import 'dart:math' as math;
import 'dart:ui' show Color;

import 'effect.dart';

/// ABA 4 DIVERSOS e ABA 5 GLOW E LUZ (beta 89).
///
/// Diversos: Chroma Key (keyer por diferenca de cor, com derramamento, clip,
/// estreitar e suavizar a borda) e S_Rays. Glow e Luz: Deep Glow, Brilho,
/// S_SpotLight, S_Glint, S_GlintRainbow, S_GlowRings, S_EdgeRays.
/// Todos em GPU pela ABI Sapphire (`shaders/luz.frag`, `shaders/chroma_key.frag`).
const efeitosLuzEDiversos = <EffectType, EffectSpec>{
  EffectType.chromaKeyPro: EffectSpec(
    id: 'chroma_key_pro',
    name: 'Chroma Key',
    category: 'Misc',
    hasColor: true,
    defaultColor: Color(0xFF00B140),
    colorLabels: ['Cor da tela'],
    synonyms: [
      'chroma',
      'fundo verde',
      'green screen',
      'keylight',
      'recorte',
      'tela verde',
      'tela azul',
    ],
    params: {
      'metodo': EffectParam(
        'Método',
        0,
        0,
        1,
        kind: ParamKind.choice,
        options: ['Diferença de cor', 'Distância de cor'],
      ),
      'ganho': EffectParam(
        'Ganho da tela',
        100,
        0,
        200,
        unit: '%',
        decimals: 0,
      ),
      'equilibrio': EffectParam(
        'Equilíbrio da tela',
        50,
        0,
        100,
        unit: '%',
        decimals: 0,
      ),
      'tolerancia': EffectParam(
        'Tolerância',
        20,
        0,
        100,
        unit: '%',
        decimals: 1,
      ),
      'suavidade': EffectParam('Suavidade', 10, 0, 100, unit: '%', decimals: 1),
      'clip_preto': EffectParam(
        'Clip preto',
        0,
        0,
        100,
        unit: '%',
        decimals: 1,
      ),
      'clip_branco': EffectParam(
        'Clip branco',
        100,
        0,
        100,
        unit: '%',
        decimals: 1,
      ),
      'derramamento': EffectParam(
        'Remover derramamento',
        100,
        0,
        100,
        unit: '%',
        decimals: 0,
      ),
      'estreitar': EffectParam(
        'Estreitar',
        0,
        -10,
        10,
        unit: 'px',
        decimals: 1,
        dragStep: .05,
      ),
      'suavizar_borda': EffectParam(
        'Suavizar borda',
        1,
        0,
        10,
        unit: 'px',
        decimals: 1,
        dragStep: .05,
      ),
      'ver': EffectParam(
        'Ver',
        0,
        0,
        1,
        kind: ParamKind.choice,
        options: ['Resultado', 'Matte'],
      ),
    },
    montar: ['ganho', 'clip_preto', 'clip_branco', 'derramamento'],
    presets: [
      EffectPronto('Tela verde', {'metodo': 0, 'ganho': 100, 'equilibrio': 50}),
      EffectPronto('Tela azul', {'metodo': 0, 'ganho': 105, 'equilibrio': 50}),
      EffectPronto('Borda limpa', {
        'clip_preto': 12,
        'clip_branco': 88,
        'estreitar': 1,
        'suavizar_borda': 1.5,
      }),
    ],
  ),
  EffectType.sRays: EffectSpec(
    id: 's_rays',
    name: 'S_Rays',
    category: 'Misc',
    hasColor: true,
    defaultColor: Color(0xFFFFF4DC),
    colorLabels: ['Cor'],
    synonyms: ['rays', 'raios', 'luz volumetrica', 'god rays', 'sapphire'],
    params: {
      'centro_x': EffectParam(
        'Centro X',
        .5,
        -1,
        2,
        kind: ParamKind.point,
        relative: true,
      ),
      'centro_y': EffectParam(
        'Centro Y',
        .5,
        -1,
        2,
        kind: ParamKind.point,
        relative: true,
      ),
      'comprimento': EffectParam(
        'Comprimento',
        40,
        0,
        100,
        unit: '%',
        decimals: 1,
      ),
      'limiar': EffectParam('Limiar', 50, 0, 100, unit: '%', decimals: 1),
      'brilho': EffectParam('Brilho', 100, 0, 400, unit: '%', decimals: 0),
      'decaimento': EffectParam(
        'Decaimento',
        50,
        0,
        100,
        unit: '%',
        decimals: 0,
      ),
    },
    montar: ['comprimento', 'brilho'],
    presets: [
      EffectPronto('Raios suaves', {'comprimento': 30, 'brilho': 80}),
      EffectPronto('Explosão de luz', {
        'comprimento': 80,
        'brilho': 220,
        'limiar': 35,
      }),
    ],
  ),
  EffectType.deepGlow: EffectSpec(
    id: 'deep_glow',
    name: 'Deep Glow',
    category: 'Light',
    hasColor: true,
    defaultColor: Color(0xFFFFFFFF),
    colorLabels: ['Tingimento'],
    synonyms: ['deep glow', 'glow', 'brilho', 'neon', 'bloom'],
    params: {
      'raio': EffectParam(
        'Raio',
        120,
        0,
        1000,
        unit: 'px',
        decimals: 0,
        dragStep: .5,
      ),
      'exposicao': EffectParam(
        'Exposição',
        100,
        0,
        1000,
        unit: '%',
        decimals: 0,
      ),
      'limiar': EffectParam('Limiar', 0, 0, 100, unit: '%', decimals: 1),
      'suavidade': EffectParam('Suavidade', 20, 0, 100, unit: '%', decimals: 1),
      'tingimento': EffectParam(
        'Tingimento',
        0,
        0,
        100,
        unit: '%',
        decimals: 0,
      ),
    },
    montar: ['raio', 'exposicao'],
    presets: [
      EffectPronto('Neon', {'raio': 90, 'exposicao': 180}),
      EffectPronto('Aura', {'raio': 300, 'exposicao': 120, 'limiar': 20}),
    ],
  ),
  EffectType.brilho: EffectSpec(
    id: 'brilho',
    name: 'Brilho',
    category: 'Light',
    hasColor: true,
    defaultColor: Color(0xFFFFFFFF),
    colorLabels: ['Tingimento'],
    synonyms: ['glow', 'brilho', 'luz'],
    params: {
      'raio': EffectParam(
        'Raio',
        30,
        0,
        400,
        unit: 'px',
        decimals: 0,
        dragStep: .5,
      ),
      'intensidade': EffectParam(
        'Intensidade',
        100,
        0,
        400,
        unit: '%',
        decimals: 0,
      ),
      'limiar': EffectParam('Limiar', 50, 0, 100, unit: '%', decimals: 1),
      'suavidade': EffectParam('Suavidade', 20, 0, 100, unit: '%', decimals: 1),
      'tingimento': EffectParam(
        'Tingimento',
        0,
        0,
        100,
        unit: '%',
        decimals: 0,
      ),
    },
    montar: ['raio', 'intensidade'],
    presets: [
      EffectPronto('Suave', {'raio': 20, 'intensidade': 60}),
      EffectPronto('Forte', {'raio': 60, 'intensidade': 220, 'limiar': 30}),
    ],
  ),
  EffectType.sSpotLight: EffectSpec(
    id: 's_spotlight',
    name: 'S_SpotLight',
    category: 'Light',
    hasColor: true,
    defaultColor: Color(0xFFFFFFFF),
    colorLabels: ['Cor da luz'],
    synonyms: ['spotlight', 'holofote', 'luz', 'sapphire'],
    params: {
      'centro_x': EffectParam(
        'Centro X',
        .5,
        -1,
        2,
        kind: ParamKind.point,
        relative: true,
      ),
      'centro_y': EffectParam(
        'Centro Y',
        .5,
        -1,
        2,
        kind: ParamKind.point,
        relative: true,
      ),
      'largura': EffectParam(
        'Largura',
        400,
        0,
        4000,
        unit: 'px',
        decimals: 0,
        dragStep: .5,
      ),
      'altura': EffectParam(
        'Altura',
        400,
        0,
        4000,
        unit: 'px',
        decimals: 0,
        dragStep: .5,
      ),
      'rotacao': EffectParam('Rotação', 0, -360, 360, unit: '°', decimals: 1),
      'suavidade': EffectParam('Suavidade', 50, 0, 100, unit: '%', decimals: 1),
      'brilho': EffectParam('Brilho', 120, 0, 400, unit: '%', decimals: 0),
      'fundo': EffectParam('Fundo', 25, 0, 100, unit: '%', decimals: 0),
    },
    montar: ['largura', 'brilho', 'fundo'],
    presets: [
      EffectPronto('Palco', {'largura': 500, 'altura': 500, 'fundo': 15}),
      EffectPronto('Faixa', {'largura': 1600, 'altura': 260, 'fundo': 35}),
    ],
  ),
  EffectType.sGlint: EffectSpec(
    id: 's_glint',
    name: 'S_Glint',
    category: 'Light',
    hasColor: true,
    defaultColor: Color(0xFFFFFFFF),
    colorLabels: ['Cor'],
    synonyms: ['glint', 'estrela', 'star', 'cintilar', 'brilho', 'sapphire'],
    params: {
      'limiar': EffectParam('Limiar', 70, 0, 100, unit: '%', decimals: 1),
      'comprimento': EffectParam(
        'Comprimento',
        120,
        0,
        1000,
        unit: 'px',
        decimals: 0,
        dragStep: .5,
      ),
      'bracos': EffectParam(
        'Braços',
        1,
        0,
        3,
        kind: ParamKind.choice,
        options: ['2', '4', '6', '8'],
      ),
      'rotacao': EffectParam('Rotação', 45, -360, 360, unit: '°', decimals: 1),
      'brilho': EffectParam('Brilho', 150, 0, 600, unit: '%', decimals: 0),
      'decaimento': EffectParam(
        'Decaimento',
        50,
        0,
        100,
        unit: '%',
        decimals: 0,
      ),
    },
    montar: ['comprimento', 'brilho'],
    presets: [
      EffectPronto('Estrela', {'bracos': 1, 'comprimento': 160}),
      EffectPronto('Cruz longa', {
        'bracos': 0,
        'comprimento': 400,
        'rotacao': 0,
      }),
    ],
  ),
  EffectType.sGlintRainbow: EffectSpec(
    id: 's_glint_rainbow',
    name: 'S_GlintRainbow',
    category: 'Light',
    synonyms: ['glint rainbow', 'arco iris', 'estrela', 'prisma', 'sapphire'],
    params: {
      'limiar': EffectParam('Limiar', 70, 0, 100, unit: '%', decimals: 1),
      'comprimento': EffectParam(
        'Comprimento',
        160,
        0,
        1000,
        unit: 'px',
        decimals: 0,
        dragStep: .5,
      ),
      'bracos': EffectParam(
        'Braços',
        1,
        0,
        3,
        kind: ParamKind.choice,
        options: ['2', '4', '6', '8'],
      ),
      'rotacao': EffectParam('Rotação', 45, -360, 360, unit: '°', decimals: 1),
      'brilho': EffectParam('Brilho', 150, 0, 600, unit: '%', decimals: 0),
      'decaimento': EffectParam(
        'Decaimento',
        40,
        0,
        100,
        unit: '%',
        decimals: 0,
      ),
      'espalhar': EffectParam(
        'Espalhar cores',
        100,
        0,
        400,
        unit: '%',
        decimals: 0,
      ),
      'matiz': EffectParam(
        'Deslocar matiz',
        0,
        -360,
        360,
        unit: '°',
        decimals: 1,
      ),
    },
    montar: ['comprimento', 'espalhar'],
    presets: [
      EffectPronto('Prisma', {'espalhar': 150, 'comprimento': 220}),
    ],
  ),
  EffectType.sGlowRings: EffectSpec(
    id: 's_glow_rings',
    name: 'S_GlowRings',
    category: 'Light',
    hasColor: true,
    defaultColor: Color(0xFFFFD28A),
    colorLabels: ['Cor dos anéis'],
    synonyms: ['glow rings', 'aneis', 'halo', 'lens', 'sapphire'],
    params: {
      'limiar': EffectParam('Limiar', 70, 0, 100, unit: '%', decimals: 1),
      'raio_dos_aneis': EffectParam(
        'Raio dos anéis',
        60,
        1,
        1000,
        unit: 'px',
        decimals: 0,
        dragStep: .5,
      ),
      'aneis': EffectParam('Anéis', 3, 1, 5, decimals: 0, dragStep: .05),
      'espessura': EffectParam('Espessura', 30, 0, 100, unit: '%', decimals: 0),
      'raio_do_brilho': EffectParam(
        'Raio do brilho',
        20,
        0,
        400,
        unit: 'px',
        decimals: 0,
        dragStep: .5,
      ),
      'brilho': EffectParam('Brilho', 120, 0, 600, unit: '%', decimals: 0),
    },
    montar: ['raio_dos_aneis', 'aneis', 'brilho'],
    presets: [
      EffectPronto('Halo', {'aneis': 1, 'raio_dos_aneis': 90}),
      EffectPronto('Ondas', {
        'aneis': 5,
        'raio_dos_aneis': 40,
        'espessura': 20,
      }),
    ],
  ),
  EffectType.sEdgeRays: EffectSpec(
    id: 's_edge_rays',
    name: 'S_EdgeRays',
    category: 'Light',
    hasColor: true,
    defaultColor: Color(0xFFBFE4FF),
    colorLabels: ['Cor'],
    synonyms: ['edge rays', 'raios de borda', 'contorno', 'luz', 'sapphire'],
    params: {
      'centro_x': EffectParam(
        'Centro X',
        .5,
        -1,
        2,
        kind: ParamKind.point,
        relative: true,
      ),
      'centro_y': EffectParam(
        'Centro Y',
        .5,
        -1,
        2,
        kind: ParamKind.point,
        relative: true,
      ),
      'comprimento': EffectParam(
        'Comprimento',
        35,
        0,
        100,
        unit: '%',
        decimals: 1,
      ),
      'limiar': EffectParam(
        'Limiar da borda',
        10,
        0,
        100,
        unit: '%',
        decimals: 1,
      ),
      'brilho': EffectParam('Brilho', 150, 0, 600, unit: '%', decimals: 0),
      'decaimento': EffectParam(
        'Decaimento',
        50,
        0,
        100,
        unit: '%',
        decimals: 0,
      ),
    },
    montar: ['comprimento', 'brilho'],
    presets: [
      EffectPronto('Contorno de luz', {'comprimento': 20, 'brilho': 220}),
    ],
  ),
};

double _v(EffectInstance e, String k, Duration t) {
  final p = e.spec.params[k]!;
  final bruto = e.paramAt(k, t);
  if (!bruto.isFinite) return p.initial;
  return bruto.clamp(p.min, p.max).toDouble();
}

double _r(EffectInstance e, String k, Duration t) =>
    _v(e, k, t) * math.pi / 180;

List<double> valoresLuz(EffectInstance e, Duration t) {
  double v(String k) => _v(e, k, t);
  double p(String k) => _v(e, k, t) / 100;
  return switch (e.type) {
    EffectType.brilho => [
      1,
      v('raio'),
      p('intensidade'),
      p('limiar'),
      p('suavidade'),
      p('tingimento'),
    ],
    EffectType.deepGlow => [
      2,
      v('raio'),
      p('exposicao'),
      p('limiar'),
      p('suavidade'),
      p('tingimento'),
    ],
    EffectType.sSpotLight => [
      3,
      v('centro_x'),
      v('centro_y'),
      v('largura'),
      v('altura'),
      _r(e, 'rotacao', t),
      p('suavidade'),
      p('brilho'),
      p('fundo'),
    ],
    EffectType.sGlint => [
      4,
      p('limiar'),
      v('comprimento'),
      v('bracos').roundToDouble() + 1,
      _r(e, 'rotacao', t),
      p('brilho'),
      p('decaimento'),
      0,
      0,
    ],
    EffectType.sGlintRainbow => [
      5,
      p('limiar'),
      v('comprimento'),
      v('bracos').roundToDouble() + 1,
      _r(e, 'rotacao', t),
      p('brilho'),
      p('decaimento'),
      p('espalhar'),
      _r(e, 'matiz', t),
    ],
    EffectType.sGlowRings => [
      6,
      p('limiar'),
      v('raio_dos_aneis'),
      v('aneis').roundToDouble(),
      p('espessura'),
      v('raio_do_brilho'),
      p('brilho'),
    ],
    EffectType.sEdgeRays => [
      7,
      v('centro_x'),
      v('centro_y'),
      p('comprimento'),
      p('limiar'),
      p('brilho'),
      p('decaimento'),
    ],
    EffectType.sRays => [
      8,
      v('centro_x'),
      v('centro_y'),
      p('comprimento'),
      p('limiar'),
      p('brilho'),
      p('decaimento'),
    ],
    _ => const [0],
  };
}

List<double> valoresChromaKey(EffectInstance e, Duration t) {
  double v(String k) => _v(e, k, t);
  double p(String k) => _v(e, k, t) / 100;
  return [
    v('metodo').roundToDouble(),
    p('ganho'),
    p('equilibrio'),
    p('tolerancia'),
    p('suavidade'),
    p('clip_preto'),
    p('clip_branco'),
    p('derramamento'),
    v('estreitar'),
    v('suavizar_borda'),
    v('ver').roundToDouble(),
  ];
}
