# Lote 1 de traducoes (105 chaves). Ver tools/i18n_translate.py.
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from i18n_translate import run

EN = {
 "ds_1_ajuste": "1 setting", "ds_arrastar_reordenar": "Drag to reorder",
 "ds_avancado": "Advanced", "ds_cancelar": "Cancel", "ds_conta_incompleta": "Incomplete account",
 "ds_cor": "Colour", "ds_pronto": "Ready", "ds_rapidas": "Quick",
 "editor_2f_fps": "%.2f fps", "editor_abrir": "Open",
 "editor_adicionar_camada": "Add layer",
 "editor_adicionar_toque_linha_ou_vazio_arraste": "Add: tap the line or empty space; drag to bend",
 "editor_agrupar": "Group",
 "editor_agrupar_camadas_escolhidas": "Group the selected layers",
 "editor_alguma_camada_solo_previa_som_so": "With a layer soloed, preview and sound play only that one",
 "editor_alinhar_base_tela": "Align to bottom of screen",
 "editor_alinhar_direita_tela": "Align to right of screen",
 "editor_alinhar_esquerda_tela": "Align to left of screen",
 "editor_alinhar_fins": "Align ends", "editor_alinhar_inicios": "Align starts",
 "editor_alinhar_topo_tela": "Align to top of screen",
 "editor_alta": "High", "editor_altura": "Height",
 "editor_aparar_empurra_camadas_seguintes_excluir_fecha": "Trim pushes the following layers; delete closes the gap",
 "editor_aparar_fim_cabecote": "Trim the end at the playhead",
 "editor_aparar_inicio_cabecote": "Trim the start at the playhead",
 "editor_aparar_projeto_cabecote": "Trim the project at the playhead",
 "editor_aparece_aqui_editor_fica_fora_video": "Shows here in the editor and stays out of the exported video",
 "editor_bloquear_camada": "Lock layer",
 "editor_borra_direcao_movimento_obturador_nas_configuracoes": "Blurs along the motion (shutter in the project settings)",
 "editor_borra_mexe_dentro_video_pelos_vetores": "Blurs what moves inside the video (from the motion vectors)",
 "editor_buscar_camadas": "Search layers…", "editor_camada": "Layer",
 "editor_camada_ajuste": "Adjustment layer", "editor_camada_bloqueada": "Layer locked",
 "editor_camada_bloqueada_desbloqueie_editar": "Layer locked: unlock to edit",
 "editor_camadas_desfoque_movimento_so_borram_isto": "Motion-blurred layers only blur with this on",
 "editor_cancelar": "Cancel", "editor_cancelar_selecao": "Clear selection",
 "editor_canto_suave_toque_ponto_alternar": "Corner/Smooth: tap the point to switch",
 "editor_centralizar_horizontal": "Centre horizontally",
 "editor_centralizar_vertical": "Centre vertically",
 "editor_colar_camada_cabecote": "Paste layer at the playhead",
 "editor_colar_efeitos": "Paste effects", "editor_colar_estilo": "Paste style",
 "editor_colar_keyframes_cabecote": "Paste keyframes at the playhead",
 "editor_compartilhar": "Share", "editor_concluir": "Done",
 "editor_concluir_desenho": "Finish drawing", "editor_converter_grupo": "Convert to group",
 "editor_copiar_camada": "Copy layer", "editor_copiar_colar": "Copy and paste",
 "editor_copiar_efeitos": "Copy effects", "editor_copiar_estilo": "Copy style",
 "editor_copiar_keyframes_cabecote": "Copy keyframes from the playhead",
 "editor_cor": "Colour",
 "editor_cria_nulo_segue_ponto_ligue_outras": "Creates a Null that follows the point — parent other layers to it",
 "editor_desagrupar": "Ungroup", "editor_desbloquear": "Unlock",
 "editor_desbloquear_camada": "Unlock layer", "editor_desenhar_pontos": "Draw with points",
 "editor_desenhe_dedo_direto_palco_cada_traco": "Draw with your finger right on the stage. Each stroke becomes a path you can edit and animate.",
 "editor_desfazer": "Undo", "editor_desfoque_movimento": "Motion blur",
 "editor_desfoque_movimento_composicao": "Composition motion blur",
 "editor_desfoque_movimento_video": "Video motion blur",
 "editor_desligar_som_segure_volume": "Mute · hold for volume",
 "editor_detectar_batidas_camada_escolhida": "Detect beats from the selected layer",
 "editor_diagnostico_tela": "On-screen diagnostics",
 "editor_distribuir_horizontal_vaos_iguais": "Distribute horizontally (equal gaps)",
 "editor_distribuir_vertical_vaos_iguais": "Distribute vertically (equal gaps)",
 "editor_dividir_cabecote": "Split at the playhead", "editor_duplicar": "Duplicate",
 "editor_duplicar_camada": "Duplicate layer", "editor_duracao": "Duration",
 "editor_edicao": "Editing", "editor_editando_grupo": "Editing the group",
 "editor_editar_grupo": "Edit the group",
 "editor_efeitos_desta_camada_valem_todas_baixo": "This layer's effects apply to every layer below",
 "editor_elipse": "Ellipse", "editor_else": " else ",
 "editor_entrar_grupo": "Enter the group", "editor_enviar_tras": "Send backward",
 "editor_escada_comeca_quando_cima_termina": "Staggered: one starts when the one above ends",
 "editor_escala": "Scale", "editor_estabilizar_pelo_ponto": "Stabilise from the point",
 "editor_estilo_efeitos": "Style and effects", "editor_estrela": "Star",
 "editor_etiqueta": "Label", "editor_excluir_camada": "Delete layer",
 "editor_excluir_selecao": "Delete selection", "editor_exportar": "Export",
 "editor_extrair_audio": "Extract the audio", "editor_fechar": "Close",
 "editor_fechar_adicionar": "Close add", "editor_formato": "Format", "editor_foto": "Photo",
 "editor_fundo_composicao": "composition background", "editor_galeria": "Gallery",
 "editor_grupo": "Group", "editor_guia_nao_exporta": "Guide (not exported)",
 "editor_h_264_abre_qualquer_aparelho_rede": "H.264: opens on any device and social network.",
 "editor_hevc_arquivo_menor_mesma_qualidade_alguns": "HEVC: smaller file, same quality. Some older devices can't play it.",
 "editor_importar_svg": "Import SVG", "editor_ir": "Go",
}

ES = {
 "ds_1_ajuste": "1 ajuste", "ds_arrastar_reordenar": "Arrastra para reordenar",
 "ds_avancado": "Avanzado", "ds_cancelar": "Cancelar", "ds_conta_incompleta": "Cuenta incompleta",
 "ds_cor": "Color", "ds_pronto": "Listo", "ds_rapidas": "Rápidas",
 "editor_2f_fps": "%.2f fps", "editor_abrir": "Abrir",
 "editor_adicionar_camada": "Añadir capa",
 "editor_adicionar_toque_linha_ou_vazio_arraste": "Añadir: toca la línea o el vacío; arrastra para curvar",
 "editor_agrupar": "Agrupar",
 "editor_agrupar_camadas_escolhidas": "Agrupar las capas elegidas",
 "editor_alguma_camada_solo_previa_som_so": "Con una capa en solo, la vista previa y el sonido solo suenan en ella",
 "editor_alinhar_base_tela": "Alinear abajo de la pantalla",
 "editor_alinhar_direita_tela": "Alinear a la derecha de la pantalla",
 "editor_alinhar_esquerda_tela": "Alinear a la izquierda de la pantalla",
 "editor_alinhar_fins": "Alinear los finales", "editor_alinhar_inicios": "Alinear los inicios",
 "editor_alinhar_topo_tela": "Alinear arriba de la pantalla",
 "editor_alta": "Alta", "editor_altura": "Altura",
 "editor_aparar_empurra_camadas_seguintes_excluir_fecha": "Recortar empuja las capas siguientes; eliminar cierra el hueco",
 "editor_aparar_fim_cabecote": "Recortar el final en el cabezal",
 "editor_aparar_inicio_cabecote": "Recortar el inicio en el cabezal",
 "editor_aparar_projeto_cabecote": "Recortar el proyecto en el cabezal",
 "editor_aparece_aqui_editor_fica_fora_video": "Aparece aquí en el editor y queda fuera del vídeo exportado",
 "editor_bloquear_camada": "Bloquear capa",
 "editor_borra_direcao_movimento_obturador_nas_configuracoes": "Desenfoca en la dirección del movimiento (obturador en los ajustes del proyecto)",
 "editor_borra_mexe_dentro_video_pelos_vetores": "Desenfoca lo que se mueve dentro del vídeo (por los vectores de movimiento)",
 "editor_buscar_camadas": "Buscar capas…", "editor_camada": "Capa",
 "editor_camada_ajuste": "Capa de ajuste", "editor_camada_bloqueada": "Capa bloqueada",
 "editor_camada_bloqueada_desbloqueie_editar": "Capa bloqueada: desbloquea para editar",
 "editor_camadas_desfoque_movimento_so_borram_isto": "Las capas con desenfoque de movimiento solo desenfocan con esto activado",
 "editor_cancelar": "Cancelar", "editor_cancelar_selecao": "Quitar selección",
 "editor_canto_suave_toque_ponto_alternar": "Esquina/Suave: toca el punto para alternar",
 "editor_centralizar_horizontal": "Centrar en horizontal",
 "editor_centralizar_vertical": "Centrar en vertical",
 "editor_colar_camada_cabecote": "Pegar capa en el cabezal",
 "editor_colar_efeitos": "Pegar efectos", "editor_colar_estilo": "Pegar estilo",
 "editor_colar_keyframes_cabecote": "Pegar keyframes en el cabezal",
 "editor_compartilhar": "Compartir", "editor_concluir": "Listo",
 "editor_concluir_desenho": "Terminar el dibujo", "editor_converter_grupo": "Convertir en grupo",
 "editor_copiar_camada": "Copiar capa", "editor_copiar_colar": "Copiar y pegar",
 "editor_copiar_efeitos": "Copiar efectos", "editor_copiar_estilo": "Copiar estilo",
 "editor_copiar_keyframes_cabecote": "Copiar keyframes del cabezal",
 "editor_cor": "Color",
 "editor_cria_nulo_segue_ponto_ligue_outras": "Crea un Nulo que sigue al punto — vincula otras capas a él",
 "editor_desagrupar": "Desagrupar", "editor_desbloquear": "Desbloquear",
 "editor_desbloquear_camada": "Desbloquear capa", "editor_desenhar_pontos": "Dibujar con puntos",
 "editor_desenhe_dedo_direto_palco_cada_traco": "Dibuja con el dedo directamente en el escenario. Cada trazo se vuelve un camino que puedes editar y animar.",
 "editor_desfazer": "Deshacer", "editor_desfoque_movimento": "Desenfoque de movimiento",
 "editor_desfoque_movimento_composicao": "Desenfoque de movimiento de la composición",
 "editor_desfoque_movimento_video": "Desenfoque del movimiento del vídeo",
 "editor_desligar_som_segure_volume": "Silenciar · mantén para el volumen",
 "editor_detectar_batidas_camada_escolhida": "Detectar los golpes de la capa elegida",
 "editor_diagnostico_tela": "Diagnóstico en pantalla",
 "editor_distribuir_horizontal_vaos_iguais": "Distribuir en horizontal (huecos iguales)",
 "editor_distribuir_vertical_vaos_iguais": "Distribuir en vertical (huecos iguales)",
 "editor_dividir_cabecote": "Dividir en el cabezal", "editor_duplicar": "Duplicar",
 "editor_duplicar_camada": "Duplicar capa", "editor_duracao": "Duración",
 "editor_edicao": "Edición", "editor_editando_grupo": "Editando el grupo",
 "editor_editar_grupo": "Editar el grupo",
 "editor_efeitos_desta_camada_valem_todas_baixo": "Los efectos de esta capa valen para todas las de abajo",
 "editor_elipse": "Elipse", "editor_else": " else ",
 "editor_entrar_grupo": "Entrar en el grupo", "editor_enviar_tras": "Enviar atrás",
 "editor_escada_comeca_quando_cima_termina": "En escalera: una empieza cuando termina la de arriba",
 "editor_escala": "Escala", "editor_estabilizar_pelo_ponto": "Estabilizar por el punto",
 "editor_estilo_efeitos": "Estilo y efectos", "editor_estrela": "Estrella",
 "editor_etiqueta": "Etiqueta", "editor_excluir_camada": "Eliminar capa",
 "editor_excluir_selecao": "Eliminar selección", "editor_exportar": "Exportar",
 "editor_extrair_audio": "Extraer el audio", "editor_fechar": "Cerrar",
 "editor_fechar_adicionar": "Cerrar añadir", "editor_formato": "Formato", "editor_foto": "Foto",
 "editor_fundo_composicao": "fondo de la composición", "editor_galeria": "Galería",
 "editor_grupo": "Grupo", "editor_guia_nao_exporta": "Guía (no se exporta)",
 "editor_h_264_abre_qualquer_aparelho_rede": "H.264: abre en cualquier dispositivo y red social.",
 "editor_hevc_arquivo_menor_mesma_qualidade_alguns": "HEVC: archivo más pequeño, misma calidad. Algunos dispositivos antiguos no lo reproducen.",
 "editor_importar_svg": "Importar SVG", "editor_ir": "Ir",
}

RU = {
 "ds_1_ajuste": "1 настройка", "ds_arrastar_reordenar": "Перетащите, чтобы изменить порядок",
 "ds_avancado": "Дополнительно", "ds_cancelar": "Отмена", "ds_conta_incompleta": "Аккаунт не заполнен",
 "ds_cor": "Цвет", "ds_pronto": "Готово", "ds_rapidas": "Быстрые",
 "editor_2f_fps": "%.2f кадр/с", "editor_abrir": "Открыть",
 "editor_adicionar_camada": "Добавить слой",
 "editor_adicionar_toque_linha_ou_vazio_arraste": "Добавить: коснитесь линии или пустого места; тяните, чтобы изогнуть",
 "editor_agrupar": "Сгруппировать",
 "editor_agrupar_camadas_escolhidas": "Сгруппировать выбранные слои",
 "editor_alguma_camada_solo_previa_som_so": "Если слой в режиме solo, просмотр и звук воспроизводят только его",
 "editor_alinhar_base_tela": "Выровнять по низу экрана",
 "editor_alinhar_direita_tela": "Выровнять по правому краю экрана",
 "editor_alinhar_esquerda_tela": "Выровнять по левому краю экрана",
 "editor_alinhar_fins": "Выровнять концы", "editor_alinhar_inicios": "Выровнять начала",
 "editor_alinhar_topo_tela": "Выровнять по верху экрана",
 "editor_alta": "Высокая", "editor_altura": "Высота",
 "editor_aparar_empurra_camadas_seguintes_excluir_fecha": "Обрезка сдвигает следующие слои; удаление закрывает промежуток",
 "editor_aparar_fim_cabecote": "Обрезать конец по курсору",
 "editor_aparar_inicio_cabecote": "Обрезать начало по курсору",
 "editor_aparar_projeto_cabecote": "Обрезать проект по курсору",
 "editor_aparece_aqui_editor_fica_fora_video": "Видно здесь, в редакторе, и не попадает в экспортируемое видео",
 "editor_bloquear_camada": "Заблокировать слой",
 "editor_borra_direcao_movimento_obturador_nas_configuracoes": "Размывает по направлению движения (выдержка в настройках проекта)",
 "editor_borra_mexe_dentro_video_pelos_vetores": "Размывает то, что движется внутри видео (по векторам движения)",
 "editor_buscar_camadas": "Поиск слоёв…", "editor_camada": "Слой",
 "editor_camada_ajuste": "Слой-коррекция", "editor_camada_bloqueada": "Слой заблокирован",
 "editor_camada_bloqueada_desbloqueie_editar": "Слой заблокирован: снимите блокировку, чтобы редактировать",
 "editor_camadas_desfoque_movimento_so_borram_isto": "Слои с размытием движения размываются только при включённом параметре",
 "editor_cancelar": "Отмена", "editor_cancelar_selecao": "Снять выделение",
 "editor_canto_suave_toque_ponto_alternar": "Угол/Сглаженный: коснитесь точки, чтобы переключить",
 "editor_centralizar_horizontal": "Центрировать по горизонтали",
 "editor_centralizar_vertical": "Центрировать по вертикали",
 "editor_colar_camada_cabecote": "Вставить слой по курсору",
 "editor_colar_efeitos": "Вставить эффекты", "editor_colar_estilo": "Вставить стиль",
 "editor_colar_keyframes_cabecote": "Вставить ключи по курсору",
 "editor_compartilhar": "Поделиться", "editor_concluir": "Готово",
 "editor_concluir_desenho": "Закончить рисунок", "editor_converter_grupo": "Преобразовать в группу",
 "editor_copiar_camada": "Копировать слой", "editor_copiar_colar": "Копировать и вставить",
 "editor_copiar_efeitos": "Копировать эффекты", "editor_copiar_estilo": "Копировать стиль",
 "editor_copiar_keyframes_cabecote": "Копировать ключи с курсора",
 "editor_cor": "Цвет",
 "editor_cria_nulo_segue_ponto_ligue_outras": "Создаёт Null, следящий за точкой — привяжите к нему другие слои",
 "editor_desagrupar": "Разгруппировать", "editor_desbloquear": "Разблокировать",
 "editor_desbloquear_camada": "Разблокировать слой", "editor_desenhar_pontos": "Рисовать точками",
 "editor_desenhe_dedo_direto_palco_cada_traco": "Рисуйте пальцем прямо на сцене. Каждый штрих становится контуром, который можно править и анимировать.",
 "editor_desfazer": "Отменить", "editor_desfoque_movimento": "Размытие движения",
 "editor_desfoque_movimento_composicao": "Размытие движения композиции",
 "editor_desfoque_movimento_video": "Размытие движения видео",
 "editor_desligar_som_segure_volume": "Выключить звук · удерживайте для громкости",
 "editor_detectar_batidas_camada_escolhida": "Найти биты выбранного слоя",
 "editor_diagnostico_tela": "Диагностика на экране",
 "editor_distribuir_horizontal_vaos_iguais": "Распределить по горизонтали (равные промежутки)",
 "editor_distribuir_vertical_vaos_iguais": "Распределить по вертикали (равные промежутки)",
 "editor_dividir_cabecote": "Разделить по курсору", "editor_duplicar": "Дублировать",
 "editor_duplicar_camada": "Дублировать слой", "editor_duracao": "Длительность",
 "editor_edicao": "Монтаж", "editor_editando_grupo": "Редактирование группы",
 "editor_editar_grupo": "Редактировать группу",
 "editor_efeitos_desta_camada_valem_todas_baixo": "Эффекты этого слоя действуют на все слои ниже",
 "editor_elipse": "Эллипс", "editor_else": " else ",
 "editor_entrar_grupo": "Войти в группу", "editor_enviar_tras": "Назад",
 "editor_escada_comeca_quando_cima_termina": "Лестницей: один начинается, когда заканчивается верхний",
 "editor_escala": "Масштаб", "editor_estabilizar_pelo_ponto": "Стабилизировать по точке",
 "editor_estilo_efeitos": "Стиль и эффекты", "editor_estrela": "Звезда",
 "editor_etiqueta": "Метка", "editor_excluir_camada": "Удалить слой",
 "editor_excluir_selecao": "Удалить выделенное", "editor_exportar": "Экспорт",
 "editor_extrair_audio": "Извлечь звук", "editor_fechar": "Закрыть",
 "editor_fechar_adicionar": "Закрыть добавление", "editor_formato": "Формат", "editor_foto": "Фото",
 "editor_fundo_composicao": "фон композиции", "editor_galeria": "Галерея",
 "editor_grupo": "Группа", "editor_guia_nao_exporta": "Направляющая (не экспортируется)",
 "editor_h_264_abre_qualquer_aparelho_rede": "H.264: открывается на любом устройстве и в соцсети.",
 "editor_hevc_arquivo_menor_mesma_qualidade_alguns": "HEVC: файл меньше при том же качестве. Некоторые старые устройства не воспроизводят его.",
 "editor_importar_svg": "Импорт SVG", "editor_ir": "Перейти",
}

HI = {
 "ds_1_ajuste": "1 सेटिंग", "ds_arrastar_reordenar": "क्रम बदलने के लिए खींचें",
 "ds_avancado": "विस्तृत", "ds_cancelar": "रद्द करें", "ds_conta_incompleta": "खाता अधूरा है",
 "ds_cor": "रंग", "ds_pronto": "तैयार", "ds_rapidas": "तेज़",
 "editor_2f_fps": "%.2f fps", "editor_abrir": "खोलें",
 "editor_adicionar_camada": "लेयर जोड़ें",
 "editor_adicionar_toque_linha_ou_vazio_arraste": "जोड़ें: लाइन या ख़ाली जगह दबाएँ; मोड़ने के लिए खींचें",
 "editor_agrupar": "समूह बनाएँ",
 "editor_agrupar_camadas_escolhidas": "चुनी हुई लेयर को समूहित करें",
 "editor_alguma_camada_solo_previa_som_so": "किसी लेयर के solo में होने पर प्रीव्यू और आवाज़ सिर्फ़ उसी की चलती है",
 "editor_alinhar_base_tela": "स्क्रीन के नीचे संरेखित करें",
 "editor_alinhar_direita_tela": "स्क्रीन के दाएँ संरेखित करें",
 "editor_alinhar_esquerda_tela": "स्क्रीन के बाएँ संरेखित करें",
 "editor_alinhar_fins": "अंत संरेखित करें", "editor_alinhar_inicios": "शुरुआत संरेखित करें",
 "editor_alinhar_topo_tela": "स्क्रीन के ऊपर संरेखित करें",
 "editor_alta": "उच्च", "editor_altura": "ऊँचाई",
 "editor_aparar_empurra_camadas_seguintes_excluir_fecha": "ट्रिम आगे की लेयर को धकेलता है; हटाने से ख़ाली जगह भर जाती है",
 "editor_aparar_fim_cabecote": "प्लेहेड पर अंत ट्रिम करें",
 "editor_aparar_inicio_cabecote": "प्लेहेड पर शुरुआत ट्रिम करें",
 "editor_aparar_projeto_cabecote": "प्लेहेड पर प्रोजेक्ट ट्रिम करें",
 "editor_aparece_aqui_editor_fica_fora_video": "एडिटर में यहाँ दिखता है और एक्सपोर्ट हुए वीडियो से बाहर रहता है",
 "editor_bloquear_camada": "लेयर लॉक करें",
 "editor_borra_direcao_movimento_obturador_nas_configuracoes": "गति की दिशा में धुंधला करें (प्रोजेक्ट सेटिंग्स में शटर)",
 "editor_borra_mexe_dentro_video_pelos_vetores": "वीडियो के अंदर जो हिलता है उसे धुंधला करें (मोशन वेक्टर से)",
 "editor_buscar_camadas": "लेयर खोजें…", "editor_camada": "लेयर",
 "editor_camada_ajuste": "समायोजन लेयर", "editor_camada_bloqueada": "लेयर लॉक है",
 "editor_camada_bloqueada_desbloqueie_editar": "लेयर लॉक है: संपादन के लिए अनलॉक करें",
 "editor_camadas_desfoque_movimento_so_borram_isto": "मोशन ब्लर वाली लेयर इसके चालू होने पर ही धुंधला करती हैं",
 "editor_cancelar": "रद्द करें", "editor_cancelar_selecao": "चयन हटाएँ",
 "editor_canto_suave_toque_ponto_alternar": "कोना/सौम्य: बदलने के लिए बिंदु दबाएँ",
 "editor_centralizar_horizontal": "क्षैतिज केंद्र में रखें",
 "editor_centralizar_vertical": "ऊर्ध्वाधर केंद्र में रखें",
 "editor_colar_camada_cabecote": "प्लेहेड पर लेयर चिपकाएँ",
 "editor_colar_efeitos": "इफ़ेक्ट चिपकाएँ", "editor_colar_estilo": "शैली चिपकाएँ",
 "editor_colar_keyframes_cabecote": "प्लेहेड पर कीफ़्रेम चिपकाएँ",
 "editor_compartilhar": "साझा करें", "editor_concluir": "हो गया",
 "editor_concluir_desenho": "ड्राइंग पूरी करें", "editor_converter_grupo": "समूह में बदलें",
 "editor_copiar_camada": "लेयर कॉपी करें", "editor_copiar_colar": "कॉपी और पेस्ट",
 "editor_copiar_efeitos": "इफ़ेक्ट कॉपी करें", "editor_copiar_estilo": "शैली कॉपी करें",
 "editor_copiar_keyframes_cabecote": "प्लेहेड से कीफ़्रेम कॉपी करें",
 "editor_cor": "रंग",
 "editor_cria_nulo_segue_ponto_ligue_outras": "बिंदु का पीछा करने वाला Null बनाता है — दूसरी लेयर उससे जोड़ें",
 "editor_desagrupar": "समूह तोड़ें", "editor_desbloquear": "अनलॉक करें",
 "editor_desbloquear_camada": "लेयर अनलॉक करें", "editor_desenhar_pontos": "बिंदुओं से बनाएँ",
 "editor_desenhe_dedo_direto_palco_cada_traco": "सीधे स्टेज पर उँगली से बनाएँ। हर स्ट्रोक एक पथ बनता है जिसे संपादित और एनिमेट किया जा सकता है।",
 "editor_desfazer": "पूर्ववत करें", "editor_desfoque_movimento": "मोशन ब्लर",
 "editor_desfoque_movimento_composicao": "कंपोज़िशन का मोशन ब्लर",
 "editor_desfoque_movimento_video": "वीडियो के मोशन का ब्लर",
 "editor_desligar_som_segure_volume": "आवाज़ बंद · वॉल्यूम के लिए दबाए रखें",
 "editor_detectar_batidas_camada_escolhida": "चुनी हुई लेयर की ताल पहचानें",
 "editor_diagnostico_tela": "स्क्रीन पर निदान",
 "editor_distribuir_horizontal_vaos_iguais": "क्षैतिज बाँटें (समान अंतराल)",
 "editor_distribuir_vertical_vaos_iguais": "ऊर्ध्वाधर बाँटें (समान अंतराल)",
 "editor_dividir_cabecote": "प्लेहेड पर विभाजित करें", "editor_duplicar": "प्रतिलिपि बनाएँ",
 "editor_duplicar_camada": "लेयर की प्रतिलिपि", "editor_duracao": "अवधि",
 "editor_edicao": "संपादन", "editor_editando_grupo": "समूह संपादित हो रहा है",
 "editor_editar_grupo": "समूह संपादित करें",
 "editor_efeitos_desta_camada_valem_todas_baixo": "इस लेयर के इफ़ेक्ट नीचे की सभी लेयर पर लागू होते हैं",
 "editor_elipse": "दीर्घवृत्त", "editor_else": " else ",
 "editor_entrar_grupo": "समूह में जाएँ", "editor_enviar_tras": "पीछे भेजें",
 "editor_escada_comeca_quando_cima_termina": "सीढ़ी में: ऊपर वाला ख़त्म होते ही अगला शुरू होता है",
 "editor_escala": "स्केल", "editor_estabilizar_pelo_ponto": "बिंदु से स्थिर करें",
 "editor_estilo_efeitos": "शैली और इफ़ेक्ट", "editor_estrela": "तारा",
 "editor_etiqueta": "लेबल", "editor_excluir_camada": "लेयर हटाएँ",
 "editor_excluir_selecao": "चयन हटाएँ", "editor_exportar": "एक्सपोर्ट",
 "editor_extrair_audio": "ऑडियो निकालें", "editor_fechar": "बंद करें",
 "editor_fechar_adicionar": "जोड़ना बंद करें", "editor_formato": "फ़ॉर्मैट", "editor_foto": "फ़ोटो",
 "editor_fundo_composicao": "कंपोज़िशन की पृष्ठभूमि", "editor_galeria": "गैलरी",
 "editor_grupo": "समूह", "editor_guia_nao_exporta": "गाइड (एक्सपोर्ट नहीं होता)",
 "editor_h_264_abre_qualquer_aparelho_rede": "H.264: किसी भी डिवाइस और सोशल नेटवर्क पर खुलता है।",
 "editor_hevc_arquivo_menor_mesma_qualidade_alguns": "HEVC: फ़ाइल छोटी, गुणवत्ता वही। कुछ पुराने डिवाइस इसे नहीं चलाते।",
 "editor_importar_svg": "SVG आयात करें", "editor_ir": "जाएँ",
}

ID = {
 "ds_1_ajuste": "1 pengaturan", "ds_arrastar_reordenar": "Seret untuk mengurutkan ulang",
 "ds_avancado": "Lanjutan", "ds_cancelar": "Batal", "ds_conta_incompleta": "Akun belum lengkap",
 "ds_cor": "Warna", "ds_pronto": "Siap", "ds_rapidas": "Cepat",
 "editor_2f_fps": "%.2f fps", "editor_abrir": "Buka",
 "editor_adicionar_camada": "Tambah lapisan",
 "editor_adicionar_toque_linha_ou_vazio_arraste": "Tambah: ketuk garis atau ruang kosong; seret untuk melengkungkan",
 "editor_agrupar": "Kelompokkan",
 "editor_agrupar_camadas_escolhidas": "Kelompokkan lapisan terpilih",
 "editor_alguma_camada_solo_previa_som_so": "Bila ada lapisan solo, pratinjau dan suara hanya memutar lapisan itu",
 "editor_alinhar_base_tela": "Rata ke bawah layar",
 "editor_alinhar_direita_tela": "Rata ke kanan layar",
 "editor_alinhar_esquerda_tela": "Rata ke kiri layar",
 "editor_alinhar_fins": "Ratakan akhir", "editor_alinhar_inicios": "Ratakan awal",
 "editor_alinhar_topo_tela": "Rata ke atas layar",
 "editor_alta": "Tinggi", "editor_altura": "Tinggi",
 "editor_aparar_empurra_camadas_seguintes_excluir_fecha": "Pemangkasan menggeser lapisan berikutnya; menghapus menutup celah",
 "editor_aparar_fim_cabecote": "Pangkas akhir di kepala playback",
 "editor_aparar_inicio_cabecote": "Pangkas awal di kepala playback",
 "editor_aparar_projeto_cabecote": "Pangkas proyek di kepala playback",
 "editor_aparece_aqui_editor_fica_fora_video": "Muncul di sini di editor dan tidak ikut ke video hasil ekspor",
 "editor_bloquear_camada": "Kunci lapisan",
 "editor_borra_direcao_movimento_obturador_nas_configuracoes": "Kabur mengikuti arah gerak (shutter di pengaturan proyek)",
 "editor_borra_mexe_dentro_video_pelos_vetores": "Mengaburkan yang bergerak di dalam video (dari vektor gerak)",
 "editor_buscar_camadas": "Cari lapisan…", "editor_camada": "Lapisan",
 "editor_camada_ajuste": "Lapisan penyesuaian", "editor_camada_bloqueada": "Lapisan terkunci",
 "editor_camada_bloqueada_desbloqueie_editar": "Lapisan terkunci: buka kunci untuk mengedit",
 "editor_camadas_desfoque_movimento_so_borram_isto": "Lapisan dengan motion blur hanya mengabur bila ini menyala",
 "editor_cancelar": "Batal", "editor_cancelar_selecao": "Hapus pilihan",
 "editor_canto_suave_toque_ponto_alternar": "Sudut/Halus: ketuk titik untuk berganti",
 "editor_centralizar_horizontal": "Pusatkan mendatar",
 "editor_centralizar_vertical": "Pusatkan tegak",
 "editor_colar_camada_cabecote": "Tempel lapisan di kepala playback",
 "editor_colar_efeitos": "Tempel efek", "editor_colar_estilo": "Tempel gaya",
 "editor_colar_keyframes_cabecote": "Tempel keyframe di kepala playback",
 "editor_compartilhar": "Bagikan", "editor_concluir": "Selesai",
 "editor_concluir_desenho": "Selesaikan gambar", "editor_converter_grupo": "Ubah jadi grup",
 "editor_copiar_camada": "Salin lapisan", "editor_copiar_colar": "Salin dan tempel",
 "editor_copiar_efeitos": "Salin efek", "editor_copiar_estilo": "Salin gaya",
 "editor_copiar_keyframes_cabecote": "Salin keyframe dari kepala playback",
 "editor_cor": "Warna",
 "editor_cria_nulo_segue_ponto_ligue_outras": "Membuat Null yang mengikuti titik — tautkan lapisan lain ke sana",
 "editor_desagrupar": "Bongkar grup", "editor_desbloquear": "Buka kunci",
 "editor_desbloquear_camada": "Buka kunci lapisan", "editor_desenhar_pontos": "Gambar dengan titik",
 "editor_desenhe_dedo_direto_palco_cada_traco": "Gambar dengan jari langsung di panggung. Tiap goresan jadi jalur yang bisa diedit dan dianimasikan.",
 "editor_desfazer": "Urungkan", "editor_desfoque_movimento": "Motion blur",
 "editor_desfoque_movimento_composicao": "Motion blur komposisi",
 "editor_desfoque_movimento_video": "Blur gerak video",
 "editor_desligar_som_segure_volume": "Bisukan · tahan untuk volume",
 "editor_detectar_batidas_camada_escolhida": "Deteksi ketukan dari lapisan terpilih",
 "editor_diagnostico_tela": "Diagnostik di layar",
 "editor_distribuir_horizontal_vaos_iguais": "Sebar mendatar (jarak sama)",
 "editor_distribuir_vertical_vaos_iguais": "Sebar tegak (jarak sama)",
 "editor_dividir_cabecote": "Bagi di kepala playback", "editor_duplicar": "Duplikat",
 "editor_duplicar_camada": "Duplikat lapisan", "editor_duracao": "Durasi",
 "editor_edicao": "Penyuntingan", "editor_editando_grupo": "Mengedit grup",
 "editor_editar_grupo": "Edit grup",
 "editor_efeitos_desta_camada_valem_todas_baixo": "Efek lapisan ini berlaku untuk semua lapisan di bawahnya",
 "editor_elipse": "Elips", "editor_else": " else ",
 "editor_entrar_grupo": "Masuk ke grup", "editor_enviar_tras": "Kirim ke belakang",
 "editor_escada_comeca_quando_cima_termina": "Bertingkat: satu mulai saat yang di atas selesai",
 "editor_escala": "Skala", "editor_estabilizar_pelo_ponto": "Stabilkan dari titik",
 "editor_estilo_efeitos": "Gaya dan efek", "editor_estrela": "Bintang",
 "editor_etiqueta": "Label", "editor_excluir_camada": "Hapus lapisan",
 "editor_excluir_selecao": "Hapus pilihan", "editor_exportar": "Ekspor",
 "editor_extrair_audio": "Ekstrak audionya", "editor_fechar": "Tutup",
 "editor_fechar_adicionar": "Tutup tambah", "editor_formato": "Format", "editor_foto": "Foto",
 "editor_fundo_composicao": "latar komposisi", "editor_galeria": "Galeri",
 "editor_grupo": "Grup", "editor_guia_nao_exporta": "Panduan (tidak diekspor)",
 "editor_h_264_abre_qualquer_aparelho_rede": "H.264: terbuka di perangkat dan media sosial mana pun.",
 "editor_hevc_arquivo_menor_mesma_qualidade_alguns": "HEVC: berkas lebih kecil, kualitas sama. Sebagian perangkat lama tidak bisa memutarnya.",
 "editor_importar_svg": "Impor SVG", "editor_ir": "Ke",
}

AR = {
 "ds_1_ajuste": "إعداد واحد", "ds_arrastar_reordenar": "اسحب لإعادة الترتيب",
 "ds_avancado": "متقدّم", "ds_cancelar": "إلغاء", "ds_conta_incompleta": "حساب غير مكتمل",
 "ds_cor": "اللون", "ds_pronto": "جاهز", "ds_rapidas": "سريعة",
 "editor_2f_fps": "%.2f إطار/ث", "editor_abrir": "فتح",
 "editor_adicionar_camada": "إضافة طبقة",
 "editor_adicionar_toque_linha_ou_vazio_arraste": "إضافة: اضغط الخط أو الفراغ؛ اسحب للانحناء",
 "editor_agrupar": "تجميع",
 "editor_agrupar_camadas_escolhidas": "تجميع الطبقات المختارة",
 "editor_alguma_camada_solo_previa_som_so": "عند تفعيل solo لطبقة، تعرض المعاينة والصوت تلك الطبقة وحدها",
 "editor_alinhar_base_tela": "محاذاة إلى أسفل الشاشة",
 "editor_alinhar_direita_tela": "محاذاة إلى يمين الشاشة",
 "editor_alinhar_esquerda_tela": "محاذاة إلى يسار الشاشة",
 "editor_alinhar_fins": "محاذاة النهايات", "editor_alinhar_inicios": "محاذاة البدايات",
 "editor_alinhar_topo_tela": "محاذاة إلى أعلى الشاشة",
 "editor_alta": "عالية", "editor_altura": "الارتفاع",
 "editor_aparar_empurra_camadas_seguintes_excluir_fecha": "القص يدفع الطبقات التالية؛ والحذف يسدّ الفراغ",
 "editor_aparar_fim_cabecote": "قص النهاية عند المؤشّر",
 "editor_aparar_inicio_cabecote": "قص البداية عند المؤشّر",
 "editor_aparar_projeto_cabecote": "قص المشروع عند المؤشّر",
 "editor_aparece_aqui_editor_fica_fora_video": "يظهر هنا في المحرّر ولا يدخل في الفيديو المُصدَّر",
 "editor_bloquear_camada": "قفل الطبقة",
 "editor_borra_direcao_movimento_obturador_nas_configuracoes": "يضبّب في اتجاه الحركة (الغالق في إعدادات المشروع)",
 "editor_borra_mexe_dentro_video_pelos_vetores": "يضبّب ما يتحرّك داخل الفيديو (من متجهات الحركة)",
 "editor_buscar_camadas": "ابحث في الطبقات…", "editor_camada": "طبقة",
 "editor_camada_ajuste": "طبقة ضبط", "editor_camada_bloqueada": "الطبقة مقفلة",
 "editor_camada_bloqueada_desbloqueie_editar": "الطبقة مقفلة: افتح القفل للتحرير",
 "editor_camadas_desfoque_movimento_so_borram_isto": "الطبقات ذات ضبابية الحركة لا تضبّب إلا عند تشغيل هذا",
 "editor_cancelar": "إلغاء", "editor_cancelar_selecao": "إلغاء التحديد",
 "editor_canto_suave_toque_ponto_alternar": "زاوية/ناعم: اضغط النقطة للتبديل",
 "editor_centralizar_horizontal": "توسيط أفقي",
 "editor_centralizar_vertical": "توسيط رأسي",
 "editor_colar_camada_cabecote": "لصق الطبقة عند المؤشّر",
 "editor_colar_efeitos": "لصق المؤثرات", "editor_colar_estilo": "لصق النمط",
 "editor_colar_keyframes_cabecote": "لصق الإطارات المفتاحية عند المؤشّر",
 "editor_compartilhar": "مشاركة", "editor_concluir": "تم",
 "editor_concluir_desenho": "إنهاء الرسم", "editor_converter_grupo": "تحويل إلى مجموعة",
 "editor_copiar_camada": "نسخ الطبقة", "editor_copiar_colar": "نسخ ولصق",
 "editor_copiar_efeitos": "نسخ المؤثرات", "editor_copiar_estilo": "نسخ النمط",
 "editor_copiar_keyframes_cabecote": "نسخ الإطارات المفتاحية من المؤشّر",
 "editor_cor": "اللون",
 "editor_cria_nulo_segue_ponto_ligue_outras": "ينشئ Null يتبع النقطة — اربط به طبقات أخرى",
 "editor_desagrupar": "فكّ التجميع", "editor_desbloquear": "فتح القفل",
 "editor_desbloquear_camada": "فتح قفل الطبقة", "editor_desenhar_pontos": "الرسم بالنقاط",
 "editor_desenhe_dedo_direto_palco_cada_traco": "ارسم بإصبعك مباشرة على المسرح. كل خط يصبح مسارًا يمكن تعديله وتحريكه.",
 "editor_desfazer": "تراجع", "editor_desfoque_movimento": "ضبابية الحركة",
 "editor_desfoque_movimento_composicao": "ضبابية حركة التركيب",
 "editor_desfoque_movimento_video": "ضبابية حركة الفيديو",
 "editor_desligar_som_segure_volume": "كتم الصوت · اضغط مطوّلًا لمستوى الصوت",
 "editor_detectar_batidas_camada_escolhida": "كشف الإيقاع من الطبقة المختارة",
 "editor_diagnostico_tela": "تشخيص على الشاشة",
 "editor_distribuir_horizontal_vaos_iguais": "توزيع أفقي (فراغات متساوية)",
 "editor_distribuir_vertical_vaos_iguais": "توزيع رأسي (فراغات متساوية)",
 "editor_dividir_cabecote": "تقسيم عند المؤشّر", "editor_duplicar": "تكرار",
 "editor_duplicar_camada": "تكرار الطبقة", "editor_duracao": "المدة",
 "editor_edicao": "التحرير", "editor_editando_grupo": "تحرير المجموعة",
 "editor_editar_grupo": "تحرير المجموعة",
 "editor_efeitos_desta_camada_valem_todas_baixo": "مؤثرات هذه الطبقة تنطبق على كل الطبقات أسفلها",
 "editor_elipse": "بيضاوي", "editor_else": " else ",
 "editor_entrar_grupo": "الدخول إلى المجموعة", "editor_enviar_tras": "إرسال إلى الخلف",
 "editor_escada_comeca_quando_cima_termina": "متدرّج: واحدة تبدأ حين تنتهي التي فوقها",
 "editor_escala": "المقياس", "editor_estabilizar_pelo_ponto": "تثبيت من النقطة",
 "editor_estilo_efeitos": "النمط والمؤثرات", "editor_estrela": "نجمة",
 "editor_etiqueta": "وسم", "editor_excluir_camada": "حذف الطبقة",
 "editor_excluir_selecao": "حذف التحديد", "editor_exportar": "تصدير",
 "editor_extrair_audio": "استخراج الصوت", "editor_fechar": "إغلاق",
 "editor_fechar_adicionar": "إغلاق الإضافة", "editor_formato": "الصيغة", "editor_foto": "صورة",
 "editor_fundo_composicao": "خلفية التركيب", "editor_galeria": "المعرض",
 "editor_grupo": "مجموعة", "editor_guia_nao_exporta": "دليل (لا يُصدَّر)",
 "editor_h_264_abre_qualquer_aparelho_rede": "H.264: يُفتح على أي جهاز وعلى الشبكات الاجتماعية.",
 "editor_hevc_arquivo_menor_mesma_qualidade_alguns": "HEVC: ملف أصغر بالجودة نفسها. بعض الأجهزة القديمة لا تشغّله.",
 "editor_importar_svg": "استيراد SVG", "editor_ir": "انتقال",
}

run({"en": EN, "es": ES, "ru": RU, "hi": HI, "id": ID, "ar": AR})
