# Lote 2 de traducoes (105 chaves).
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from i18n_translate import run

EN = {
 "editor_ir_proxima_marca": "Go to the next marker", "editor_ir_tempo": "Go to time",
 "editor_keyframe_anterior_segure_inicio": "Previous keyframe · hold for the start",
 "editor_keyframes": "Keyframes", "editor_largura": "Width",
 "editor_leve_cabecote_dentro_camadas": "Move the playhead into the layers",
 "editor_limpar_selecao": "Clear selection", "editor_mais": "More",
 "editor_mais_acoes_camada": "More layer actions",
 "editor_mais_linha_tempo": "More timeline options",
 "editor_mantenha_aurea_aberto_ate_terminar": "Keep Aurea open until it finishes.",
 "editor_mao_livre": "Freehand", "editor_mao_livre_desenhe_dedo": "Freehand: draw with your finger",
 "editor_marcar_ou_desmarcar_este_instante": "Mark (or unmark) this instant",
 "editor_marcas_ritmo": "Markers and beats",
 "editor_mesclagem_opacidade_efeitos_cores": "Blending, opacity, effects and colours",
 "editor_mostrar_camada": "Show layer",
 "editor_move_video_ponto_ficar_parado_tela": "Moves the video so the point stays still on screen",
 "editor_movimento": "Motion", "editor_musica_ou_som": "Music or sound",
 "editor_nao_aceita_movimento_corte_nem_edicao": "Takes no motion, trim or editing",
 "editor_nenhum": "None", "editor_nenhum_app_abre_video": "No app opens video",
 "editor_nenhuma_outra_camada_seguir_crie_nulo": "No other layer to track. Create a Null in Add › Object.",
 "editor_nome_camada": "Layer name", "editor_nome_ou_texto_camada": "Layer name or text",
 "editor_ocultar_camada": "Hide layer", "editor_outra_cor": "Other colour…",
 "editor_padrao": "Default", "editor_pausar": "Pause",
 "editor_personalizada": "Custom", "editor_plano_fundo": "Backdrop", "editor_poligono": "Polygon",
 "editor_previa": "Preview", "editor_projeto": "From the project", "editor_projeto_cbe9": "Project",
 "editor_projetos": "Projects",
 "editor_proximo_keyframe_segure_fim": "Next keyframe · hold for the end",
 "editor_quadro_atras_segure_inicio": "One frame back · hold for the start",
 "editor_quadro_frente_segure_fim": "One frame forward · hold for the end",
 "editor_quadros_segundo": "Frames per second",
 "editor_quadros_segundo_tempos_gpu_memoria_decodificador": "Frames per second, GPU timings, memory and the decoder",
 "editor_qualidade": "Quality", "editor_rastrear_ponto": "Track a point",
 "editor_rastreio": "Tracking", "editor_refazer": "Redo",
 "editor_remover_espacos_vazios": "Remove empty gaps",
 "editor_remover_toque_ponto_apagar": "Remove: tap the point to delete it",
 "editor_renomear": "Rename",
 "editor_repeticao_ligada_segure_desligar": "Repeat on · hold to turn off",
 "editor_reproducao_loop": "Loop playback", "editor_reproducao_previa": "Playback and preview",
 "editor_reproduzir": "Play", "editor_reproduzir_segure_repetir": "Play · hold to repeat",
 "editor_resolucao": "Resolution",
 "editor_resolucao_previa_segure_diagnostico": "Preview resolution · hold for diagnostics",
 "editor_retangulo": "Rectangle", "editor_rotacao": "Rotation",
 "editor_sair_tela_cheia": "Exit full screen", "editor_salvando": "Saving…",
 "editor_salvando_galeria": "Saving to the gallery…", "editor_sdr_bt_709": "SDR · BT.709",
 "editor_segundos_ou_mm_ss_ms": "seconds, or mm:ss.ms",
 "editor_selecionar_arraste_pontos_alcas": "Select: drag points and handles",
 "editor_selecionar_todas_camadas": "Select all layers",
 "editor_selecione_menos_duas_camadas": "Select at least two layers",
 "editor_solo": "Solo",
 "editor_som_desligado_toque_ligar_segure_volume": "Sound off · tap to turn on, hold for volume",
 "editor_som_vira_camada_propria_video_fica": "The sound becomes its own layer and the video goes silent",
 "editor_tamanho": "Size", "editor_tamanho_estimado": "Estimated size",
 "editor_tamanho_livre": "Free size", "editor_tela_cheia": "Full screen",
 "editor_tempo": "Time",
 "editor_timeline_magnetica_modo_edicao": "Magnetic timeline (Editing mode)",
 "editor_toque_num_objeto_tela_editar": "Tap an object on screen to edit it.",
 "editor_toque_trocar_90_180_270_360": "Tap to switch (90°, 180°, 270°, 360°): larger = longer trail",
 "editor_trazer_frente": "Bring forward", "editor_velocidade": "Speed",
 "editor_vetor_contorno_pontos_voce_arrasta_curva": "Vector = outline with points you drag, bend and animate.",
 "editor_video": "Video", "editor_video_pronto": "Video ready",
 "editor_vinculada_outra_camada_trocar": "Parented to another layer · change",
 "editor_vincular_escolhidas_camada": "Parent the selected ones to a layer",
 "editor_vincular_outra_camada": "Parent to another layer",
 "editor_volta_aceitar_movimento_edicao": "Takes motion and editing again",
 "editor_voltar_composicao_principal": "Back to the main composition",
 "editor_voltar_editor": "Back to the editor", "editor_voltar_tirar_selecao": "Back (clear the selection)",
 "effect_abra_projeto_aplicar_este_efeito": "Open a project to apply this effect.",
 "effect_adicionar_selecao": "Add to the selection",
 "effect_buscar_glitch_vhs_desfoque_cor": "Search: \"glitch\", \"vhs\", \"blur\", \"colour\"…",
 "effect_favoritos": "★ Favourites", "effect_nos_favoritos": "Add to favourites",
 "effect_recentes": "Recent", "effect_tirar_favoritos": "Remove from favourites",
 "effect_todos": "All",
 "home_ruanzitwo_ofruanzitwo_tiktok_ruanzitwo": "Ruanzitwo  ·  @ofruanzitwo  ·  TikTok @ruanzitwo",
 "home_ver_todos": "See all",
 "panel_1_caminho": "1 Path", "panel_1_recortar_pelo": "1. Cut by what",
 "panel_1_to": ", 1 to ", "panel_2_modo": "2 Mode",
 "panel_2_qual_camada_recorta": "2. Which layer cuts", "panel_2_to": ", 2 to",
}

ES = {
 "editor_ir_proxima_marca": "Ir a la próxima marca", "editor_ir_tempo": "Ir al tiempo",
 "editor_keyframe_anterior_segure_inicio": "Keyframe anterior · mantén para el inicio",
 "editor_keyframes": "Keyframes", "editor_largura": "Ancho",
 "editor_leve_cabecote_dentro_camadas": "Lleva el cabezal dentro de las capas",
 "editor_limpar_selecao": "Limpiar selección", "editor_mais": "Más",
 "editor_mais_acoes_camada": "Más acciones de la capa",
 "editor_mais_linha_tempo": "Más de la línea de tiempo",
 "editor_mantenha_aurea_aberto_ate_terminar": "Mantén Aurea abierto hasta que termine.",
 "editor_mao_livre": "Mano libre", "editor_mao_livre_desenhe_dedo": "Mano libre: dibuja con el dedo",
 "editor_marcar_ou_desmarcar_este_instante": "Marcar (o desmarcar) este instante",
 "editor_marcas_ritmo": "Marcas y ritmo",
 "editor_mesclagem_opacidade_efeitos_cores": "Mezcla, opacidad, efectos y colores",
 "editor_mostrar_camada": "Mostrar capa",
 "editor_move_video_ponto_ficar_parado_tela": "Mueve el vídeo para que el punto quede quieto en pantalla",
 "editor_movimento": "Movimiento", "editor_musica_ou_som": "Música o sonido",
 "editor_nao_aceita_movimento_corte_nem_edicao": "No acepta movimiento, corte ni edición",
 "editor_nenhum": "Ninguno", "editor_nenhum_app_abre_video": "Ninguna app abre vídeo",
 "editor_nenhuma_outra_camada_seguir_crie_nulo": "No hay otra capa que seguir. Crea un Nulo en Añadir › Objeto.",
 "editor_nome_camada": "Nombre de la capa", "editor_nome_ou_texto_camada": "Nombre o texto de la capa",
 "editor_ocultar_camada": "Ocultar capa", "editor_outra_cor": "Otro color…",
 "editor_padrao": "Predeterminado", "editor_pausar": "Pausar",
 "editor_personalizada": "Personalizada", "editor_plano_fundo": "Fondo", "editor_poligono": "Polígono",
 "editor_previa": "Vista previa", "editor_projeto": "Del proyecto", "editor_projeto_cbe9": "Proyecto",
 "editor_projetos": "Proyectos",
 "editor_proximo_keyframe_segure_fim": "Keyframe siguiente · mantén para el final",
 "editor_quadro_atras_segure_inicio": "Un fotograma atrás · mantén para el inicio",
 "editor_quadro_frente_segure_fim": "Un fotograma adelante · mantén para el final",
 "editor_quadros_segundo": "Fotogramas por segundo",
 "editor_quadros_segundo_tempos_gpu_memoria_decodificador": "Fotogramas por segundo, tiempos de GPU, memoria y el decodificador",
 "editor_qualidade": "Calidad", "editor_rastrear_ponto": "Rastrear un punto",
 "editor_rastreio": "Rastreo", "editor_refazer": "Rehacer",
 "editor_remover_espacos_vazios": "Quitar huecos vacíos",
 "editor_remover_toque_ponto_apagar": "Quitar: toca el punto para borrarlo",
 "editor_renomear": "Renombrar",
 "editor_repeticao_ligada_segure_desligar": "Repetición activada · mantén para apagar",
 "editor_reproducao_loop": "Reproducción en bucle", "editor_reproducao_previa": "Reproducción y vista previa",
 "editor_reproduzir": "Reproducir", "editor_reproduzir_segure_repetir": "Reproducir · mantén para repetir",
 "editor_resolucao": "Resolución",
 "editor_resolucao_previa_segure_diagnostico": "Resolución de la vista previa · mantén para el diagnóstico",
 "editor_retangulo": "Rectángulo", "editor_rotacao": "Rotación",
 "editor_sair_tela_cheia": "Salir de pantalla completa", "editor_salvando": "Guardando…",
 "editor_salvando_galeria": "Guardando en la galería…", "editor_sdr_bt_709": "SDR · BT.709",
 "editor_segundos_ou_mm_ss_ms": "segundos, o mm:ss.ms",
 "editor_selecionar_arraste_pontos_alcas": "Seleccionar: arrastra puntos y manejadores",
 "editor_selecionar_todas_camadas": "Seleccionar todas las capas",
 "editor_selecione_menos_duas_camadas": "Selecciona al menos dos capas",
 "editor_solo": "Solo",
 "editor_som_desligado_toque_ligar_segure_volume": "Sonido apagado · toca para encender, mantén para el volumen",
 "editor_som_vira_camada_propria_video_fica": "El sonido se vuelve una capa propia y el vídeo queda mudo",
 "editor_tamanho": "Tamaño", "editor_tamanho_estimado": "Tamaño estimado",
 "editor_tamanho_livre": "Tamaño libre", "editor_tela_cheia": "Pantalla completa",
 "editor_tempo": "Tiempo",
 "editor_timeline_magnetica_modo_edicao": "Línea de tiempo magnética (modo Edición)",
 "editor_toque_num_objeto_tela_editar": "Toca un objeto en pantalla para editarlo.",
 "editor_toque_trocar_90_180_270_360": "Toca para cambiar (90°, 180°, 270°, 360°): mayor = estela más larga",
 "editor_trazer_frente": "Traer al frente", "editor_velocidade": "Velocidad",
 "editor_vetor_contorno_pontos_voce_arrasta_curva": "Vector = contorno con puntos que arrastras, curvas y animas.",
 "editor_video": "Vídeo", "editor_video_pronto": "Vídeo listo",
 "editor_vinculada_outra_camada_trocar": "Vinculada a otra capa · cambiar",
 "editor_vincular_escolhidas_camada": "Vincular las elegidas a una capa",
 "editor_vincular_outra_camada": "Vincular a otra capa",
 "editor_volta_aceitar_movimento_edicao": "Vuelve a aceptar movimiento y edición",
 "editor_voltar_composicao_principal": "Volver a la composición principal",
 "editor_voltar_editor": "Volver al editor", "editor_voltar_tirar_selecao": "Volver (quitar la selección)",
 "effect_abra_projeto_aplicar_este_efeito": "Abre un proyecto para aplicar este efecto.",
 "effect_adicionar_selecao": "Añadir a la selección",
 "effect_buscar_glitch_vhs_desfoque_cor": "Buscar: \"glitch\", \"vhs\", \"desenfoque\", \"color\"…",
 "effect_favoritos": "★ Favoritos", "effect_nos_favoritos": "Añadir a favoritos",
 "effect_recentes": "Recientes", "effect_tirar_favoritos": "Quitar de favoritos",
 "effect_todos": "Todos",
 "home_ruanzitwo_ofruanzitwo_tiktok_ruanzitwo": "Ruanzitwo  ·  @ofruanzitwo  ·  TikTok @ruanzitwo",
 "home_ver_todos": "Ver todos",
 "panel_1_caminho": "1 Camino", "panel_1_recortar_pelo": "1. Recortar por qué",
 "panel_1_to": ", 1 to ", "panel_2_modo": "2 Modo",
 "panel_2_qual_camada_recorta": "2. Qué capa recorta", "panel_2_to": ", 2 to",
}

RU = {
 "editor_ir_proxima_marca": "К следующей метке", "editor_ir_tempo": "Перейти ко времени",
 "editor_keyframe_anterior_segure_inicio": "Предыдущий ключ · удерживайте для начала",
 "editor_keyframes": "Ключевые кадры", "editor_largura": "Ширина",
 "editor_leve_cabecote_dentro_camadas": "Заведите курсор внутрь слоёв",
 "editor_limpar_selecao": "Снять выделение", "editor_mais": "Ещё",
 "editor_mais_acoes_camada": "Другие действия со слоем",
 "editor_mais_linha_tempo": "Другие действия с таймлайном",
 "editor_mantenha_aurea_aberto_ate_terminar": "Не закрывайте Aurea до завершения.",
 "editor_mao_livre": "От руки", "editor_mao_livre_desenhe_dedo": "От руки: рисуйте пальцем",
 "editor_marcar_ou_desmarcar_este_instante": "Поставить (или снять) метку здесь",
 "editor_marcas_ritmo": "Метки и ритм",
 "editor_mesclagem_opacidade_efeitos_cores": "Смешивание, прозрачность, эффекты и цвета",
 "editor_mostrar_camada": "Показать слой",
 "editor_move_video_ponto_ficar_parado_tela": "Сдвигает видео так, чтобы точка стояла на месте",
 "editor_movimento": "Движение", "editor_musica_ou_som": "Музыка или звук",
 "editor_nao_aceita_movimento_corte_nem_edicao": "Не принимает движение, обрезку и монтаж",
 "editor_nenhum": "Нет", "editor_nenhum_app_abre_video": "Ни одно приложение не открывает видео",
 "editor_nenhuma_outra_camada_seguir_crie_nulo": "Нет другого слоя для слежения. Создайте Null в «Добавить › Объект».",
 "editor_nome_camada": "Имя слоя", "editor_nome_ou_texto_camada": "Имя или текст слоя",
 "editor_ocultar_camada": "Скрыть слой", "editor_outra_cor": "Другой цвет…",
 "editor_padrao": "По умолчанию", "editor_pausar": "Пауза",
 "editor_personalizada": "Своя", "editor_plano_fundo": "Фон", "editor_poligono": "Многоугольник",
 "editor_previa": "Просмотр", "editor_projeto": "Из проекта", "editor_projeto_cbe9": "Проект",
 "editor_projetos": "Проекты",
 "editor_proximo_keyframe_segure_fim": "Следующий ключ · удерживайте для конца",
 "editor_quadro_atras_segure_inicio": "На кадр назад · удерживайте для начала",
 "editor_quadro_frente_segure_fim": "На кадр вперёд · удерживайте для конца",
 "editor_quadros_segundo": "Кадров в секунду",
 "editor_quadros_segundo_tempos_gpu_memoria_decodificador": "Кадров в секунду, тайминги GPU, память и декодер",
 "editor_qualidade": "Качество", "editor_rastrear_ponto": "Отследить точку",
 "editor_rastreio": "Слежение", "editor_refazer": "Вернуть",
 "editor_remover_espacos_vazios": "Убрать пустые промежутки",
 "editor_remover_toque_ponto_apagar": "Удалить: коснитесь точки, чтобы стереть",
 "editor_renomear": "Переименовать",
 "editor_repeticao_ligada_segure_desligar": "Повтор включён · удерживайте, чтобы выключить",
 "editor_reproducao_loop": "Повтор воспроизведения", "editor_reproducao_previa": "Воспроизведение и просмотр",
 "editor_reproduzir": "Воспроизвести", "editor_reproduzir_segure_repetir": "Воспроизвести · удерживайте для повтора",
 "editor_resolucao": "Разрешение",
 "editor_resolucao_previa_segure_diagnostico": "Разрешение просмотра · удерживайте для диагностики",
 "editor_retangulo": "Прямоугольник", "editor_rotacao": "Поворот",
 "editor_sair_tela_cheia": "Выйти из полноэкранного режима", "editor_salvando": "Сохранение…",
 "editor_salvando_galeria": "Сохранение в галерею…", "editor_sdr_bt_709": "SDR · BT.709",
 "editor_segundos_ou_mm_ss_ms": "секунды, или мм:сс.мс",
 "editor_selecionar_arraste_pontos_alcas": "Выбор: тяните точки и маркеры",
 "editor_selecionar_todas_camadas": "Выбрать все слои",
 "editor_selecione_menos_duas_camadas": "Выберите хотя бы два слоя",
 "editor_solo": "Solo",
 "editor_som_desligado_toque_ligar_segure_volume": "Звук выключен · коснитесь для включения, удерживайте для громкости",
 "editor_som_vira_camada_propria_video_fica": "Звук становится отдельным слоем, а видео — беззвучным",
 "editor_tamanho": "Размер", "editor_tamanho_estimado": "Оценка размера",
 "editor_tamanho_livre": "Свободный размер", "editor_tela_cheia": "Полный экран",
 "editor_tempo": "Время",
 "editor_timeline_magnetica_modo_edicao": "Магнитный таймлайн (режим монтажа)",
 "editor_toque_num_objeto_tela_editar": "Коснитесь объекта на экране, чтобы редактировать.",
 "editor_toque_trocar_90_180_270_360": "Коснитесь для смены (90°, 180°, 270°, 360°): больше = длиннее след",
 "editor_trazer_frente": "На передний план", "editor_velocidade": "Скорость",
 "editor_vetor_contorno_pontos_voce_arrasta_curva": "Вектор = контур с точками, которые вы тянете, изгибаете и анимируете.",
 "editor_video": "Видео", "editor_video_pronto": "Видео готово",
 "editor_vinculada_outra_camada_trocar": "Привязана к другому слою · сменить",
 "editor_vincular_escolhidas_camada": "Привязать выбранные к слою",
 "editor_vincular_outra_camada": "Привязать к другому слою",
 "editor_volta_aceitar_movimento_edicao": "Снова принимает движение и монтаж",
 "editor_voltar_composicao_principal": "Назад к основной композиции",
 "editor_voltar_editor": "Назад в редактор", "editor_voltar_tirar_selecao": "Назад (снять выделение)",
 "effect_abra_projeto_aplicar_este_efeito": "Откройте проект, чтобы применить этот эффект.",
 "effect_adicionar_selecao": "Добавить к выделению",
 "effect_buscar_glitch_vhs_desfoque_cor": "Поиск: «glitch», «vhs», «размытие», «цвет»…",
 "effect_favoritos": "★ Избранное", "effect_nos_favoritos": "Добавить в избранное",
 "effect_recentes": "Недавние", "effect_tirar_favoritos": "Убрать из избранного",
 "effect_todos": "Все",
 "home_ruanzitwo_ofruanzitwo_tiktok_ruanzitwo": "Ruanzitwo  ·  @ofruanzitwo  ·  TikTok @ruanzitwo",
 "home_ver_todos": "Показать все",
 "panel_1_caminho": "1 Контур", "panel_1_recortar_pelo": "1. Чем обрезать",
 "panel_1_to": ", 1 to ", "panel_2_modo": "2 Режим",
 "panel_2_qual_camada_recorta": "2. Какой слой обрезает", "panel_2_to": ", 2 to",
}

HI = {
 "editor_ir_proxima_marca": "अगले मार्कर पर जाएँ", "editor_ir_tempo": "समय पर जाएँ",
 "editor_keyframe_anterior_segure_inicio": "पिछला कीफ़्रेम · शुरुआत के लिए दबाए रखें",
 "editor_keyframes": "कीफ़्रेम", "editor_largura": "चौड़ाई",
 "editor_leve_cabecote_dentro_camadas": "प्लेहेड को लेयर के अंदर ले जाएँ",
 "editor_limpar_selecao": "चयन साफ़ करें", "editor_mais": "और",
 "editor_mais_acoes_camada": "लेयर की और क्रियाएँ",
 "editor_mais_linha_tempo": "टाइमलाइन के और विकल्प",
 "editor_mantenha_aurea_aberto_ate_terminar": "पूरा होने तक Aurea खुला रखें।",
 "editor_mao_livre": "मुक्त हस्त", "editor_mao_livre_desenhe_dedo": "मुक्त हस्त: उँगली से बनाएँ",
 "editor_marcar_ou_desmarcar_este_instante": "इस क्षण को चिह्नित (या हटाएँ)",
 "editor_marcas_ritmo": "मार्कर और ताल",
 "editor_mesclagem_opacidade_efeitos_cores": "मिश्रण, अपारदर्शिता, इफ़ेक्ट और रंग",
 "editor_mostrar_camada": "लेयर दिखाएँ",
 "editor_move_video_ponto_ficar_parado_tela": "वीडियो को हिलाता है ताकि बिंदु स्क्रीन पर स्थिर रहे",
 "editor_movimento": "गति", "editor_musica_ou_som": "संगीत या ध्वनि",
 "editor_nao_aceita_movimento_corte_nem_edicao": "गति, कट या संपादन स्वीकार नहीं करता",
 "editor_nenhum": "कोई नहीं", "editor_nenhum_app_abre_video": "कोई ऐप वीडियो नहीं खोलता",
 "editor_nenhuma_outra_camada_seguir_crie_nulo": "पीछा करने के लिए और लेयर नहीं। जोड़ें › ऑब्जेक्ट में Null बनाएँ।",
 "editor_nome_camada": "लेयर का नाम", "editor_nome_ou_texto_camada": "लेयर का नाम या टेक्स्ट",
 "editor_ocultar_camada": "लेयर छिपाएँ", "editor_outra_cor": "दूसरा रंग…",
 "editor_padrao": "डिफ़ॉल्ट", "editor_pausar": "रोकें",
 "editor_personalizada": "कस्टम", "editor_plano_fundo": "पृष्ठभूमि", "editor_poligono": "बहुभुज",
 "editor_previa": "प्रीव्यू", "editor_projeto": "प्रोजेक्ट से", "editor_projeto_cbe9": "प्रोजेक्ट",
 "editor_projetos": "प्रोजेक्ट",
 "editor_proximo_keyframe_segure_fim": "अगला कीफ़्रेम · अंत के लिए दबाए रखें",
 "editor_quadro_atras_segure_inicio": "एक फ़्रेम पीछे · शुरुआत के लिए दबाए रखें",
 "editor_quadro_frente_segure_fim": "एक फ़्रेम आगे · अंत के लिए दबाए रखें",
 "editor_quadros_segundo": "प्रति सेकंड फ़्रेम",
 "editor_quadros_segundo_tempos_gpu_memoria_decodificador": "प्रति सेकंड फ़्रेम, GPU समय, मेमोरी और डिकोडर",
 "editor_qualidade": "गुणवत्ता", "editor_rastrear_ponto": "बिंदु ट्रैक करें",
 "editor_rastreio": "ट्रैकिंग", "editor_refazer": "दोबारा करें",
 "editor_remover_espacos_vazios": "ख़ाली जगह हटाएँ",
 "editor_remover_toque_ponto_apagar": "हटाएँ: मिटाने के लिए बिंदु दबाएँ",
 "editor_renomear": "नाम बदलें",
 "editor_repeticao_ligada_segure_desligar": "पुनरावृत्ति चालू · बंद करने के लिए दबाए रखें",
 "editor_reproducao_loop": "लूप में चलाएँ", "editor_reproducao_previa": "प्लेबैक और प्रीव्यू",
 "editor_reproduzir": "चलाएँ", "editor_reproduzir_segure_repetir": "चलाएँ · दोहराने के लिए दबाए रखें",
 "editor_resolucao": "रिज़ॉल्यूशन",
 "editor_resolucao_previa_segure_diagnostico": "प्रीव्यू रिज़ॉल्यूशन · निदान के लिए दबाए रखें",
 "editor_retangulo": "आयत", "editor_rotacao": "घुमाव",
 "editor_sair_tela_cheia": "फ़ुल स्क्रीन से बाहर", "editor_salvando": "सहेजा जा रहा है…",
 "editor_salvando_galeria": "गैलरी में सहेजा जा रहा है…", "editor_sdr_bt_709": "SDR · BT.709",
 "editor_segundos_ou_mm_ss_ms": "सेकंड, या mm:ss.ms",
 "editor_selecionar_arraste_pontos_alcas": "चुनें: बिंदु और हैंडल खींचें",
 "editor_selecionar_todas_camadas": "सभी लेयर चुनें",
 "editor_selecione_menos_duas_camadas": "कम से कम दो लेयर चुनें",
 "editor_solo": "Solo",
 "editor_som_desligado_toque_ligar_segure_volume": "आवाज़ बंद · चालू करने के लिए दबाएँ, वॉल्यूम के लिए दबाए रखें",
 "editor_som_vira_camada_propria_video_fica": "आवाज़ अपनी अलग लेयर बन जाती है और वीडियो चुप हो जाता है",
 "editor_tamanho": "आकार", "editor_tamanho_estimado": "अनुमानित आकार",
 "editor_tamanho_livre": "मुक्त आकार", "editor_tela_cheia": "फ़ुल स्क्रीन",
 "editor_tempo": "समय",
 "editor_timeline_magnetica_modo_edicao": "चुंबकीय टाइमलाइन (संपादन मोड)",
 "editor_toque_num_objeto_tela_editar": "संपादन के लिए स्क्रीन पर किसी ऑब्जेक्ट को दबाएँ।",
 "editor_toque_trocar_90_180_270_360": "बदलने के लिए दबाएँ (90°, 180°, 270°, 360°): बड़ा = लंबा पीछा",
 "editor_trazer_frente": "आगे लाएँ", "editor_velocidade": "गति",
 "editor_vetor_contorno_pontos_voce_arrasta_curva": "वेक्टर = बिंदुओं वाला किनारा जिसे आप खींचते, मोड़ते और एनिमेट करते हैं।",
 "editor_video": "वीडियो", "editor_video_pronto": "वीडियो तैयार",
 "editor_vinculada_outra_camada_trocar": "दूसरी लेयर से जुड़ी · बदलें",
 "editor_vincular_escolhidas_camada": "चुनी हुई को एक लेयर से जोड़ें",
 "editor_vincular_outra_camada": "दूसरी लेयर से जोड़ें",
 "editor_volta_aceitar_movimento_edicao": "फिर से गति और संपादन स्वीकार करता है",
 "editor_voltar_composicao_principal": "मुख्य कंपोज़िशन पर वापस",
 "editor_voltar_editor": "एडिटर पर वापस", "editor_voltar_tirar_selecao": "वापस (चयन हटाएँ)",
 "effect_abra_projeto_aplicar_este_efeito": "यह इफ़ेक्ट लगाने के लिए प्रोजेक्ट खोलें।",
 "effect_adicionar_selecao": "चयन में जोड़ें",
 "effect_buscar_glitch_vhs_desfoque_cor": "खोजें: \"glitch\", \"vhs\", \"ब्लर\", \"रंग\"…",
 "effect_favoritos": "★ पसंदीदा", "effect_nos_favoritos": "पसंदीदा में डालें",
 "effect_recentes": "हाल के", "effect_tirar_favoritos": "पसंदीदा से हटाएँ",
 "effect_todos": "सभी",
 "home_ruanzitwo_ofruanzitwo_tiktok_ruanzitwo": "Ruanzitwo  ·  @ofruanzitwo  ·  TikTok @ruanzitwo",
 "home_ver_todos": "सभी देखें",
 "panel_1_caminho": "1 पथ", "panel_1_recortar_pelo": "1. किससे काटें",
 "panel_1_to": ", 1 to ", "panel_2_modo": "2 मोड",
 "panel_2_qual_camada_recorta": "2. कौन-सी लेयर काटती है", "panel_2_to": ", 2 to",
}

ID = {
 "editor_ir_proxima_marca": "Ke penanda berikutnya", "editor_ir_tempo": "Ke waktu",
 "editor_keyframe_anterior_segure_inicio": "Keyframe sebelumnya · tahan untuk awal",
 "editor_keyframes": "Keyframe", "editor_largura": "Lebar",
 "editor_leve_cabecote_dentro_camadas": "Bawa kepala playback masuk ke lapisan",
 "editor_limpar_selecao": "Bersihkan pilihan", "editor_mais": "Lainnya",
 "editor_mais_acoes_camada": "Aksi lapisan lainnya",
 "editor_mais_linha_tempo": "Opsi timeline lainnya",
 "editor_mantenha_aurea_aberto_ate_terminar": "Biarkan Aurea terbuka sampai selesai.",
 "editor_mao_livre": "Bebas tangan", "editor_mao_livre_desenhe_dedo": "Bebas tangan: gambar dengan jari",
 "editor_marcar_ou_desmarcar_este_instante": "Tandai (atau lepas) momen ini",
 "editor_marcas_ritmo": "Penanda dan ketukan",
 "editor_mesclagem_opacidade_efeitos_cores": "Pencampuran, opasitas, efek, dan warna",
 "editor_mostrar_camada": "Tampilkan lapisan",
 "editor_move_video_ponto_ficar_parado_tela": "Menggeser video agar titiknya diam di layar",
 "editor_movimento": "Gerak", "editor_musica_ou_som": "Musik atau suara",
 "editor_nao_aceita_movimento_corte_nem_edicao": "Tidak menerima gerak, potong, atau penyuntingan",
 "editor_nenhum": "Tidak ada", "editor_nenhum_app_abre_video": "Tidak ada aplikasi yang membuka video",
 "editor_nenhuma_outra_camada_seguir_crie_nulo": "Tidak ada lapisan lain untuk diikuti. Buat Null di Tambah › Objek.",
 "editor_nome_camada": "Nama lapisan", "editor_nome_ou_texto_camada": "Nama atau teks lapisan",
 "editor_ocultar_camada": "Sembunyikan lapisan", "editor_outra_cor": "Warna lain…",
 "editor_padrao": "Bawaan", "editor_pausar": "Jeda",
 "editor_personalizada": "Khusus", "editor_plano_fundo": "Latar", "editor_poligono": "Poligon",
 "editor_previa": "Pratinjau", "editor_projeto": "Dari proyek", "editor_projeto_cbe9": "Proyek",
 "editor_projetos": "Proyek",
 "editor_proximo_keyframe_segure_fim": "Keyframe berikutnya · tahan untuk akhir",
 "editor_quadro_atras_segure_inicio": "Satu frame ke belakang · tahan untuk awal",
 "editor_quadro_frente_segure_fim": "Satu frame ke depan · tahan untuk akhir",
 "editor_quadros_segundo": "Frame per detik",
 "editor_quadros_segundo_tempos_gpu_memoria_decodificador": "Frame per detik, waktu GPU, memori, dan dekoder",
 "editor_qualidade": "Kualitas", "editor_rastrear_ponto": "Lacak sebuah titik",
 "editor_rastreio": "Pelacakan", "editor_refazer": "Ulangi",
 "editor_remover_espacos_vazios": "Hapus celah kosong",
 "editor_remover_toque_ponto_apagar": "Hapus: ketuk titik untuk menghapusnya",
 "editor_renomear": "Ganti nama",
 "editor_repeticao_ligada_segure_desligar": "Pengulangan menyala · tahan untuk mematikan",
 "editor_reproducao_loop": "Putar berulang", "editor_reproducao_previa": "Pemutaran dan pratinjau",
 "editor_reproduzir": "Putar", "editor_reproduzir_segure_repetir": "Putar · tahan untuk mengulang",
 "editor_resolucao": "Resolusi",
 "editor_resolucao_previa_segure_diagnostico": "Resolusi pratinjau · tahan untuk diagnostik",
 "editor_retangulo": "Persegi", "editor_rotacao": "Rotasi",
 "editor_sair_tela_cheia": "Keluar dari layar penuh", "editor_salvando": "Menyimpan…",
 "editor_salvando_galeria": "Menyimpan ke galeri…", "editor_sdr_bt_709": "SDR · BT.709",
 "editor_segundos_ou_mm_ss_ms": "detik, atau mm:ss.ms",
 "editor_selecionar_arraste_pontos_alcas": "Pilih: seret titik dan pegangan",
 "editor_selecionar_todas_camadas": "Pilih semua lapisan",
 "editor_selecione_menos_duas_camadas": "Pilih minimal dua lapisan",
 "editor_solo": "Solo",
 "editor_som_desligado_toque_ligar_segure_volume": "Suara mati · ketuk untuk menyalakan, tahan untuk volume",
 "editor_som_vira_camada_propria_video_fica": "Suara jadi lapisan sendiri dan videonya jadi bisu",
 "editor_tamanho": "Ukuran", "editor_tamanho_estimado": "Perkiraan ukuran",
 "editor_tamanho_livre": "Ukuran bebas", "editor_tela_cheia": "Layar penuh",
 "editor_tempo": "Waktu",
 "editor_timeline_magnetica_modo_edicao": "Timeline magnetis (mode Penyuntingan)",
 "editor_toque_num_objeto_tela_editar": "Ketuk objek di layar untuk mengeditnya.",
 "editor_toque_trocar_90_180_270_360": "Ketuk untuk berganti (90°, 180°, 270°, 360°): makin besar = jejak makin panjang",
 "editor_trazer_frente": "Bawa ke depan", "editor_velocidade": "Kecepatan",
 "editor_vetor_contorno_pontos_voce_arrasta_curva": "Vektor = garis luar dengan titik yang Anda seret, lengkungkan, dan animasikan.",
 "editor_video": "Video", "editor_video_pronto": "Video siap",
 "editor_vinculada_outra_camada_trocar": "Terpaut ke lapisan lain · ganti",
 "editor_vincular_escolhidas_camada": "Pautkan yang terpilih ke sebuah lapisan",
 "editor_vincular_outra_camada": "Pautkan ke lapisan lain",
 "editor_volta_aceitar_movimento_edicao": "Menerima gerak dan penyuntingan lagi",
 "editor_voltar_composicao_principal": "Kembali ke komposisi utama",
 "editor_voltar_editor": "Kembali ke editor", "editor_voltar_tirar_selecao": "Kembali (hapus pilihan)",
 "effect_abra_projeto_aplicar_este_efeito": "Buka proyek untuk menerapkan efek ini.",
 "effect_adicionar_selecao": "Tambahkan ke pilihan",
 "effect_buscar_glitch_vhs_desfoque_cor": "Cari: \"glitch\", \"vhs\", \"blur\", \"warna\"…",
 "effect_favoritos": "★ Favorit", "effect_nos_favoritos": "Tambahkan ke favorit",
 "effect_recentes": "Terbaru", "effect_tirar_favoritos": "Hapus dari favorit",
 "effect_todos": "Semua",
 "home_ruanzitwo_ofruanzitwo_tiktok_ruanzitwo": "Ruanzitwo  ·  @ofruanzitwo  ·  TikTok @ruanzitwo",
 "home_ver_todos": "Lihat semua",
 "panel_1_caminho": "1 Jalur", "panel_1_recortar_pelo": "1. Dipotong oleh apa",
 "panel_1_to": ", 1 to ", "panel_2_modo": "2 Mode",
 "panel_2_qual_camada_recorta": "2. Lapisan mana yang memotong", "panel_2_to": ", 2 to",
}

AR = {
 "editor_ir_proxima_marca": "إلى العلامة التالية", "editor_ir_tempo": "الانتقال إلى وقت",
 "editor_keyframe_anterior_segure_inicio": "الإطار المفتاحي السابق · اضغط مطوّلًا للبداية",
 "editor_keyframes": "الإطارات المفتاحية", "editor_largura": "العرض",
 "editor_leve_cabecote_dentro_camadas": "انقل المؤشّر إلى داخل الطبقات",
 "editor_limpar_selecao": "مسح التحديد", "editor_mais": "المزيد",
 "editor_mais_acoes_camada": "مزيد من إجراءات الطبقة",
 "editor_mais_linha_tempo": "المزيد من خيارات الخط الزمني",
 "editor_mantenha_aurea_aberto_ate_terminar": "أبقِ Aurea مفتوحًا حتى ينتهي.",
 "editor_mao_livre": "رسم حر", "editor_mao_livre_desenhe_dedo": "رسم حر: ارسم بإصبعك",
 "editor_marcar_ou_desmarcar_este_instante": "ضع (أو أزل) علامة عند هذه اللحظة",
 "editor_marcas_ritmo": "العلامات والإيقاع",
 "editor_mesclagem_opacidade_efeitos_cores": "الدمج والعتامة والمؤثرات والألوان",
 "editor_mostrar_camada": "إظهار الطبقة",
 "editor_move_video_ponto_ficar_parado_tela": "يحرّك الفيديو ليبقى النقطة ثابتة على الشاشة",
 "editor_movimento": "الحركة", "editor_musica_ou_som": "موسيقى أو صوت",
 "editor_nao_aceita_movimento_corte_nem_edicao": "لا يقبل الحركة ولا القصّ ولا التحرير",
 "editor_nenhum": "لا شيء", "editor_nenhum_app_abre_video": "لا يوجد تطبيق يفتح الفيديو",
 "editor_nenhuma_outra_camada_seguir_crie_nulo": "لا توجد طبقة أخرى للتتبع. أنشئ Null في إضافة › كائن.",
 "editor_nome_camada": "اسم الطبقة", "editor_nome_ou_texto_camada": "اسم الطبقة أو نصّها",
 "editor_ocultar_camada": "إخفاء الطبقة", "editor_outra_cor": "لون آخر…",
 "editor_padrao": "افتراضي", "editor_pausar": "إيقاف مؤقت",
 "editor_personalizada": "مخصّص", "editor_plano_fundo": "الخلفية", "editor_poligono": "مضلّع",
 "editor_previa": "معاينة", "editor_projeto": "من المشروع", "editor_projeto_cbe9": "مشروع",
 "editor_projetos": "المشاريع",
 "editor_proximo_keyframe_segure_fim": "الإطار المفتاحي التالي · اضغط مطوّلًا للنهاية",
 "editor_quadro_atras_segure_inicio": "إطار للخلف · اضغط مطوّلًا للبداية",
 "editor_quadro_frente_segure_fim": "إطار للأمام · اضغط مطوّلًا للنهاية",
 "editor_quadros_segundo": "إطار في الثانية",
 "editor_quadros_segundo_tempos_gpu_memoria_decodificador": "إطار في الثانية، أزمنة GPU، الذاكرة، ومفكّك الترميز",
 "editor_qualidade": "الجودة", "editor_rastrear_ponto": "تتبّع نقطة",
 "editor_rastreio": "التتبّع", "editor_refazer": "إعادة",
 "editor_remover_espacos_vazios": "إزالة الفراغات",
 "editor_remover_toque_ponto_apagar": "إزالة: اضغط النقطة لمحوها",
 "editor_renomear": "إعادة تسمية",
 "editor_repeticao_ligada_segure_desligar": "التكرار مفعّل · اضغط مطوّلًا للإيقاف",
 "editor_reproducao_loop": "تشغيل متكرّر", "editor_reproducao_previa": "التشغيل والمعاينة",
 "editor_reproduzir": "تشغيل", "editor_reproduzir_segure_repetir": "تشغيل · اضغط مطوّلًا للتكرار",
 "editor_resolucao": "الدقة",
 "editor_resolucao_previa_segure_diagnostico": "دقة المعاينة · اضغط مطوّلًا للتشخيص",
 "editor_retangulo": "مستطيل", "editor_rotacao": "الدوران",
 "editor_sair_tela_cheia": "الخروج من ملء الشاشة", "editor_salvando": "جارٍ الحفظ…",
 "editor_salvando_galeria": "جارٍ الحفظ في المعرض…", "editor_sdr_bt_709": "SDR · BT.709",
 "editor_segundos_ou_mm_ss_ms": "ثوانٍ، أو مم:ثث.مم",
 "editor_selecionar_arraste_pontos_alcas": "تحديد: اسحب النقاط والمقابض",
 "editor_selecionar_todas_camadas": "تحديد كل الطبقات",
 "editor_selecione_menos_duas_camadas": "حدّد طبقتين على الأقل",
 "editor_solo": "Solo",
 "editor_som_desligado_toque_ligar_segure_volume": "الصوت مكتوم · اضغط للتشغيل، اضغط مطوّلًا لمستوى الصوت",
 "editor_som_vira_camada_propria_video_fica": "يصبح الصوت طبقة مستقلة ويصمت الفيديو",
 "editor_tamanho": "الحجم", "editor_tamanho_estimado": "الحجم التقديري",
 "editor_tamanho_livre": "حجم حر", "editor_tela_cheia": "ملء الشاشة",
 "editor_tempo": "الزمن",
 "editor_timeline_magnetica_modo_edicao": "خط زمني مغناطيسي (وضع التحرير)",
 "editor_toque_num_objeto_tela_editar": "اضغط أي كائن على الشاشة لتحريره.",
 "editor_toque_trocar_90_180_270_360": "اضغط للتبديل (90°، 180°، 270°، 360°): الأكبر = أثر أطول",
 "editor_trazer_frente": "إحضار إلى الأمام", "editor_velocidade": "السرعة",
 "editor_vetor_contorno_pontos_voce_arrasta_curva": "المتجه = حدّ بنقاط تسحبها وتحنيها وتحريكها.",
 "editor_video": "فيديو", "editor_video_pronto": "الفيديو جاهز",
 "editor_vinculada_outra_camada_trocar": "مرتبطة بطبقة أخرى · تغيير",
 "editor_vincular_escolhidas_camada": "ربط المختارة بطبقة",
 "editor_vincular_outra_camada": "الربط بطبقة أخرى",
 "editor_volta_aceitar_movimento_edicao": "يعود لقبول الحركة والتحرير",
 "editor_voltar_composicao_principal": "العودة إلى التركيب الرئيسي",
 "editor_voltar_editor": "العودة إلى المحرّر", "editor_voltar_tirar_selecao": "رجوع (إزالة التحديد)",
 "effect_abra_projeto_aplicar_este_efeito": "افتح مشروعًا لتطبيق هذا المؤثر.",
 "effect_adicionar_selecao": "إضافة إلى التحديد",
 "effect_buscar_glitch_vhs_desfoque_cor": "ابحث: \"glitch\"، \"vhs\"، \"ضباب\"، \"لون\"…",
 "effect_favoritos": "★ المفضّلة", "effect_nos_favoritos": "إضافة إلى المفضّلة",
 "effect_recentes": "الأخيرة", "effect_tirar_favoritos": "إزالة من المفضّلة",
 "effect_todos": "الكل",
 "home_ruanzitwo_ofruanzitwo_tiktok_ruanzitwo": "Ruanzitwo  ·  @ofruanzitwo  ·  TikTok @ruanzitwo",
 "home_ver_todos": "عرض الكل",
 "panel_1_caminho": "1 مسار", "panel_1_recortar_pelo": "1. القصّ بماذا",
 "panel_1_to": ", 1 to ", "panel_2_modo": "2 الوضع",
 "panel_2_qual_camada_recorta": "2. أي طبقة تقصّ", "panel_2_to": ", 2 to",
}

run({"en": EN, "es": ES, "ru": RU, "hi": HI, "id": ID, "ar": AR})
