# Lote 3 de traducoes (105 chaves).
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from i18n_translate import run

EN = {
 "panel_3_borda": "3 Border", "panel_4_rastrear": "4 Track", "panel_aa": "Aa",
 "panel_aberta": " (open)", "panel_abertura": "Aperture", "panel_abrir_caminho": "Open path",
 "panel_abrir_efeitos_camada": "Open the layer's effects", "panel_acelerar": "Speed up",
 "panel_acelerar_desacelerar_tempo": "Speed up and slow down over time",
 "panel_acha_movimento_camera_video_roda_segundo": "Finds the camera motion in the video (runs in the background).",
 "panel_adicionar": "+ Add", "panel_adicionar_animacao": "+ Add animation",
 "panel_adicionar_efeito": "Add effect", "panel_adicionar_expressao": "Add expression",
 "panel_adicionar_mascara": "+ Add mask", "panel_adicionar_ponto": "Add point",
 "panel_ainda_nao_editavel_app": "Not editable in the app yet", "panel_ajustar": "Adjust",
 "panel_alinhamento": "Alignment", "panel_alta_qualidade": "High quality",
 "panel_alternar_deixa_furos": "Toggle (leaves gaps)", "panel_altura": "Height",
 "panel_altura_caixa": "Box height", "panel_altura_caixa_0cec": "box height",
 "panel_analisar_camera": "Analyse camera", "panel_analisar_novo": "Analyse again",
 "panel_analise_cancelada": "Analysis cancelled.", "panel_analise_guardada": " (analysis saved)",
 "panel_analise_projeto_nao_muda": "Stops the analysis; the project doesn't change.",
 "panel_anima_cada": "Animates each", "panel_animacao": "Animation",
 "panel_animador_texto": "text animator", "panel_apagar": "Delete",
 "panel_apagar_este_caminho": "Delete this path", "panel_apagar_mascara": "Delete mask",
 "panel_apagar_preset": "Delete preset", "panel_aparar_desenhar_so_trecho": "Trim (draw only a section)",
 "panel_aplicar": "Apply",
 "panel_aplicar_sem_texto_remove_expressao": "Applying with no text removes the expression.",
 "panel_aplicar_todos_segmentos": "Apply to all segments",
 "panel_arraste_alcas_palco_mudar_tamanho": "Drag the handles on the stage to change the size",
 "panel_arraste_pontos_palco_toque_num_ponto": "Drag the points on the stage; tap a point to see the curve handles.",
 "panel_arredondar_pontas": "Round the ends", "panel_avancado": "Advanced",
 "panel_borda": "Border", "panel_borra_camada_direcao_ela_move": "Blurs the layer along the direction it moves.",
 "panel_borra_mexe_dentro_video": "Blurs what moves inside the video.",
 "panel_buscar_fonte": "Search font", "panel_buscar_preset": "Search preset",
 "panel_cada_sozinho": "Each on its own", "panel_caixa": "Box",
 "panel_camada_escolhida_recorta_esta_some_tela": "The chosen layer cuts this one and it leaves the screen.",
 "panel_camera_3d": "3D camera",
 "panel_camera_so_gira_lugar_sem_profundidade": "The camera only rotates in place — no depth",
 "panel_caminho": "Path", "panel_cancelar": "Cancel", "panel_canto_suave": "Corner / Smooth",
 "panel_cantos": "Corners", "panel_cantos_arredondados": "Rounded corners",
 "panel_centro": "Centre", "panel_chanfrados": "Beveled",
 "panel_colar_curva": "Paste curve", "panel_colar_curva_e26b": "paste curve",
 "panel_colar_efeitos": "Paste effects",
 "panel_como_esta_mascara_combina_outras": "How this mask combines with the others",
 "panel_congelado_cabecote": "Frozen at the playhead", "panel_congelar": "Freeze",
 "panel_contorno": "Outline",
 "panel_contorno_esta_sem_cor_escolha_cor": "The outline has no colour: pick one above for it to appear.",
 "panel_contorno_texto": "text outline", "panel_converter_caminho_livre": "Convert to a free path",
 "panel_copiar_curva": "Copy curve", "panel_copiar_efeitos": "Copy effects",
 "panel_copias": "Copies", "panel_copias_cima": "Copies on top",
 "panel_copias_embaixo": "Copies below", "panel_cor": "Colour",
 "panel_cor_brilho_metalico_rugosidade_vem_arquivo": "Colour, metallic shine and roughness come from the model file (glTF, FBX).",
 "panel_cor_contorno": "Outline colour", "panel_cor_contorno_bb27": "outline colour",
 "panel_cor_contorno_texto": "text outline colour", "panel_cor_final": "End colour",
 "panel_cor_forma": "shape colour", "panel_cor_fundo_texto": "text background colour",
 "panel_cor_inicial": "Start colour", "panel_cor_meio": "+ middle colour",
 "panel_cor_meio_dd59": "− middle colour", "panel_cor_preenchimento": "Colour and fill",
 "panel_cor_solida": "Solid colour", "panel_cor_sombra_texto": "text shadow colour",
 "panel_cor_texto": "text colour", "panel_cor_texto_3d": "3D text colour",
 "panel_cria_camera_3d_animada_ponto_guia": "Creates the animated 3D camera and a guide point on the scene floor.",
 "panel_cria_ponto_guia_segue_objeto_ligue": "Creates a guide point that follows the object — parent texts and shapes to it.",
 "panel_criar_camera": "Create camera",
 "panel_crie_camada_vetorial_desenho_vetorial_servir": "Create a vector layer (Vector drawing) to serve as a guide.",
 "panel_crie_pelo_menos_2_keyframes_npara": "Create at least 2 keyframes\nto edit the curve.",
 "panel_curva": "Curve", "panel_curva_todos": "curve on all",
 "panel_degrade_redondo": "Round gradient", "panel_degrade_reto": "Straight gradient",
 "panel_depois_outro": "One after another", "panel_desacelerar": "Slow down",
 "panel_desce": "Down", "panel_desenhar_mao": "Draw by hand",
}

ES = {
 "panel_3_borda": "3 Borde", "panel_4_rastrear": "4 Rastrear", "panel_aa": "Aa",
 "panel_aberta": " (abierta)", "panel_abertura": "Apertura", "panel_abrir_caminho": "Abrir camino",
 "panel_abrir_efeitos_camada": "Abrir los efectos de la capa", "panel_acelerar": "Acelerar",
 "panel_acelerar_desacelerar_tempo": "Acelerar y desacelerar en el tiempo",
 "panel_acha_movimento_camera_video_roda_segundo": "Encuentra el movimiento de la cámara del vídeo (se ejecuta en segundo plano).",
 "panel_adicionar": "+ Añadir", "panel_adicionar_animacao": "+ Añadir animación",
 "panel_adicionar_efeito": "Añadir efecto", "panel_adicionar_expressao": "Añadir expresión",
 "panel_adicionar_mascara": "+ Añadir máscara", "panel_adicionar_ponto": "Añadir punto",
 "panel_ainda_nao_editavel_app": "Aún no editable en la app", "panel_ajustar": "Ajustar",
 "panel_alinhamento": "Alineación", "panel_alta_qualidade": "Alta calidad",
 "panel_alternar_deixa_furos": "Alternar (deja huecos)", "panel_altura": "Altura",
 "panel_altura_caixa": "Altura de la caja", "panel_altura_caixa_0cec": "altura de la caja",
 "panel_analisar_camera": "Analizar cámara", "panel_analisar_novo": "Analizar de nuevo",
 "panel_analise_cancelada": "Análisis cancelado.", "panel_analise_guardada": " (análisis guardado)",
 "panel_analise_projeto_nao_muda": "Detiene el análisis; el proyecto no cambia.",
 "panel_anima_cada": "Anima cada", "panel_animacao": "Animación",
 "panel_animador_texto": "animador de texto", "panel_apagar": "Borrar",
 "panel_apagar_este_caminho": "Borrar este camino", "panel_apagar_mascara": "Borrar máscara",
 "panel_apagar_preset": "Borrar preset", "panel_aparar_desenhar_so_trecho": "Recortar (dibujar solo un tramo)",
 "panel_aplicar": "Aplicar",
 "panel_aplicar_sem_texto_remove_expressao": "Aplicar sin texto quita la expresión.",
 "panel_aplicar_todos_segmentos": "Aplicar en todos los segmentos",
 "panel_arraste_alcas_palco_mudar_tamanho": "Arrastra los manejadores en el escenario para cambiar el tamaño",
 "panel_arraste_pontos_palco_toque_num_ponto": "Arrastra los puntos en el escenario; toca un punto para ver los manejadores de curva.",
 "panel_arredondar_pontas": "Redondear las puntas", "panel_avancado": "Avanzado",
 "panel_borda": "Borde", "panel_borra_camada_direcao_ela_move": "Desenfoca la capa en la dirección en que se mueve.",
 "panel_borra_mexe_dentro_video": "Desenfoca lo que se mueve dentro del vídeo.",
 "panel_buscar_fonte": "Buscar fuente", "panel_buscar_preset": "Buscar preset",
 "panel_cada_sozinho": "Cada uno solo", "panel_caixa": "Caja",
 "panel_camada_escolhida_recorta_esta_some_tela": "La capa elegida recorta esta y desaparece de la pantalla.",
 "panel_camera_3d": "Cámara 3D",
 "panel_camera_so_gira_lugar_sem_profundidade": "La cámara solo gira en el sitio — sin profundidad",
 "panel_caminho": "Camino", "panel_cancelar": "Cancelar", "panel_canto_suave": "Esquina / Suave",
 "panel_cantos": "Esquinas", "panel_cantos_arredondados": "Esquinas redondeadas",
 "panel_centro": "Centro", "panel_chanfrados": "Biselados",
 "panel_colar_curva": "Pegar curva", "panel_colar_curva_e26b": "pegar curva",
 "panel_colar_efeitos": "Pegar efectos",
 "panel_como_esta_mascara_combina_outras": "Cómo se combina esta máscara con las demás",
 "panel_congelado_cabecote": "Congelado en el cabezal", "panel_congelar": "Congelar",
 "panel_contorno": "Contorno",
 "panel_contorno_esta_sem_cor_escolha_cor": "El contorno no tiene color: elige uno arriba para que aparezca.",
 "panel_contorno_texto": "contorno del texto", "panel_converter_caminho_livre": "Convertir en camino libre",
 "panel_copiar_curva": "Copiar curva", "panel_copiar_efeitos": "Copiar efectos",
 "panel_copias": "Copias", "panel_copias_cima": "Copias por encima",
 "panel_copias_embaixo": "Copias debajo", "panel_cor": "Color",
 "panel_cor_brilho_metalico_rugosidade_vem_arquivo": "El color, el brillo metálico y la rugosidad vienen del archivo del modelo (glTF, FBX).",
 "panel_cor_contorno": "Color del contorno", "panel_cor_contorno_bb27": "color del contorno",
 "panel_cor_contorno_texto": "color del contorno del texto", "panel_cor_final": "Color final",
 "panel_cor_forma": "color de la forma", "panel_cor_fundo_texto": "color del fondo del texto",
 "panel_cor_inicial": "Color inicial", "panel_cor_meio": "+ color del medio",
 "panel_cor_meio_dd59": "− color del medio", "panel_cor_preenchimento": "Color y relleno",
 "panel_cor_solida": "Color sólido", "panel_cor_sombra_texto": "color de la sombra del texto",
 "panel_cor_texto": "color del texto", "panel_cor_texto_3d": "color del texto 3D",
 "panel_cria_camera_3d_animada_ponto_guia": "Crea la cámara 3D animada y un punto guía en el suelo de la escena.",
 "panel_cria_ponto_guia_segue_objeto_ligue": "Crea un punto guía que sigue al objeto — vincula textos y formas a él.",
 "panel_criar_camera": "Crear cámara",
 "panel_crie_camada_vetorial_desenho_vetorial_servir": "Crea una capa vectorial (Dibujo vectorial) para servir de guía.",
 "panel_crie_pelo_menos_2_keyframes_npara": "Crea al menos 2 keyframes\npara editar la curva.",
 "panel_curva": "Curva", "panel_curva_todos": "curva en todos",
 "panel_degrade_redondo": "Degradado redondo", "panel_degrade_reto": "Degradado recto",
 "panel_depois_outro": "Uno tras otro", "panel_desacelerar": "Desacelerar",
 "panel_desce": "Baja", "panel_desenhar_mao": "Dibujar a mano",
}

RU = {
 "panel_3_borda": "3 Рамка", "panel_4_rastrear": "4 Слежение", "panel_aa": "Aa",
 "panel_aberta": " (открыта)", "panel_abertura": "Диафрагма", "panel_abrir_caminho": "Открыть контур",
 "panel_abrir_efeitos_camada": "Открыть эффекты слоя", "panel_acelerar": "Ускорить",
 "panel_acelerar_desacelerar_tempo": "Ускорение и замедление во времени",
 "panel_acha_movimento_camera_video_roda_segundo": "Находит движение камеры в видео (работает в фоне).",
 "panel_adicionar": "+ Добавить", "panel_adicionar_animacao": "+ Добавить анимацию",
 "panel_adicionar_efeito": "Добавить эффект", "panel_adicionar_expressao": "Добавить выражение",
 "panel_adicionar_mascara": "+ Добавить маску", "panel_adicionar_ponto": "Добавить точку",
 "panel_ainda_nao_editavel_app": "Пока не редактируется в приложении", "panel_ajustar": "Настроить",
 "panel_alinhamento": "Выравнивание", "panel_alta_qualidade": "Высокое качество",
 "panel_alternar_deixa_furos": "Переключить (оставляет пропуски)", "panel_altura": "Высота",
 "panel_altura_caixa": "Высота блока", "panel_altura_caixa_0cec": "высота блока",
 "panel_analisar_camera": "Анализировать камеру", "panel_analisar_novo": "Анализировать снова",
 "panel_analise_cancelada": "Анализ отменён.", "panel_analise_guardada": " (анализ сохранён)",
 "panel_analise_projeto_nao_muda": "Останавливает анализ; проект не меняется.",
 "panel_anima_cada": "Анимирует каждый", "panel_animacao": "Анимация",
 "panel_animador_texto": "аниматор текста", "panel_apagar": "Стереть",
 "panel_apagar_este_caminho": "Стереть этот контур", "panel_apagar_mascara": "Стереть маску",
 "panel_apagar_preset": "Стереть пресет", "panel_aparar_desenhar_so_trecho": "Обрезать (нарисовать только участок)",
 "panel_aplicar": "Применить",
 "panel_aplicar_sem_texto_remove_expressao": "Применение без текста убирает выражение.",
 "panel_aplicar_todos_segmentos": "Применить ко всем сегментам",
 "panel_arraste_alcas_palco_mudar_tamanho": "Тяните маркеры на сцене, чтобы изменить размер",
 "panel_arraste_pontos_palco_toque_num_ponto": "Тяните точки на сцене; коснитесь точки, чтобы увидеть маркеры кривой.",
 "panel_arredondar_pontas": "Скруглить концы", "panel_avancado": "Дополнительно",
 "panel_borda": "Рамка", "panel_borra_camada_direcao_ela_move": "Размывает слой по направлению его движения.",
 "panel_borra_mexe_dentro_video": "Размывает то, что движется внутри видео.",
 "panel_buscar_fonte": "Найти шрифт", "panel_buscar_preset": "Найти пресет",
 "panel_cada_sozinho": "Каждый отдельно", "panel_caixa": "Блок",
 "panel_camada_escolhida_recorta_esta_some_tela": "Выбранный слой обрезает этот, и он уходит с экрана.",
 "panel_camera_3d": "3D-камера",
 "panel_camera_so_gira_lugar_sem_profundidade": "Камера только вращается на месте — без глубины",
 "panel_caminho": "Контур", "panel_cancelar": "Отмена", "panel_canto_suave": "Угол / Сглаженный",
 "panel_cantos": "Углы", "panel_cantos_arredondados": "Скруглённые углы",
 "panel_centro": "Центр", "panel_chanfrados": "Скошенные",
 "panel_colar_curva": "Вставить кривую", "panel_colar_curva_e26b": "вставить кривую",
 "panel_colar_efeitos": "Вставить эффекты",
 "panel_como_esta_mascara_combina_outras": "Как эта маска сочетается с остальными",
 "panel_congelado_cabecote": "Заморожен по курсору", "panel_congelar": "Заморозить",
 "panel_contorno": "Обводка",
 "panel_contorno_esta_sem_cor_escolha_cor": "У обводки нет цвета: выберите цвет выше, чтобы она появилась.",
 "panel_contorno_texto": "обводка текста", "panel_converter_caminho_livre": "Преобразовать в свободный контур",
 "panel_copiar_curva": "Копировать кривую", "panel_copiar_efeitos": "Копировать эффекты",
 "panel_copias": "Копии", "panel_copias_cima": "Копии сверху",
 "panel_copias_embaixo": "Копии снизу", "panel_cor": "Цвет",
 "panel_cor_brilho_metalico_rugosidade_vem_arquivo": "Цвет, металлический блеск и шероховатость берутся из файла модели (glTF, FBX).",
 "panel_cor_contorno": "Цвет обводки", "panel_cor_contorno_bb27": "цвет обводки",
 "panel_cor_contorno_texto": "цвет обводки текста", "panel_cor_final": "Конечный цвет",
 "panel_cor_forma": "цвет фигуры", "panel_cor_fundo_texto": "цвет фона текста",
 "panel_cor_inicial": "Начальный цвет", "panel_cor_meio": "+ цвет середины",
 "panel_cor_meio_dd59": "− цвет середины", "panel_cor_preenchimento": "Цвет и заливка",
 "panel_cor_solida": "Сплошной цвет", "panel_cor_sombra_texto": "цвет тени текста",
 "panel_cor_texto": "цвет текста", "panel_cor_texto_3d": "цвет 3D-текста",
 "panel_cria_camera_3d_animada_ponto_guia": "Создаёт анимированную 3D-камеру и направляющую точку на полу сцены.",
 "panel_cria_ponto_guia_segue_objeto_ligue": "Создаёт направляющую точку, следящую за объектом — привяжите к ней тексты и фигуры.",
 "panel_criar_camera": "Создать камеру",
 "panel_crie_camada_vetorial_desenho_vetorial_servir": "Создайте векторный слой (Векторный рисунок), чтобы он служил направляющей.",
 "panel_crie_pelo_menos_2_keyframes_npara": "Создайте хотя бы 2 ключа,\nчтобы редактировать кривую.",
 "panel_curva": "Кривая", "panel_curva_todos": "кривая на всех",
 "panel_degrade_redondo": "Круглый градиент", "panel_degrade_reto": "Прямой градиент",
 "panel_depois_outro": "Один за другим", "panel_desacelerar": "Замедлить",
 "panel_desce": "Вниз", "panel_desenhar_mao": "Рисовать от руки",
}

HI = {
 "panel_3_borda": "3 किनारा", "panel_4_rastrear": "4 ट्रैक", "panel_aa": "Aa",
 "panel_aberta": " (खुला)", "panel_abertura": "एपर्चर", "panel_abrir_caminho": "पथ खोलें",
 "panel_abrir_efeitos_camada": "लेयर के इफ़ेक्ट खोलें", "panel_acelerar": "तेज़ करें",
 "panel_acelerar_desacelerar_tempo": "समय के साथ तेज़ और धीमा",
 "panel_acha_movimento_camera_video_roda_segundo": "वीडियो में कैमरे की गति खोजता है (पृष्ठभूमि में चलता है)।",
 "panel_adicionar": "+ जोड़ें", "panel_adicionar_animacao": "+ एनिमेशन जोड़ें",
 "panel_adicionar_efeito": "इफ़ेक्ट जोड़ें", "panel_adicionar_expressao": "एक्सप्रेशन जोड़ें",
 "panel_adicionar_mascara": "+ मास्क जोड़ें", "panel_adicionar_ponto": "बिंदु जोड़ें",
 "panel_ainda_nao_editavel_app": "ऐप में अभी संपादन योग्य नहीं", "panel_ajustar": "समायोजित करें",
 "panel_alinhamento": "संरेखण", "panel_alta_qualidade": "उच्च गुणवत्ता",
 "panel_alternar_deixa_furos": "टॉगल (अंतराल छोड़ता है)", "panel_altura": "ऊँचाई",
 "panel_altura_caixa": "बॉक्स की ऊँचाई", "panel_altura_caixa_0cec": "बॉक्स की ऊँचाई",
 "panel_analisar_camera": "कैमरा विश्लेषण", "panel_analisar_novo": "फिर से विश्लेषण",
 "panel_analise_cancelada": "विश्लेषण रद्द हुआ।", "panel_analise_guardada": " (विश्लेषण सहेजा गया)",
 "panel_analise_projeto_nao_muda": "विश्लेषण रोकता है; प्रोजेक्ट नहीं बदलता।",
 "panel_anima_cada": "हर एक को एनिमेट करें", "panel_animacao": "एनिमेशन",
 "panel_animador_texto": "टेक्स्ट एनिमेटर", "panel_apagar": "मिटाएँ",
 "panel_apagar_este_caminho": "यह पथ मिटाएँ", "panel_apagar_mascara": "मास्क मिटाएँ",
 "panel_apagar_preset": "प्रीसेट मिटाएँ", "panel_aparar_desenhar_so_trecho": "ट्रिम (केवल एक हिस्सा बनाएँ)",
 "panel_aplicar": "लागू करें",
 "panel_aplicar_sem_texto_remove_expressao": "बिना टेक्स्ट लागू करने पर एक्सप्रेशन हट जाता है।",
 "panel_aplicar_todos_segmentos": "सभी सेगमेंट पर लागू करें",
 "panel_arraste_alcas_palco_mudar_tamanho": "आकार बदलने के लिए स्टेज पर हैंडल खींचें",
 "panel_arraste_pontos_palco_toque_num_ponto": "स्टेज पर बिंदु खींचें; कर्व हैंडल देखने के लिए बिंदु दबाएँ।",
 "panel_arredondar_pontas": "सिरे गोल करें", "panel_avancado": "विस्तृत",
 "panel_borda": "किनारा", "panel_borra_camada_direcao_ela_move": "लेयर को उसकी गति की दिशा में धुंधला करता है।",
 "panel_borra_mexe_dentro_video": "वीडियो के अंदर जो हिलता है उसे धुंधला करता है।",
 "panel_buscar_fonte": "फ़ॉन्ट खोजें", "panel_buscar_preset": "प्रीसेट खोजें",
 "panel_cada_sozinho": "हर एक अलग", "panel_caixa": "बॉक्स",
 "panel_camada_escolhida_recorta_esta_some_tela": "चुनी हुई लेयर इसे काटती है और यह स्क्रीन से हट जाती है।",
 "panel_camera_3d": "3D कैमरा",
 "panel_camera_so_gira_lugar_sem_profundidade": "कैमरा सिर्फ़ अपनी जगह घूमता है — गहराई नहीं",
 "panel_caminho": "पथ", "panel_cancelar": "रद्द करें", "panel_canto_suave": "कोना / सौम्य",
 "panel_cantos": "कोने", "panel_cantos_arredondados": "गोल कोने",
 "panel_centro": "केंद्र", "panel_chanfrados": "तिरछे",
 "panel_colar_curva": "कर्व चिपकाएँ", "panel_colar_curva_e26b": "कर्व चिपकाएँ",
 "panel_colar_efeitos": "इफ़ेक्ट चिपकाएँ",
 "panel_como_esta_mascara_combina_outras": "यह मास्क बाक़ी के साथ कैसे मिलता है",
 "panel_congelado_cabecote": "प्लेहेड पर जमा हुआ", "panel_congelar": "जमाएँ",
 "panel_contorno": "रूपरेखा",
 "panel_contorno_esta_sem_cor_escolha_cor": "रूपरेखा का रंग नहीं है: दिखाने के लिए ऊपर से रंग चुनें।",
 "panel_contorno_texto": "टेक्स्ट की रूपरेखा", "panel_converter_caminho_livre": "मुक्त पथ में बदलें",
 "panel_copiar_curva": "कर्व कॉपी करें", "panel_copiar_efeitos": "इफ़ेक्ट कॉपी करें",
 "panel_copias": "प्रतियाँ", "panel_copias_cima": "प्रतियाँ ऊपर",
 "panel_copias_embaixo": "प्रतियाँ नीचे", "panel_cor": "रंग",
 "panel_cor_brilho_metalico_rugosidade_vem_arquivo": "रंग, धात्विक चमक और खुरदरापन मॉडल फ़ाइल (glTF, FBX) से आते हैं।",
 "panel_cor_contorno": "रूपरेखा का रंग", "panel_cor_contorno_bb27": "रूपरेखा का रंग",
 "panel_cor_contorno_texto": "टेक्स्ट की रूपरेखा का रंग", "panel_cor_final": "अंतिम रंग",
 "panel_cor_forma": "आकृति का रंग", "panel_cor_fundo_texto": "टेक्स्ट की पृष्ठभूमि का रंग",
 "panel_cor_inicial": "शुरुआती रंग", "panel_cor_meio": "+ बीच का रंग",
 "panel_cor_meio_dd59": "− बीच का रंग", "panel_cor_preenchimento": "रंग और भरण",
 "panel_cor_solida": "ठोस रंग", "panel_cor_sombra_texto": "टेक्स्ट की छाया का रंग",
 "panel_cor_texto": "टेक्स्ट का रंग", "panel_cor_texto_3d": "3D टेक्स्ट का रंग",
 "panel_cria_camera_3d_animada_ponto_guia": "एनिमेटेड 3D कैमरा और सीन के फ़र्श पर एक गाइड बिंदु बनाता है।",
 "panel_cria_ponto_guia_segue_objeto_ligue": "ऑब्जेक्ट का पीछा करने वाला गाइड बिंदु बनाता है — टेक्स्ट और आकृतियाँ उससे जोड़ें।",
 "panel_criar_camera": "कैमरा बनाएँ",
 "panel_crie_camada_vetorial_desenho_vetorial_servir": "गाइड के तौर पर वेक्टर लेयर (वेक्टर ड्रॉइंग) बनाएँ।",
 "panel_crie_pelo_menos_2_keyframes_npara": "कर्व संपादित करने के लिए\nकम से कम 2 कीफ़्रेम बनाएँ।",
 "panel_curva": "कर्व", "panel_curva_todos": "सभी पर कर्व",
 "panel_degrade_redondo": "गोल ग्रेडिएंट", "panel_degrade_reto": "सीधा ग्रेडिएंट",
 "panel_depois_outro": "एक के बाद एक", "panel_desacelerar": "धीमा करें",
 "panel_desce": "नीचे", "panel_desenhar_mao": "हाथ से बनाएँ",
}

ID = {
 "panel_3_borda": "3 Tepi", "panel_4_rastrear": "4 Lacak", "panel_aa": "Aa",
 "panel_aberta": " (terbuka)", "panel_abertura": "Bukaan", "panel_abrir_caminho": "Buka jalur",
 "panel_abrir_efeitos_camada": "Buka efek lapisan", "panel_acelerar": "Percepat",
 "panel_acelerar_desacelerar_tempo": "Percepat dan perlambat seiring waktu",
 "panel_acha_movimento_camera_video_roda_segundo": "Menemukan gerak kamera di video (berjalan di latar belakang).",
 "panel_adicionar": "+ Tambah", "panel_adicionar_animacao": "+ Tambah animasi",
 "panel_adicionar_efeito": "Tambah efek", "panel_adicionar_expressao": "Tambah ekspresi",
 "panel_adicionar_mascara": "+ Tambah masker", "panel_adicionar_ponto": "Tambah titik",
 "panel_ainda_nao_editavel_app": "Belum bisa diedit di aplikasi", "panel_ajustar": "Sesuaikan",
 "panel_alinhamento": "Perataan", "panel_alta_qualidade": "Kualitas tinggi",
 "panel_alternar_deixa_furos": "Beralih (meninggalkan celah)", "panel_altura": "Tinggi",
 "panel_altura_caixa": "Tinggi kotak", "panel_altura_caixa_0cec": "tinggi kotak",
 "panel_analisar_camera": "Analisis kamera", "panel_analisar_novo": "Analisis lagi",
 "panel_analise_cancelada": "Analisis dibatalkan.", "panel_analise_guardada": " (analisis tersimpan)",
 "panel_analise_projeto_nao_muda": "Menghentikan analisis; proyek tidak berubah.",
 "panel_anima_cada": "Animasikan tiap", "panel_animacao": "Animasi",
 "panel_animador_texto": "penganimasi teks", "panel_apagar": "Hapus",
 "panel_apagar_este_caminho": "Hapus jalur ini", "panel_apagar_mascara": "Hapus masker",
 "panel_apagar_preset": "Hapus preset", "panel_aparar_desenhar_so_trecho": "Pangkas (gambar hanya sepotong)",
 "panel_aplicar": "Terapkan",
 "panel_aplicar_sem_texto_remove_expressao": "Menerapkan tanpa teks menghapus ekspresinya.",
 "panel_aplicar_todos_segmentos": "Terapkan ke semua segmen",
 "panel_arraste_alcas_palco_mudar_tamanho": "Seret pegangan di panggung untuk mengubah ukuran",
 "panel_arraste_pontos_palco_toque_num_ponto": "Seret titik di panggung; ketuk titik untuk melihat pegangan kurva.",
 "panel_arredondar_pontas": "Bulatkan ujung", "panel_avancado": "Lanjutan",
 "panel_borda": "Tepi", "panel_borra_camada_direcao_ela_move": "Mengaburkan lapisan searah geraknya.",
 "panel_borra_mexe_dentro_video": "Mengaburkan yang bergerak di dalam video.",
 "panel_buscar_fonte": "Cari font", "panel_buscar_preset": "Cari preset",
 "panel_cada_sozinho": "Masing-masing sendiri", "panel_caixa": "Kotak",
 "panel_camada_escolhida_recorta_esta_some_tela": "Lapisan terpilih memotong yang ini dan ia hilang dari layar.",
 "panel_camera_3d": "Kamera 3D",
 "panel_camera_so_gira_lugar_sem_profundidade": "Kamera hanya berputar di tempat — tanpa kedalaman",
 "panel_caminho": "Jalur", "panel_cancelar": "Batal", "panel_canto_suave": "Sudut / Halus",
 "panel_cantos": "Sudut", "panel_cantos_arredondados": "Sudut membulat",
 "panel_centro": "Tengah", "panel_chanfrados": "Berpahat",
 "panel_colar_curva": "Tempel kurva", "panel_colar_curva_e26b": "tempel kurva",
 "panel_colar_efeitos": "Tempel efek",
 "panel_como_esta_mascara_combina_outras": "Bagaimana masker ini bergabung dengan yang lain",
 "panel_congelado_cabecote": "Dibekukan di kepala playback", "panel_congelar": "Bekukan",
 "panel_contorno": "Garis luar",
 "panel_contorno_esta_sem_cor_escolha_cor": "Garis luarnya belum berwarna: pilih warna di atas agar muncul.",
 "panel_contorno_texto": "garis luar teks", "panel_converter_caminho_livre": "Ubah jadi jalur bebas",
 "panel_copiar_curva": "Salin kurva", "panel_copiar_efeitos": "Salin efek",
 "panel_copias": "Salinan", "panel_copias_cima": "Salinan di atas",
 "panel_copias_embaixo": "Salinan di bawah", "panel_cor": "Warna",
 "panel_cor_brilho_metalico_rugosidade_vem_arquivo": "Warna, kilau logam, dan kekasaran berasal dari berkas model (glTF, FBX).",
 "panel_cor_contorno": "Warna garis luar", "panel_cor_contorno_bb27": "warna garis luar",
 "panel_cor_contorno_texto": "warna garis luar teks", "panel_cor_final": "Warna akhir",
 "panel_cor_forma": "warna bentuk", "panel_cor_fundo_texto": "warna latar teks",
 "panel_cor_inicial": "Warna awal", "panel_cor_meio": "+ warna tengah",
 "panel_cor_meio_dd59": "− warna tengah", "panel_cor_preenchimento": "Warna dan isian",
 "panel_cor_solida": "Warna padat", "panel_cor_sombra_texto": "warna bayangan teks",
 "panel_cor_texto": "warna teks", "panel_cor_texto_3d": "warna teks 3D",
 "panel_cria_camera_3d_animada_ponto_guia": "Membuat kamera 3D beranimasi dan titik panduan di lantai panggung.",
 "panel_cria_ponto_guia_segue_objeto_ligue": "Membuat titik panduan yang mengikuti objek — pautkan teks dan bentuk ke sana.",
 "panel_criar_camera": "Buat kamera",
 "panel_crie_camada_vetorial_desenho_vetorial_servir": "Buat lapisan vektor (Gambar vektor) untuk jadi panduan.",
 "panel_crie_pelo_menos_2_keyframes_npara": "Buat minimal 2 keyframe\nuntuk mengedit kurvanya.",
 "panel_curva": "Kurva", "panel_curva_todos": "kurva di semua",
 "panel_degrade_redondo": "Gradien bulat", "panel_degrade_reto": "Gradien lurus",
 "panel_depois_outro": "Satu demi satu", "panel_desacelerar": "Perlambat",
 "panel_desce": "Turun", "panel_desenhar_mao": "Gambar dengan tangan",
}

AR = {
 "panel_3_borda": "3 الحدود", "panel_4_rastrear": "4 التتبّع", "panel_aa": "Aa",
 "panel_aberta": " (مفتوحة)", "panel_abertura": "فتحة العدسة", "panel_abrir_caminho": "فتح المسار",
 "panel_abrir_efeitos_camada": "فتح مؤثرات الطبقة", "panel_acelerar": "تسريع",
 "panel_acelerar_desacelerar_tempo": "تسريع وتبطيء عبر الزمن",
 "panel_acha_movimento_camera_video_roda_segundo": "يجد حركة الكاميرا في الفيديو (يعمل في الخلفية).",
 "panel_adicionar": "+ إضافة", "panel_adicionar_animacao": "+ إضافة تحريك",
 "panel_adicionar_efeito": "إضافة مؤثر", "panel_adicionar_expressao": "إضافة تعبير",
 "panel_adicionar_mascara": "+ إضافة قناع", "panel_adicionar_ponto": "إضافة نقطة",
 "panel_ainda_nao_editavel_app": "غير قابل للتحرير في التطبيق بعد", "panel_ajustar": "ضبط",
 "panel_alinhamento": "المحاذاة", "panel_alta_qualidade": "جودة عالية",
 "panel_alternar_deixa_furos": "تبديل (يترك فراغات)", "panel_altura": "الارتفاع",
 "panel_altura_caixa": "ارتفاع الصندوق", "panel_altura_caixa_0cec": "ارتفاع الصندوق",
 "panel_analisar_camera": "تحليل الكاميرا", "panel_analisar_novo": "تحليل من جديد",
 "panel_analise_cancelada": "أُلغي التحليل.", "panel_analise_guardada": " (التحليل محفوظ)",
 "panel_analise_projeto_nao_muda": "يوقف التحليل؛ والمشروع لا يتغيّر.",
 "panel_anima_cada": "يحرّك كل", "panel_animacao": "التحريك",
 "panel_animador_texto": "محرّك النص", "panel_apagar": "محو",
 "panel_apagar_este_caminho": "محو هذا المسار", "panel_apagar_mascara": "محو القناع",
 "panel_apagar_preset": "محو الإعداد", "panel_aparar_desenhar_so_trecho": "قصّ (ارسم مقطعًا فقط)",
 "panel_aplicar": "تطبيق",
 "panel_aplicar_sem_texto_remove_expressao": "التطبيق بلا نص يحذف التعبير.",
 "panel_aplicar_todos_segmentos": "تطبيق على كل المقاطع",
 "panel_arraste_alcas_palco_mudar_tamanho": "اسحب المقابض على المسرح لتغيير الحجم",
 "panel_arraste_pontos_palco_toque_num_ponto": "اسحب النقاط على المسرح؛ اضغط نقطة لرؤية مقابض الانحناء.",
 "panel_arredondar_pontas": "تدوير الأطراف", "panel_avancado": "متقدّم",
 "panel_borda": "الحدود", "panel_borra_camada_direcao_ela_move": "يضبّب الطبقة في اتجاه حركتها.",
 "panel_borra_mexe_dentro_video": "يضبّب ما يتحرّك داخل الفيديو.",
 "panel_buscar_fonte": "ابحث عن خط", "panel_buscar_preset": "ابحث عن إعداد",
 "panel_cada_sozinho": "كل واحد وحده", "panel_caixa": "صندوق",
 "panel_camada_escolhida_recorta_esta_some_tela": "الطبقة المختارة تقصّ هذه وتختفي من الشاشة.",
 "panel_camera_3d": "كاميرا 3D",
 "panel_camera_so_gira_lugar_sem_profundidade": "الكاميرا تدور في مكانها فقط — بلا عمق",
 "panel_caminho": "مسار", "panel_cancelar": "إلغاء", "panel_canto_suave": "زاوية / ناعم",
 "panel_cantos": "الزوايا", "panel_cantos_arredondados": "زوايا مستديرة",
 "panel_centro": "المركز", "panel_chanfrados": "مشطوفة",
 "panel_colar_curva": "لصق المنحنى", "panel_colar_curva_e26b": "لصق المنحنى",
 "panel_colar_efeitos": "لصق المؤثرات",
 "panel_como_esta_mascara_combina_outras": "كيف يتحد هذا القناع مع البقية",
 "panel_congelado_cabecote": "مجمّد عند المؤشّر", "panel_congelar": "تجميد",
 "panel_contorno": "الإطار",
 "panel_contorno_esta_sem_cor_escolha_cor": "الإطار بلا لون: اختر لونًا بالأعلى ليظهر.",
 "panel_contorno_texto": "إطار النص", "panel_converter_caminho_livre": "تحويل إلى مسار حر",
 "panel_copiar_curva": "نسخ المنحنى", "panel_copiar_efeitos": "نسخ المؤثرات",
 "panel_copias": "النسخ", "panel_copias_cima": "النسخ فوق",
 "panel_copias_embaixo": "النسخ أسفل", "panel_cor": "اللون",
 "panel_cor_brilho_metalico_rugosidade_vem_arquivo": "اللون واللمعان المعدني والخشونة تأتي من ملف المجسّم (glTF، FBX).",
 "panel_cor_contorno": "لون الإطار", "panel_cor_contorno_bb27": "لون الإطار",
 "panel_cor_contorno_texto": "لون إطار النص", "panel_cor_final": "اللون النهائي",
 "panel_cor_forma": "لون الشكل", "panel_cor_fundo_texto": "لون خلفية النص",
 "panel_cor_inicial": "اللون الأولي", "panel_cor_meio": "+ لون الوسط",
 "panel_cor_meio_dd59": "− لون الوسط", "panel_cor_preenchimento": "اللون والتعبئة",
 "panel_cor_solida": "لون صلب", "panel_cor_sombra_texto": "لون ظل النص",
 "panel_cor_texto": "لون النص", "panel_cor_texto_3d": "لون النص 3D",
 "panel_cria_camera_3d_animada_ponto_guia": "ينشئ كاميرا 3D متحرّكة ونقطة إرشاد على أرض المشهد.",
 "panel_cria_ponto_guia_segue_objeto_ligue": "ينشئ نقطة إرشاد تتبع الكائن — اربط بها النصوص والأشكال.",
 "panel_criar_camera": "إنشاء كاميرا",
 "panel_crie_camada_vetorial_desenho_vetorial_servir": "أنشئ طبقة متجهة (رسم متجه) لتكون دليلًا.",
 "panel_crie_pelo_menos_2_keyframes_npara": "أنشئ إطارين مفتاحيين على الأقل\nلتحرير المنحنى.",
 "panel_curva": "المنحنى", "panel_curva_todos": "المنحنى على الكل",
 "panel_degrade_redondo": "تدرّج دائري", "panel_degrade_reto": "تدرّج مستقيم",
 "panel_depois_outro": "واحدًا بعد الآخر", "panel_desacelerar": "تبطيء",
 "panel_desce": "ينزل", "panel_desenhar_mao": "الرسم باليد",
}

run({"en": EN, "es": ES, "ru": RU, "hi": HI, "id": ID, "ar": AR})
