# Lote 4 de traducoes (105 chaves).
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from i18n_translate import run

EN = {
 "panel_desfoque": "Blur",
 "panel_desfoque_brilho_cor_outros_efeitos_aplicados": "Blur, brightness, colour and the other effects applied to this vector.",
 "panel_desfoque_movimento": "Motion blur", "panel_desfoque_movimento_video": "Video motion blur",
 "panel_desfoque_sombra": "shadow blur", "panel_desligada": "Off",
 "panel_desligada_propriedade_usa_keyframes": "Off: the property uses the keyframes.",
 "panel_desligar_efeito": "Turn the effect off", "panel_desligar_efeitos": "turn off effects",
 "panel_desligar_todos": "Turn all off",
 "panel_deslize_ajustar_profundidade_toque_z_voltar": "Slide to adjust depth · tap Z to go back to X/Y",
 "panel_deslize_mover_camada": "Slide to move the layer",
 "panel_deslize_mover_toque_z_profundidade": "Slide to move · tap Z for depth",
 "panel_deslize_ponto_giro_botao_centro_devolve": "Slide the pivot point · the Centre button resets it",
 "panel_deslocamento": "Offset", "panel_deslocar_tracos": "Offset strokes",
 "panel_deslocar_trecho": "Offset section", "panel_diferenca": "Difference",
 "panel_digite_texto": "Type the text", "panel_direcao": "Direction", "panel_direita": "Right",
 "panel_distancia_x": "Distance X", "panel_distancia_y": "Distance Y",
 "panel_duracao_cada": "Duration of each", "panel_durar_ate_fim_camada": "Last until the end of the layer",
 "panel_easing_curve": "Easing curve",
 "panel_editando_pontos_palco_toque_concluir_palco": "Editing points on the stage. Tap Done (on the stage) when you finish.",
 "panel_editar_curva_propriedade": "Edit the property curve",
 "panel_editar_expressao": "Edit expression", "panel_editar_forma": "Edit shape",
 "panel_efeito_removido": "Effect removed", "panel_efeitos": "Effects",
 "panel_efeitos_camada": "Layer effects", "panel_elipse": "Ellipse",
 "panel_elipse_meio_camada_pronta_ajustar": "An ellipse in the middle of the layer, ready to adjust.",
 "panel_encolher_caber": "Shrink to fit", "panel_entrada_suave": "Soft in",
 "panel_entrada_suave_1fd1": "soft in", "panel_equilibrado": "Balanced", "panel_escala": "Scale",
 "panel_escolha_camada_abaixo": "Pick the layer below",
 "panel_escolha_camada_vetorial": "Pick a vector layer.",
 "panel_escolha_estilo_ou_animacao": "Choose a style and/or animation",
 "panel_escolha_ferramenta_toque_palco_editar_pontos": "Pick a tool and tap the stage to edit the points.",
 "panel_escolha_forma_editar_silhueta": "Pick a shape to edit the silhouette.",
 "panel_escolha_mascara_acima_editar_palco": "Pick a mask above to edit it on the stage.",
 "panel_escolhe": "Chooses", "panel_esconder_x_y_z_3d": "Hide X/Y/Z (3D)",
 "panel_escreva_expressao_ou_toque_num_atalho": "Write an expression or tap a shortcut.",
 "panel_espaco": "Space", "panel_espessura": "Thickness", "panel_esquerda": "Left",
 "panel_esquerda_direita": "Left and right",
 "panel_esta_camada_ainda_nao_tem_grupos": "This layer has no groups yet. Add a path above.",
 "panel_esta_camada_nao_tem_audio": "This layer has no audio.",
 "panel_esta_camada_vetorial_edite_caminhos_painel": "This layer is a vector: edit the paths in the Vector panel.",
 "panel_esta_curva_igual_nos_dois_sentidos": "This curve is the same in both directions",
 "panel_estabilizar_pelo_ponto": "Stabilise from the point",
 "panel_este_efeito_nao_tem_ajustes": "This effect has no settings.",
 "panel_este_efeito_saiu_aurea_nao_desenha": "This effect left Aurea and no longer draws anything. It was kept here for you to decide — the rest of the layer is intact.",
 "panel_este_efeito_saiu_catalogo_ele_nao": "This effect left the catalogue. It no longer draws; delete it with ⋯.",
 "panel_este_trecho_quadro_parado_apare_bordas": "This section is a freeze frame. Trim the edges on the timeline to change how long it stays on screen.",
 "panel_este_video_nao_tem_trilha_som": "This video has no audio track.",
 "panel_estilo": "Style", "panel_estudio_neutro": "Neutral studio",
 "panel_excluir_sobreposicao": "Delete overlay", "panel_expandir": "Expand",
 "panel_expressao": "Expression", "panel_expressao_3c65": "Expression…",
 "panel_extrair_audio_camada": "Extract the audio to a layer",
 "panel_faiscas": "Sparks", "panel_favoritar": "Favourite", "panel_fechar": "Close",
 "panel_fechar_caminho": "Close path",
 "panel_ferramentas_pontos_transformam_forma_pronta_caminho": "The point tools turn the ready shape into a free path.",
 "panel_fim": "End", "panel_fonte": "Font", "panel_forma_animada": "Animated shape",
 "panel_forma_anterior": "Previous shape", "panel_fundo": "Background",
 "panel_gerar_legendas": "Generate captions", "panel_girar_3d_x_y": "Rotate in 3D (X and Y)",
 "panel_giro": "Spin", "panel_gravidade": "Gravity", "panel_grupo_visivel": "Group visible",
 "panel_guarda_curva_keyframe_escolhido": "Saves the curve of the chosen keyframe.",
 "panel_guarda_efeitos_camada_keyframes": "Saves the layer's effects together with the keyframes.",
 "panel_guarda_estilo_ou_animacao_texto": "Saves the text style and/or animation.",
 "panel_guarda_keyframes_movimento_camada": "Saves the layer's motion keyframes.",
 "panel_guarda_opcoes_atuais_legenda": "Saves the current caption options.",
 "panel_idioma_fala": "Speech language", "panel_imagem_ambiente": "Environment image ✓",
 "panel_importar": "Import", "panel_importar_legenda_srt": "Import captions (.srt)",
 "panel_inicio": "Start",
 "panel_inicio_camada_fica_lugar_fim_acompanha": "The layer start stays put; the end follows the new speed.",
 "panel_intensidade": "Strength", "panel_intensidade_camada_ajuste": "Adjustment layer strength",
 "panel_intensidade_desfoque": "Blur strength", "panel_intensidade_desfoque_eef9": "blur strength",
 "panel_intensidade_vale_todas_camadas_desfoque_neste": "The strength applies to every blurred layer in this project.",
 "panel_intersecao": "Intersect", "panel_inverter_curva": "invert curve",
 "panel_inverter_direcao_caminho": "Reverse the path direction",
 "panel_inverter_mostrar_lado_fora": "Invert (show the outside)",
}

ES = {
 "panel_desfoque": "Desenfoque",
 "panel_desfoque_brilho_cor_outros_efeitos_aplicados": "Desenfoque, brillo, color y los demás efectos aplicados a este vector.",
 "panel_desfoque_movimento": "Desenfoque de movimiento", "panel_desfoque_movimento_video": "Desenfoque del movimiento del vídeo",
 "panel_desfoque_sombra": "desenfoque de la sombra", "panel_desligada": "Apagada",
 "panel_desligada_propriedade_usa_keyframes": "Apagada: la propiedad usa los keyframes.",
 "panel_desligar_efeito": "Apagar efecto", "panel_desligar_efeitos": "apagar efectos",
 "panel_desligar_todos": "Apagar todos",
 "panel_deslize_ajustar_profundidade_toque_z_voltar": "Desliza para ajustar la profundidad · toca Z para volver a X/Y",
 "panel_deslize_mover_camada": "Desliza para mover la capa",
 "panel_deslize_mover_toque_z_profundidade": "Desliza para mover · toca Z para la profundidad",
 "panel_deslize_ponto_giro_botao_centro_devolve": "Desliza el punto de giro · el botón Centro lo devuelve a cero",
 "panel_deslocamento": "Desplazamiento", "panel_deslocar_tracos": "Desplazar trazos",
 "panel_deslocar_trecho": "Desplazar tramo", "panel_diferenca": "Diferencia",
 "panel_digite_texto": "Escribe el texto", "panel_direcao": "Dirección", "panel_direita": "Derecha",
 "panel_distancia_x": "Distancia X", "panel_distancia_y": "Distancia Y",
 "panel_duracao_cada": "Duración de cada una", "panel_durar_ate_fim_camada": "Dura hasta el final de la capa",
 "panel_easing_curve": "Easing curve",
 "panel_editando_pontos_palco_toque_concluir_palco": "Editando puntos en el escenario. Toca Listo (en el escenario) al terminar.",
 "panel_editar_curva_propriedade": "Editar la curva de la propiedad",
 "panel_editar_expressao": "Editar expresión", "panel_editar_forma": "Editar forma",
 "panel_efeito_removido": "Efecto quitado", "panel_efeitos": "Efectos",
 "panel_efeitos_camada": "Efectos de la capa", "panel_elipse": "Elipse",
 "panel_elipse_meio_camada_pronta_ajustar": "Una elipse en medio de la capa, lista para ajustar.",
 "panel_encolher_caber": "Encoger para que quepa", "panel_entrada_suave": "Entrada suave",
 "panel_entrada_suave_1fd1": "entrada suave", "panel_equilibrado": "Equilibrado", "panel_escala": "Escala",
 "panel_escolha_camada_abaixo": "Elige la capa de abajo",
 "panel_escolha_camada_vetorial": "Elige una capa vectorial.",
 "panel_escolha_estilo_ou_animacao": "Elige estilo y/o animación",
 "panel_escolha_ferramenta_toque_palco_editar_pontos": "Elige una herramienta y toca el escenario para editar los puntos.",
 "panel_escolha_forma_editar_silhueta": "Elige una forma para editar la silueta.",
 "panel_escolha_mascara_acima_editar_palco": "Elige una máscara arriba para editarla en el escenario.",
 "panel_escolhe": "Elige", "panel_esconder_x_y_z_3d": "Ocultar X/Y/Z (3D)",
 "panel_escreva_expressao_ou_toque_num_atalho": "Escribe una expresión o toca un atajo.",
 "panel_espaco": "Espacio", "panel_espessura": "Grosor", "panel_esquerda": "Izquierda",
 "panel_esquerda_direita": "Izquierda y derecha",
 "panel_esta_camada_ainda_nao_tem_grupos": "Esta capa aún no tiene grupos. Añade un camino arriba.",
 "panel_esta_camada_nao_tem_audio": "Esta capa no tiene audio.",
 "panel_esta_camada_vetorial_edite_caminhos_painel": "Esta capa es vectorial: edita los caminos en el panel Vector.",
 "panel_esta_curva_igual_nos_dois_sentidos": "Esta curva es igual en los dos sentidos",
 "panel_estabilizar_pelo_ponto": "Estabilizar por el punto",
 "panel_este_efeito_nao_tem_ajustes": "Este efecto no tiene ajustes.",
 "panel_este_efeito_saiu_aurea_nao_desenha": "Este efecto salió de Aurea y ya no dibuja nada. Quedó guardado aquí para que decidas — el resto de la capa está intacto.",
 "panel_este_efeito_saiu_catalogo_ele_nao": "Este efecto salió del catálogo. Ya no dibuja; bórralo con ⋯.",
 "panel_este_trecho_quadro_parado_apare_bordas": "Este tramo es un fotograma congelado. Recorta los bordes en la línea de tiempo para cambiar cuánto tiempo queda en pantalla.",
 "panel_este_video_nao_tem_trilha_som": "Este vídeo no tiene pista de audio.",
 "panel_estilo": "Estilo", "panel_estudio_neutro": "Estudio neutro",
 "panel_excluir_sobreposicao": "Eliminar superposición", "panel_expandir": "Expandir",
 "panel_expressao": "Expresión", "panel_expressao_3c65": "Expresión…",
 "panel_extrair_audio_camada": "Extraer el audio a una capa",
 "panel_faiscas": "Chispas", "panel_favoritar": "Favorito", "panel_fechar": "Cerrar",
 "panel_fechar_caminho": "Cerrar camino",
 "panel_ferramentas_pontos_transformam_forma_pronta_caminho": "Las herramientas de puntos convierten la forma lista en camino libre.",
 "panel_fim": "Final", "panel_fonte": "Fuente", "panel_forma_animada": "Forma animada",
 "panel_forma_anterior": "Forma anterior", "panel_fundo": "Fondo",
 "panel_gerar_legendas": "Generar subtítulos", "panel_girar_3d_x_y": "Girar en 3D (X e Y)",
 "panel_giro": "Giro", "panel_gravidade": "Gravedad", "panel_grupo_visivel": "Grupo visible",
 "panel_guarda_curva_keyframe_escolhido": "Guarda la curva del keyframe elegido.",
 "panel_guarda_efeitos_camada_keyframes": "Guarda los efectos de la capa con los keyframes.",
 "panel_guarda_estilo_ou_animacao_texto": "Guarda el estilo y/o la animación del texto.",
 "panel_guarda_keyframes_movimento_camada": "Guarda los keyframes de movimiento de la capa.",
 "panel_guarda_opcoes_atuais_legenda": "Guarda las opciones actuales del subtítulo.",
 "panel_idioma_fala": "Idioma del habla", "panel_imagem_ambiente": "Imagen de entorno ✓",
 "panel_importar": "Importar", "panel_importar_legenda_srt": "Importar subtítulos (.srt)",
 "panel_inicio": "Inicio",
 "panel_inicio_camada_fica_lugar_fim_acompanha": "El inicio de la capa se queda; el final acompaña la nueva velocidad.",
 "panel_intensidade": "Intensidad", "panel_intensidade_camada_ajuste": "Intensidad de la capa de ajuste",
 "panel_intensidade_desfoque": "Intensidad del desenfoque", "panel_intensidade_desfoque_eef9": "intensidad del desenfoque",
 "panel_intensidade_vale_todas_camadas_desfoque_neste": "La intensidad vale para todas las capas con desenfoque en este proyecto.",
 "panel_intersecao": "Intersección", "panel_inverter_curva": "invertir curva",
 "panel_inverter_direcao_caminho": "Invertir la dirección del camino",
 "panel_inverter_mostrar_lado_fora": "Invertir (mostrar el lado de fuera)",
}

RU = {
 "panel_desfoque": "Размытие",
 "panel_desfoque_brilho_cor_outros_efeitos_aplicados": "Размытие, яркость, цвет и остальные эффекты, применённые к этому вектору.",
 "panel_desfoque_movimento": "Размытие движения", "panel_desfoque_movimento_video": "Размытие движения видео",
 "panel_desfoque_sombra": "размытие тени", "panel_desligada": "Выключена",
 "panel_desligada_propriedade_usa_keyframes": "Выключена: свойство использует ключевые кадры.",
 "panel_desligar_efeito": "Выключить эффект", "panel_desligar_efeitos": "выключить эффекты",
 "panel_desligar_todos": "Выключить все",
 "panel_deslize_ajustar_profundidade_toque_z_voltar": "Сдвиньте, чтобы настроить глубину · коснитесь Z, чтобы вернуться к X/Y",
 "panel_deslize_mover_camada": "Сдвиньте, чтобы переместить слой",
 "panel_deslize_mover_toque_z_profundidade": "Сдвиньте для перемещения · коснитесь Z для глубины",
 "panel_deslize_ponto_giro_botao_centro_devolve": "Сдвиньте точку вращения · кнопка «Центр» возвращает ноль",
 "panel_deslocamento": "Смещение", "panel_deslocar_tracos": "Сместить штрихи",
 "panel_deslocar_trecho": "Сместить участок", "panel_diferenca": "Разница",
 "panel_digite_texto": "Введите текст", "panel_direcao": "Направление", "panel_direita": "Вправо",
 "panel_distancia_x": "Расстояние X", "panel_distancia_y": "Расстояние Y",
 "panel_duracao_cada": "Длительность каждого", "panel_durar_ate_fim_camada": "Длится до конца слоя",
 "panel_easing_curve": "Кривая плавности",
 "panel_editando_pontos_palco_toque_concluir_palco": "Редактирование точек на сцене. Коснитесь «Готово» (на сцене), когда закончите.",
 "panel_editar_curva_propriedade": "Редактировать кривую свойства",
 "panel_editar_expressao": "Редактировать выражение", "panel_editar_forma": "Редактировать фигуру",
 "panel_efeito_removido": "Эффект удалён", "panel_efeitos": "Эффекты",
 "panel_efeitos_camada": "Эффекты слоя", "panel_elipse": "Эллипс",
 "panel_elipse_meio_camada_pronta_ajustar": "Эллипс в середине слоя, готовый к настройке.",
 "panel_encolher_caber": "Уменьшить, чтобы поместилось", "panel_entrada_suave": "Мягкий вход",
 "panel_entrada_suave_1fd1": "мягкий вход", "panel_equilibrado": "Сбалансированный", "panel_escala": "Масштаб",
 "panel_escolha_camada_abaixo": "Выберите слой ниже",
 "panel_escolha_camada_vetorial": "Выберите векторный слой.",
 "panel_escolha_estilo_ou_animacao": "Выберите стиль и/или анимацию",
 "panel_escolha_ferramenta_toque_palco_editar_pontos": "Выберите инструмент и коснитесь сцены, чтобы править точки.",
 "panel_escolha_forma_editar_silhueta": "Выберите фигуру, чтобы править силуэт.",
 "panel_escolha_mascara_acima_editar_palco": "Выберите маску выше, чтобы править её на сцене.",
 "panel_escolhe": "Выбирает", "panel_esconder_x_y_z_3d": "Скрыть X/Y/Z (3D)",
 "panel_escreva_expressao_ou_toque_num_atalho": "Напишите выражение или коснитесь подсказки.",
 "panel_espaco": "Пробел", "panel_espessura": "Толщина", "panel_esquerda": "Влево",
 "panel_esquerda_direita": "Влево и вправо",
 "panel_esta_camada_ainda_nao_tem_grupos": "У этого слоя пока нет групп. Добавьте контур выше.",
 "panel_esta_camada_nao_tem_audio": "У этого слоя нет звука.",
 "panel_esta_camada_vetorial_edite_caminhos_painel": "Этот слой векторный: правьте контуры на панели «Вектор».",
 "panel_esta_curva_igual_nos_dois_sentidos": "Эта кривая одинакова в обе стороны",
 "panel_estabilizar_pelo_ponto": "Стабилизировать по точке",
 "panel_este_efeito_nao_tem_ajustes": "У этого эффекта нет настроек.",
 "panel_este_efeito_saiu_aurea_nao_desenha": "Этот эффект покинул Aurea и больше ничего не рисует. Он сохранён здесь, чтобы вы решили — остальная часть слоя цела.",
 "panel_este_efeito_saiu_catalogo_ele_nao": "Этот эффект ушёл из каталога. Он больше не рисует; удалите его через ⋯.",
 "panel_este_trecho_quadro_parado_apare_bordas": "Этот участок — стоп-кадр. Обрежьте края на таймлайне, чтобы изменить, сколько он держится на экране.",
 "panel_este_video_nao_tem_trilha_som": "В этом видео нет звуковой дорожки.",
 "panel_estilo": "Стиль", "panel_estudio_neutro": "Нейтральная студия",
 "panel_excluir_sobreposicao": "Удалить наложение", "panel_expandir": "Развернуть",
 "panel_expressao": "Выражение", "panel_expressao_3c65": "Выражение…",
 "panel_extrair_audio_camada": "Извлечь звук в отдельный слой",
 "panel_faiscas": "Искры", "panel_favoritar": "В избранное", "panel_fechar": "Закрыть",
 "panel_fechar_caminho": "Замкнуть контур",
 "panel_ferramentas_pontos_transformam_forma_pronta_caminho": "Инструменты точек превращают готовую фигуру в свободный контур.",
 "panel_fim": "Конец", "panel_fonte": "Шрифт", "panel_forma_animada": "Анимированная фигура",
 "panel_forma_anterior": "Предыдущая фигура", "panel_fundo": "Фон",
 "panel_gerar_legendas": "Создать субтитры", "panel_girar_3d_x_y": "Вращать в 3D (X и Y)",
 "panel_giro": "Вращение", "panel_gravidade": "Гравитация", "panel_grupo_visivel": "Группа видима",
 "panel_guarda_curva_keyframe_escolhido": "Сохраняет кривую выбранного ключа.",
 "panel_guarda_efeitos_camada_keyframes": "Сохраняет эффекты слоя вместе с ключами.",
 "panel_guarda_estilo_ou_animacao_texto": "Сохраняет стиль и/или анимацию текста.",
 "panel_guarda_keyframes_movimento_camada": "Сохраняет ключи движения слоя.",
 "panel_guarda_opcoes_atuais_legenda": "Сохраняет текущие настройки субтитра.",
 "panel_idioma_fala": "Язык речи", "panel_imagem_ambiente": "Изображение окружения ✓",
 "panel_importar": "Импорт", "panel_importar_legenda_srt": "Импорт субтитров (.srt)",
 "panel_inicio": "Начало",
 "panel_inicio_camada_fica_lugar_fim_acompanha": "Начало слоя остаётся на месте; конец следует за новой скоростью.",
 "panel_intensidade": "Интенсивность", "panel_intensidade_camada_ajuste": "Интенсивность слоя-коррекции",
 "panel_intensidade_desfoque": "Интенсивность размытия", "panel_intensidade_desfoque_eef9": "интенсивность размытия",
 "panel_intensidade_vale_todas_camadas_desfoque_neste": "Интенсивность действует на все размытые слои в этом проекте.",
 "panel_intersecao": "Пересечение", "panel_inverter_curva": "инвертировать кривую",
 "panel_inverter_direcao_caminho": "Инвертировать направление контура",
 "panel_inverter_mostrar_lado_fora": "Инвертировать (показать внешнюю сторону)",
}

HI = {
 "panel_desfoque": "ब्लर",
 "panel_desfoque_brilho_cor_outros_efeitos_aplicados": "इस वेक्टर पर लगाए गए ब्लर, चमक, रंग और बाक़ी इफ़ेक्ट।",
 "panel_desfoque_movimento": "मोशन ब्लर", "panel_desfoque_movimento_video": "वीडियो के मोशन का ब्लर",
 "panel_desfoque_sombra": "छाया का ब्लर", "panel_desligada": "बंद",
 "panel_desligada_propriedade_usa_keyframes": "बंद: यह प्रॉपर्टी कीफ़्रेम इस्तेमाल करती है।",
 "panel_desligar_efeito": "इफ़ेक्ट बंद करें", "panel_desligar_efeitos": "इफ़ेक्ट बंद करें",
 "panel_desligar_todos": "सभी बंद करें",
 "panel_deslize_ajustar_profundidade_toque_z_voltar": "गहराई समायोजित करने के लिए स्लाइड करें · X/Y पर लौटने के लिए Z दबाएँ",
 "panel_deslize_mover_camada": "लेयर हिलाने के लिए स्लाइड करें",
 "panel_deslize_mover_toque_z_profundidade": "हिलाने के लिए स्लाइड करें · गहराई के लिए Z दबाएँ",
 "panel_deslize_ponto_giro_botao_centro_devolve": "घुमाव बिंदु स्लाइड करें · केंद्र बटन इसे शून्य पर लौटाता है",
 "panel_deslocamento": "विस्थापन", "panel_deslocar_tracos": "स्ट्रोक खिसकाएँ",
 "panel_deslocar_trecho": "हिस्सा खिसकाएँ", "panel_diferenca": "अंतर",
 "panel_digite_texto": "टेक्स्ट लिखें", "panel_direcao": "दिशा", "panel_direita": "दाएँ",
 "panel_distancia_x": "दूरी X", "panel_distancia_y": "दूरी Y",
 "panel_duracao_cada": "हर एक की अवधि", "panel_durar_ate_fim_camada": "लेयर के अंत तक चले",
 "panel_easing_curve": "ईज़िंग कर्व",
 "panel_editando_pontos_palco_toque_concluir_palco": "स्टेज पर बिंदु संपादित हो रहे हैं। पूरा होने पर (स्टेज पर) हो गया दबाएँ।",
 "panel_editar_curva_propriedade": "प्रॉपर्टी का कर्व संपादित करें",
 "panel_editar_expressao": "एक्सप्रेशन संपादित करें", "panel_editar_forma": "आकृति संपादित करें",
 "panel_efeito_removido": "इफ़ेक्ट हटाया गया", "panel_efeitos": "इफ़ेक्ट",
 "panel_efeitos_camada": "लेयर के इफ़ेक्ट", "panel_elipse": "दीर्घवृत्त",
 "panel_elipse_meio_camada_pronta_ajustar": "लेयर के बीच एक दीर्घवृत्त, समायोजन के लिए तैयार।",
 "panel_encolher_caber": "फ़िट होने तक छोटा करें", "panel_entrada_suave": "सौम्य प्रवेश",
 "panel_entrada_suave_1fd1": "सौम्य प्रवेश", "panel_equilibrado": "संतुलित", "panel_escala": "स्केल",
 "panel_escolha_camada_abaixo": "नीचे की लेयर चुनें",
 "panel_escolha_camada_vetorial": "वेक्टर लेयर चुनें।",
 "panel_escolha_estilo_ou_animacao": "शैली और/या एनिमेशन चुनें",
 "panel_escolha_ferramenta_toque_palco_editar_pontos": "औज़ार चुनें और बिंदु संपादित करने के लिए स्टेज दबाएँ।",
 "panel_escolha_forma_editar_silhueta": "सिल्हूट संपादित करने के लिए आकृति चुनें।",
 "panel_escolha_mascara_acima_editar_palco": "स्टेज पर संपादित करने के लिए ऊपर से मास्क चुनें।",
 "panel_escolhe": "चुनता है", "panel_esconder_x_y_z_3d": "X/Y/Z छिपाएँ (3D)",
 "panel_escreva_expressao_ou_toque_num_atalho": "एक्सप्रेशन लिखें या शॉर्टकट दबाएँ।",
 "panel_espaco": "अंतराल", "panel_espessura": "मोटाई", "panel_esquerda": "बाएँ",
 "panel_esquerda_direita": "बाएँ और दाएँ",
 "panel_esta_camada_ainda_nao_tem_grupos": "इस लेयर में अभी समूह नहीं हैं। ऊपर एक पथ जोड़ें।",
 "panel_esta_camada_nao_tem_audio": "इस लेयर में ऑडियो नहीं है।",
 "panel_esta_camada_vetorial_edite_caminhos_painel": "यह लेयर वेक्टर है: पथ वेक्टर पैनल में संपादित करें।",
 "panel_esta_curva_igual_nos_dois_sentidos": "यह कर्व दोनों दिशाओं में एक जैसा है",
 "panel_estabilizar_pelo_ponto": "बिंदु से स्थिर करें",
 "panel_este_efeito_nao_tem_ajustes": "इस इफ़ेक्ट में कोई सेटिंग नहीं है।",
 "panel_este_efeito_saiu_aurea_nao_desenha": "यह इफ़ेक्ट Aurea से हट गया और अब कुछ नहीं बनाता। यह यहाँ आपके फ़ैसले के लिए रखा है — बाक़ी लेयर सुरक्षित है।",
 "panel_este_efeito_saiu_catalogo_ele_nao": "यह इफ़ेक्ट कैटलॉग से हट गया। अब नहीं बनता; ⋯ से हटाएँ।",
 "panel_este_trecho_quadro_parado_apare_bordas": "यह हिस्सा एक स्थिर फ़्रेम है। स्क्रीन पर कितनी देर रहे, यह बदलने के लिए टाइमलाइन पर किनारे ट्रिम करें।",
 "panel_este_video_nao_tem_trilha_som": "इस वीडियो में ऑडियो ट्रैक नहीं है।",
 "panel_estilo": "शैली", "panel_estudio_neutro": "न्यूट्रल स्टूडियो",
 "panel_excluir_sobreposicao": "ओवरले हटाएँ", "panel_expandir": "फैलाएँ",
 "panel_expressao": "एक्सप्रेशन", "panel_expressao_3c65": "एक्सप्रेशन…",
 "panel_extrair_audio_camada": "ऑडियो को अलग लेयर में निकालें",
 "panel_faiscas": "चिंगारियाँ", "panel_favoritar": "पसंदीदा", "panel_fechar": "बंद करें",
 "panel_fechar_caminho": "पथ बंद करें",
 "panel_ferramentas_pontos_transformam_forma_pronta_caminho": "बिंदु औज़ार तैयार आकृति को मुक्त पथ में बदल देते हैं।",
 "panel_fim": "अंत", "panel_fonte": "फ़ॉन्ट", "panel_forma_animada": "एनिमेटेड आकृति",
 "panel_forma_anterior": "पिछली आकृति", "panel_fundo": "पृष्ठभूमि",
 "panel_gerar_legendas": "कैप्शन बनाएँ", "panel_girar_3d_x_y": "3D में घुमाएँ (X और Y)",
 "panel_giro": "घुमाव", "panel_gravidade": "गुरुत्व", "panel_grupo_visivel": "समूह दिखाई दे",
 "panel_guarda_curva_keyframe_escolhido": "चुने हुए कीफ़्रेम का कर्व सहेजता है।",
 "panel_guarda_efeitos_camada_keyframes": "लेयर के इफ़ेक्ट कीफ़्रेम के साथ सहेजता है।",
 "panel_guarda_estilo_ou_animacao_texto": "टेक्स्ट की शैली और/या एनिमेशन सहेजता है।",
 "panel_guarda_keyframes_movimento_camada": "लेयर के मोशन कीफ़्रेम सहेजता है।",
 "panel_guarda_opcoes_atuais_legenda": "कैप्शन की मौजूदा सेटिंग्स सहेजता है।",
 "panel_idioma_fala": "बोली की भाषा", "panel_imagem_ambiente": "वातावरण छवि ✓",
 "panel_importar": "आयात करें", "panel_importar_legenda_srt": "कैप्शन आयात करें (.srt)",
 "panel_inicio": "शुरुआत",
 "panel_inicio_camada_fica_lugar_fim_acompanha": "लेयर की शुरुआत जगह पर रहती है; अंत नई गति के साथ चलता है।",
 "panel_intensidade": "तीव्रता", "panel_intensidade_camada_ajuste": "समायोजन लेयर की तीव्रता",
 "panel_intensidade_desfoque": "ब्लर की तीव्रता", "panel_intensidade_desfoque_eef9": "ब्लर की तीव्रता",
 "panel_intensidade_vale_todas_camadas_desfoque_neste": "यह तीव्रता इस प्रोजेक्ट की सभी ब्लर वाली लेयर पर लागू होती है।",
 "panel_intersecao": "प्रतिच्छेद", "panel_inverter_curva": "कर्व उलटें",
 "panel_inverter_direcao_caminho": "पथ की दिशा उलटें",
 "panel_inverter_mostrar_lado_fora": "उलटें (बाहरी हिस्सा दिखाएँ)",
}

ID = {
 "panel_desfoque": "Blur",
 "panel_desfoque_brilho_cor_outros_efeitos_aplicados": "Blur, kecerahan, warna, dan efek lain yang diterapkan ke vektor ini.",
 "panel_desfoque_movimento": "Motion blur", "panel_desfoque_movimento_video": "Blur gerak video",
 "panel_desfoque_sombra": "blur bayangan", "panel_desligada": "Mati",
 "panel_desligada_propriedade_usa_keyframes": "Mati: properti memakai keyframe-nya.",
 "panel_desligar_efeito": "Matikan efek", "panel_desligar_efeitos": "matikan efek",
 "panel_desligar_todos": "Matikan semua",
 "panel_deslize_ajustar_profundidade_toque_z_voltar": "Geser untuk mengatur kedalaman · ketuk Z untuk kembali ke X/Y",
 "panel_deslize_mover_camada": "Geser untuk memindahkan lapisan",
 "panel_deslize_mover_toque_z_profundidade": "Geser untuk memindahkan · ketuk Z untuk kedalaman",
 "panel_deslize_ponto_giro_botao_centro_devolve": "Geser titik putarnya · tombol Tengah mengembalikannya ke nol",
 "panel_deslocamento": "Pergeseran", "panel_deslocar_tracos": "Geser goresan",
 "panel_deslocar_trecho": "Geser potongan", "panel_diferenca": "Selisih",
 "panel_digite_texto": "Ketik teksnya", "panel_direcao": "Arah", "panel_direita": "Kanan",
 "panel_distancia_x": "Jarak X", "panel_distancia_y": "Jarak Y",
 "panel_duracao_cada": "Durasi masing-masing", "panel_durar_ate_fim_camada": "Bertahan sampai akhir lapisan",
 "panel_easing_curve": "Kurva easing",
 "panel_editando_pontos_palco_toque_concluir_palco": "Mengedit titik di panggung. Ketuk Selesai (di panggung) bila sudah.",
 "panel_editar_curva_propriedade": "Edit kurva properti",
 "panel_editar_expressao": "Edit ekspresi", "panel_editar_forma": "Edit bentuk",
 "panel_efeito_removido": "Efek dihapus", "panel_efeitos": "Efek",
 "panel_efeitos_camada": "Efek lapisan", "panel_elipse": "Elips",
 "panel_elipse_meio_camada_pronta_ajustar": "Sebuah elips di tengah lapisan, siap disesuaikan.",
 "panel_encolher_caber": "Kecilkan agar muat", "panel_entrada_suave": "Masuk halus",
 "panel_entrada_suave_1fd1": "masuk halus", "panel_equilibrado": "Seimbang", "panel_escala": "Skala",
 "panel_escolha_camada_abaixo": "Pilih lapisan di bawah",
 "panel_escolha_camada_vetorial": "Pilih lapisan vektor.",
 "panel_escolha_estilo_ou_animacao": "Pilih gaya dan/atau animasi",
 "panel_escolha_ferramenta_toque_palco_editar_pontos": "Pilih alat dan ketuk panggung untuk mengedit titiknya.",
 "panel_escolha_forma_editar_silhueta": "Pilih bentuk untuk mengedit silhuetnya.",
 "panel_escolha_mascara_acima_editar_palco": "Pilih masker di atas untuk mengeditnya di panggung.",
 "panel_escolhe": "Memilih", "panel_esconder_x_y_z_3d": "Sembunyikan X/Y/Z (3D)",
 "panel_escreva_expressao_ou_toque_num_atalho": "Tulis ekspresi atau ketuk pintasan.",
 "panel_espaco": "Jarak", "panel_espessura": "Ketebalan", "panel_esquerda": "Kiri",
 "panel_esquerda_direita": "Kiri dan kanan",
 "panel_esta_camada_ainda_nao_tem_grupos": "Lapisan ini belum punya grup. Tambah jalur di atas.",
 "panel_esta_camada_nao_tem_audio": "Lapisan ini tidak punya audio.",
 "panel_esta_camada_vetorial_edite_caminhos_painel": "Lapisan ini vektor: edit jalurnya di panel Vektor.",
 "panel_esta_curva_igual_nos_dois_sentidos": "Kurva ini sama di kedua arah",
 "panel_estabilizar_pelo_ponto": "Stabilkan dari titik",
 "panel_este_efeito_nao_tem_ajustes": "Efek ini tidak punya pengaturan.",
 "panel_este_efeito_saiu_aurea_nao_desenha": "Efek ini keluar dari Aurea e não desenha mais nada. Ficou guardado aqui para você decidir — o resto da lapisan utuh.",
 "panel_este_efeito_saiu_catalogo_ele_nao": "Efek ini keluar dari katalog. Tidak menggambar lagi; hapus lewat ⋯.",
 "panel_este_trecho_quadro_parado_apare_bordas": "Potongan ini adalah frame beku. Pangkas tepinya di timeline untuk mengubah berapa lama ia tampil.",
 "panel_este_video_nao_tem_trilha_som": "Video ini tidak punya trek audio.",
 "panel_estilo": "Gaya", "panel_estudio_neutro": "Studio netral",
 "panel_excluir_sobreposicao": "Hapus hamparan", "panel_expandir": "Bentangkan",
 "panel_expressao": "Ekspresi", "panel_expressao_3c65": "Ekspresi…",
 "panel_extrair_audio_camada": "Ekstrak audionya ke lapisan",
 "panel_faiscas": "Percikan", "panel_favoritar": "Favoritkan", "panel_fechar": "Tutup",
 "panel_fechar_caminho": "Tutup jalur",
 "panel_ferramentas_pontos_transformam_forma_pronta_caminho": "Alat titik mengubah bentuk siap jadi jalur bebas.",
 "panel_fim": "Akhir", "panel_fonte": "Font", "panel_forma_animada": "Bentuk beranimasi",
 "panel_forma_anterior": "Bentuk sebelumnya", "panel_fundo": "Latar",
 "panel_gerar_legendas": "Buat teks", "panel_girar_3d_x_y": "Putar dalam 3D (X dan Y)",
 "panel_giro": "Putaran", "panel_gravidade": "Gravitasi", "panel_grupo_visivel": "Grup terlihat",
 "panel_guarda_curva_keyframe_escolhido": "Menyimpan kurva keyframe terpilih.",
 "panel_guarda_efeitos_camada_keyframes": "Menyimpan efek lapisan bersama keyframe-nya.",
 "panel_guarda_estilo_ou_animacao_texto": "Menyimpan gaya dan/atau animasi teks.",
 "panel_guarda_keyframes_movimento_camada": "Menyimpan keyframe gerak lapisan.",
 "panel_guarda_opcoes_atuais_legenda": "Menyimpan opsi teks yang sekarang.",
 "panel_idioma_fala": "Bahasa ucapan", "panel_imagem_ambiente": "Gambar lingkungan ✓",
 "panel_importar": "Impor", "panel_importar_legenda_srt": "Impor teks (.srt)",
 "panel_inicio": "Awal",
 "panel_inicio_camada_fica_lugar_fim_acompanha": "Awal lapisan tetap di tempatnya; akhirnya mengikuti kecepatan baru.",
 "panel_intensidade": "Intensitas", "panel_intensidade_camada_ajuste": "Intensitas lapisan penyesuaian",
 "panel_intensidade_desfoque": "Intensitas blur", "panel_intensidade_desfoque_eef9": "intensitas blur",
 "panel_intensidade_vale_todas_camadas_desfoque_neste": "Intensitasnya berlaku untuk semua lapisan ber-blur di proyek ini.",
 "panel_intersecao": "Irisan", "panel_inverter_curva": "balik kurva",
 "panel_inverter_direcao_caminho": "Balik arah jalur",
 "panel_inverter_mostrar_lado_fora": "Balik (tampilkan sisi luar)",
}

AR = {
 "panel_desfoque": "ضباب",
 "panel_desfoque_brilho_cor_outros_efeitos_aplicados": "الضباب والسطوع واللون وبقية المؤثرات المطبَّقة على هذا المتجه.",
 "panel_desfoque_movimento": "ضبابية الحركة", "panel_desfoque_movimento_video": "ضبابية حركة الفيديو",
 "panel_desfoque_sombra": "ضبابية الظل", "panel_desligada": "مطفأة",
 "panel_desligada_propriedade_usa_keyframes": "مطفأة: الخاصية تستخدم الإطارات المفتاحية.",
 "panel_desligar_efeito": "إطفاء المؤثر", "panel_desligar_efeitos": "إطفاء المؤثرات",
 "panel_desligar_todos": "إطفاء الكل",
 "panel_deslize_ajustar_profundidade_toque_z_voltar": "اسحب لضبط العمق · اضغط Z للعودة إلى X/Y",
 "panel_deslize_mover_camada": "اسحب لتحريك الطبقة",
 "panel_deslize_mover_toque_z_profundidade": "اسحب للتحريك · اضغط Z للعمق",
 "panel_deslize_ponto_giro_botao_centro_devolve": "اسحب نقطة الدوران · زر المركز يعيدها إلى الصفر",
 "panel_deslocamento": "الإزاحة", "panel_deslocar_tracos": "إزاحة الخطوط",
 "panel_deslocar_trecho": "إزاحة المقطع", "panel_diferenca": "الفرق",
 "panel_digite_texto": "اكتب النص", "panel_direcao": "الاتجاه", "panel_direita": "يمين",
 "panel_distancia_x": "المسافة X", "panel_distancia_y": "المسافة Y",
 "panel_duracao_cada": "مدة كل واحدة", "panel_durar_ate_fim_camada": "يستمر حتى نهاية الطبقة",
 "panel_easing_curve": "منحنى التمهيد",
 "panel_editando_pontos_palco_toque_concluir_palco": "تحرير النقاط على المسرح. اضغط «تم» (على المسرح) عند الانتهاء.",
 "panel_editar_curva_propriedade": "تحرير منحنى الخاصية",
 "panel_editar_expressao": "تحرير التعبير", "panel_editar_forma": "تحرير الشكل",
 "panel_efeito_removido": "أُزيل المؤثر", "panel_efeitos": "المؤثرات",
 "panel_efeitos_camada": "مؤثرات الطبقة", "panel_elipse": "بيضاوي",
 "panel_elipse_meio_camada_pronta_ajustar": "بيضاوي في وسط الطبقة، جاهز للضبط.",
 "panel_encolher_caber": "تصغير ليتّسع", "panel_entrada_suave": "دخول ناعم",
 "panel_entrada_suave_1fd1": "دخول ناعم", "panel_equilibrado": "متوازن", "panel_escala": "المقياس",
 "panel_escolha_camada_abaixo": "اختر الطبقة بالأسفل",
 "panel_escolha_camada_vetorial": "اختر طبقة متجهة.",
 "panel_escolha_estilo_ou_animacao": "اختر نمطًا و/أو تحريكًا",
 "panel_escolha_ferramenta_toque_palco_editar_pontos": "اختر أداة واضغط المسرح لتحرير النقاط.",
 "panel_escolha_forma_editar_silhueta": "اختر شكلًا لتحرير الظلّ الخارجي.",
 "panel_escolha_mascara_acima_editar_palco": "اختر قناعًا بالأعلى لتحريره على المسرح.",
 "panel_escolhe": "يختار", "panel_esconder_x_y_z_3d": "إخفاء X/Y/Z (3D)",
 "panel_escreva_expressao_ou_toque_num_atalho": "اكتب تعبيرًا أو اضغط اختصارًا.",
 "panel_espaco": "المسافة", "panel_espessura": "السماكة", "panel_esquerda": "يسار",
 "panel_esquerda_direita": "يسار ويمين",
 "panel_esta_camada_ainda_nao_tem_grupos": "هذه الطبقة بلا مجموعات بعد. أضف مسارًا بالأعلى.",
 "panel_esta_camada_nao_tem_audio": "هذه الطبقة بلا صوت.",
 "panel_esta_camada_vetorial_edite_caminhos_painel": "هذه الطبقة متجهة: حرّر المسارات في لوحة المتجه.",
 "panel_esta_curva_igual_nos_dois_sentidos": "هذا المنحنى متساوٍ في الاتجاهين",
 "panel_estabilizar_pelo_ponto": "تثبيت من النقطة",
 "panel_este_efeito_nao_tem_ajustes": "هذا المؤثر بلا إعدادات.",
 "panel_este_efeito_saiu_aurea_nao_desenha": "خرج هذا المؤثر من Aurea ولم يعد يرسم شيئًا. بقي محفوظًا هنا لتقرّر — وبقية الطبقة سليمة.",
 "panel_este_efeito_saiu_catalogo_ele_nao": "خرج هذا المؤثر من الكتالوج. لم يعد يرسم؛ احذفه من ⋯.",
 "panel_este_trecho_quadro_parado_apare_bordas": "هذا المقطع إطار مجمّد. اقصّ الحواف على الخط الزمني لتغيير مدة بقائه على الشاشة.",
 "panel_este_video_nao_tem_trilha_som": "هذا الفيديو بلا مسار صوتي.",
 "panel_estilo": "النمط", "panel_estudio_neutro": "استوديو محايد",
 "panel_excluir_sobreposicao": "حذف الطبقة المتراكبة", "panel_expandir": "توسيع",
 "panel_expressao": "تعبير", "panel_expressao_3c65": "تعبير…",
 "panel_extrair_audio_camada": "استخراج الصوت إلى طبقة",
 "panel_faiscas": "شرر", "panel_favoritar": "إضافة للمفضّلة", "panel_fechar": "إغلاق",
 "panel_fechar_caminho": "إغلاق المسار",
 "panel_ferramentas_pontos_transformam_forma_pronta_caminho": "أدوات النقاط تحوّل الشكل الجاهز إلى مسار حر.",
 "panel_fim": "النهاية", "panel_fonte": "الخط", "panel_forma_animada": "شكل متحرّك",
 "panel_forma_anterior": "الشكل السابق", "panel_fundo": "الخلفية",
 "panel_gerar_legendas": "إنشاء الترجمات", "panel_girar_3d_x_y": "تدوير في 3D (X و Y)",
 "panel_giro": "الدوران", "panel_gravidade": "الجاذبية", "panel_grupo_visivel": "المجموعة ظاهرة",
 "panel_guarda_curva_keyframe_escolhido": "يحفظ منحنى الإطار المفتاحي المختار.",
 "panel_guarda_efeitos_camada_keyframes": "يحفظ مؤثرات الطبقة مع الإطارات المفتاحية.",
 "panel_guarda_estilo_ou_animacao_texto": "يحفظ نمط النص و/أو تحريكه.",
 "panel_guarda_keyframes_movimento_camada": "يحفظ إطارات حركة الطبقة المفتاحية.",
 "panel_guarda_opcoes_atuais_legenda": "يحفظ خيارات الترجمة الحالية.",
 "panel_idioma_fala": "لغة الكلام", "panel_imagem_ambiente": "صورة المحيط ✓",
 "panel_importar": "استيراد", "panel_importar_legenda_srt": "استيراد ترجمة (.srt)",
 "panel_inicio": "البداية",
 "panel_inicio_camada_fica_lugar_fim_acompanha": "بداية الطبقة تبقى في مكانها؛ والنهاية تتبع السرعة الجديدة.",
 "panel_intensidade": "الشدّة", "panel_intensidade_camada_ajuste": "شدّة طبقة الضبط",
 "panel_intensidade_desfoque": "شدّة الضباب", "panel_intensidade_desfoque_eef9": "شدّة الضباب",
 "panel_intensidade_vale_todas_camadas_desfoque_neste": "الشدّة تنطبق على كل الطبقات ذات الضباب في هذا المشروع.",
 "panel_intersecao": "تقاطع", "panel_inverter_curva": "عكس المنحنى",
 "panel_inverter_direcao_caminho": "عكس اتجاه المسار",
 "panel_inverter_mostrar_lado_fora": "عكس (إظهار الجهة الخارجية)",
}

run({"en": EN, "es": ES, "ru": RU, "hi": HI, "id": ID, "ar": AR})
