# Lote 5 de traducoes (105 chaves).
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from i18n_translate import run

EN = {
 "panel_inverter_sentido": "Reverse direction", "panel_ja_existe_sera_substituido": "Already exists: it will be replaced.",
 "panel_juntar_caminhos_grupo": "Join the group's paths",
 "panel_juntar_precisa_2_caminhos_grupo_use": "Joining needs 2 paths in the group: use + Add above.",
 "panel_keyframe_anterior": "Previous keyframe", "panel_lados": "Sides", "panel_largura": "Width",
 "panel_largura_caixa": "Box width", "panel_largura_caixa_4a83": "box width",
 "panel_largura_contorno": "Outline width", "panel_legendas": "Captions",
 "panel_lento_meio": "Slow in the middle", "panel_letra": "Letter", "panel_ligada": "On",
 "panel_ligar_efeito": "Turn the effect on", "panel_ligar_efeitos": "turn on effects",
 "panel_ligar_todos": "Turn all on", "panel_limite_canto": "Corner limit",
 "panel_limpar_busca": "Clear search", "panel_linear": "Linear", "panel_linha": "Line",
 "panel_linha_reta": "Straight line", "panel_livre": "Free",
 "panel_losango_trilho_grava_keyframe_linha_acesa": "The track diamond records a keyframe of the lit line at the playhead.",
 "panel_luz_ambiente": "Ambient light", "panel_maior": "Larger",
 "panel_mais_opcoes_efeitos": "More effect options",
 "panel_mantem_forma_libera_pontos": "Keeps the shape and frees the points.",
 "panel_manter": "Keep", "panel_manter_proporcao": "Keep the aspect ratio",
 "panel_marcar_keyframe_aqui": "Mark a keyframe here",
 "panel_margem_fundo": "Background margin", "panel_margem_fundo_276c": "background margin",
 "panel_margem_inicial": "Starting margin", "panel_margem_texto_caminho": "text margin on the path",
 "panel_mascara_mostra_so_parte_camada_escolha": "A mask shows only part of the layer. Choose how to start:",
 "panel_mascara_recorte": "Mask and cut-out",
 "panel_mascara_segue_esta_embaixo_dela_cabecote": "The mask follows what is beneath it, from the playhead to the end of the clip.",
 "panel_mascaras": "Masks", "panel_material": "Material",
 "panel_material_ambiente": "Material and environment", "panel_mistura": "Blending",
 "panel_mistura_opacidade": "Blending and opacity", "panel_misturar": "Blend",
 "panel_modo_escolhido_acima": "With the mode chosen above.",
 "panel_mostrar_x_y_z_3d": "Show X/Y/Z (3D)", "panel_motor_recusou_esta_propriedade": "The engine refused this property.",
 "panel_move_so_este_grupo_dentro_camada": "Moves only this group inside the layer.",
 "panel_move_video_ponto_ficar_parado_tela": "Moves the video so the point stays still on screen.",
 "panel_mover_baixo": "Move down", "panel_mover_cima": "Move up", "panel_mover_pivo": "move pivot",
 "panel_mover_ponto_curva_tempo": "move a point on the time curve",
 "panel_movimento_camera_encontrado": "Camera motion found", "panel_movimento_suave": "Smooth motion",
 "panel_mudo": "Muted", "panel_nao_ha_outra_camada_possa_recortar": "There is no other layer that can cut this one.",
 "panel_nao_juntar": "Don't join", "panel_nao_recortar": "Don't cut",
 "panel_negrito": "Bold", "panel_neve": "Snow", "panel_nome_preset": "Give the preset a name",
 "panel_normal": "Normal",
 "panel_novo_grupo_preenchimento_borda_proprios": "New group (with its own fill and border)",
 "panel_objetos_aproximam_ou_giram": "For objects that come closer or rotate.",
 "panel_objetos_so_andam_pela_tela": "For objects that only move across the screen.",
 "panel_onde_caminhos_cruzam": "Where the paths cross", "panel_opacidade": "Opacity",
 "panel_opacidade_final": "End opacity", "panel_opacidade_inicial": "Start opacity",
 "panel_ordem": "In order", "panel_ordem_aleatoria": "Random order",
 "panel_ordem_copias": "Order of the copies", "panel_overshoot": "Overshoot",
 "panel_overshoot_9678": "Overshoot ✓", "panel_padrao_aparelho": "Device default",
 "panel_palavra": "Word", "panel_parada_toque_trilho_animar": "Still — tap the track ◇ to animate",
 "panel_parado_toque_trilho_animar": "Still — tap the track ◇ to animate",
 "panel_paragrafo": "Paragraph", "panel_particulas": "Particles",
 "panel_particulas_segundo": "Particles per second", "panel_passagem": "Crossing",
 "panel_passar_tras_frente": "Pass from back to front", "panel_pela_forma": "By shape",
 "panel_pela_forma_aparece_onde_outra_camada": "By shape: it appears where the other layer exists. By brightness: where it is bright.",
 "panel_pela_forma_invertido": "By shape, inverted", "panel_pelo_brilho": "By brightness",
 "panel_pelo_brilho_invertido": "By brightness, inverted", "panel_perpendicular_caminho": "Perpendicular to the path",
 "panel_petalas": "Petals", "panel_pivo_x": "Pivot X", "panel_pivo_y": "Pivot Y",
 "panel_poeira_luz": "Light dust", "panel_pontas": "Ends",
 "panel_posicao_x": "Position X", "panel_posicao_y": "Position Y",
 "panel_preencher": "Fill", "panel_preencher_tudo": "Fill everything",
 "panel_preenchimento": "Fill", "panel_preenchimento_6e8f": "fill",
 "panel_preset_sai_deste_aparelho": "The preset leaves this device.",
 "panel_presets": "Presets", "panel_profundidade_z": "Depth Z",
 "panel_proxima_forma": "Next shape",
}

ES = {
 "panel_inverter_sentido": "Invertir el sentido", "panel_ja_existe_sera_substituido": "Ya existe: se reemplazará.",
 "panel_juntar_caminhos_grupo": "Unir los caminos del grupo",
 "panel_juntar_precisa_2_caminhos_grupo_use": "Unir necesita 2 caminos en el grupo: usa + Añadir arriba.",
 "panel_keyframe_anterior": "Keyframe anterior", "panel_lados": "Lados", "panel_largura": "Ancho",
 "panel_largura_caixa": "Ancho de la caja", "panel_largura_caixa_4a83": "ancho de la caja",
 "panel_largura_contorno": "Grosor del contorno", "panel_legendas": "Subtítulos",
 "panel_lento_meio": "Lento en medio", "panel_letra": "Letra", "panel_ligada": "Encendida",
 "panel_ligar_efeito": "Encender efecto", "panel_ligar_efeitos": "encender efectos",
 "panel_ligar_todos": "Encender todos", "panel_limite_canto": "Límite de la esquina",
 "panel_limpar_busca": "Quitar búsqueda", "panel_linear": "Lineal", "panel_linha": "Línea",
 "panel_linha_reta": "Línea recta", "panel_livre": "Libre",
 "panel_losango_trilho_grava_keyframe_linha_acesa": "El rombo del riel graba un keyframe de la línea encendida en el cabezal.",
 "panel_luz_ambiente": "Luz de ambiente", "panel_maior": "Mayor",
 "panel_mais_opcoes_efeitos": "Más opciones de los efectos",
 "panel_mantem_forma_libera_pontos": "Mantiene la forma y libera los puntos.",
 "panel_manter": "Mantener", "panel_manter_proporcao": "Mantener proporción",
 "panel_marcar_keyframe_aqui": "Marcar un keyframe aquí",
 "panel_margem_fundo": "Margen del fondo", "panel_margem_fundo_276c": "margen del fondo",
 "panel_margem_inicial": "Margen inicial", "panel_margem_texto_caminho": "margen del texto en el camino",
 "panel_mascara_mostra_so_parte_camada_escolha": "Una máscara muestra solo una parte de la capa. Elige cómo empezar:",
 "panel_mascara_recorte": "Máscara y recorte",
 "panel_mascara_segue_esta_embaixo_dela_cabecote": "La máscara sigue lo que está debajo, del cabezal al final del clip.",
 "panel_mascaras": "Máscaras", "panel_material": "Material",
 "panel_material_ambiente": "Material y entorno", "panel_mistura": "Mezcla",
 "panel_mistura_opacidade": "Mezcla y opacidad", "panel_misturar": "Mezclar",
 "panel_modo_escolhido_acima": "Con el modo elegido arriba.",
 "panel_mostrar_x_y_z_3d": "Mostrar X/Y/Z (3D)", "panel_motor_recusou_esta_propriedade": "El motor rechazó esta propiedad.",
 "panel_move_so_este_grupo_dentro_camada": "Mueve solo este grupo dentro de la capa.",
 "panel_move_video_ponto_ficar_parado_tela": "Mueve el vídeo para que el punto quede quieto en pantalla.",
 "panel_mover_baixo": "Mover abajo", "panel_mover_cima": "Mover arriba", "panel_mover_pivo": "mover pivote",
 "panel_mover_ponto_curva_tempo": "mover punto de la curva de tiempo",
 "panel_movimento_camera_encontrado": "Movimiento de cámara encontrado", "panel_movimento_suave": "Movimiento suave",
 "panel_mudo": "Silenciado", "panel_nao_ha_outra_camada_possa_recortar": "No hay otra capa que pueda recortar esta.",
 "panel_nao_juntar": "No unir", "panel_nao_recortar": "No recortar",
 "panel_negrito": "Negrita", "panel_neve": "Nieve", "panel_nome_preset": "Ponle un nombre al preset",
 "panel_normal": "Normal",
 "panel_novo_grupo_preenchimento_borda_proprios": "Grupo nuevo (con relleno y borde propios)",
 "panel_objetos_aproximam_ou_giram": "Para objetos que se acercan o giran.",
 "panel_objetos_so_andam_pela_tela": "Para objetos que solo se mueven por la pantalla.",
 "panel_onde_caminhos_cruzam": "Donde los caminos se cruzan", "panel_opacidade": "Opacidad",
 "panel_opacidade_final": "Opacidad final", "panel_opacidade_inicial": "Opacidad inicial",
 "panel_ordem": "En orden", "panel_ordem_aleatoria": "Orden aleatorio",
 "panel_ordem_copias": "Orden de las copias", "panel_overshoot": "Overshoot",
 "panel_overshoot_9678": "Overshoot ✓", "panel_padrao_aparelho": "Predeterminado del dispositivo",
 "panel_palavra": "Palabra", "panel_parada_toque_trilho_animar": "Quieta — toca el ◇ del riel para animar",
 "panel_parado_toque_trilho_animar": "Quieto — toca el ◇ del riel para animar",
 "panel_paragrafo": "Párrafo", "panel_particulas": "Partículas",
 "panel_particulas_segundo": "Partículas por segundo", "panel_passagem": "Pasada",
 "panel_passar_tras_frente": "Pasar de atrás hacia adelante", "panel_pela_forma": "Por la forma",
 "panel_pela_forma_aparece_onde_outra_camada": "Por la forma: aparece donde existe la otra capa. Por el brillo: donde es clara.",
 "panel_pela_forma_invertido": "Por la forma, invertido", "panel_pelo_brilho": "Por el brillo",
 "panel_pelo_brilho_invertido": "Por el brillo, invertido", "panel_perpendicular_caminho": "Perpendicular al camino",
 "panel_petalas": "Pétalos", "panel_pivo_x": "Pivote en X", "panel_pivo_y": "Pivote en Y",
 "panel_poeira_luz": "Polvo de luz", "panel_pontas": "Puntas",
 "panel_posicao_x": "Posición X", "panel_posicao_y": "Posición Y",
 "panel_preencher": "Rellenar", "panel_preencher_tudo": "Rellenar todo",
 "panel_preenchimento": "Relleno", "panel_preenchimento_6e8f": "relleno",
 "panel_preset_sai_deste_aparelho": "El preset sale de este dispositivo.",
 "panel_presets": "Presets", "panel_profundidade_z": "Profundidad Z",
 "panel_proxima_forma": "Forma siguiente",
}

RU = {
 "panel_inverter_sentido": "Инвертировать направление", "panel_ja_existe_sera_substituido": "Уже есть: будет заменён.",
 "panel_juntar_caminhos_grupo": "Соединить контуры группы",
 "panel_juntar_precisa_2_caminhos_grupo_use": "Для соединения нужно 2 контура в группе: нажмите + Добавить выше.",
 "panel_keyframe_anterior": "Предыдущий ключ", "panel_lados": "Стороны", "panel_largura": "Ширина",
 "panel_largura_caixa": "Ширина блока", "panel_largura_caixa_4a83": "ширина блока",
 "panel_largura_contorno": "Толщина обводки", "panel_legendas": "Субтитры",
 "panel_lento_meio": "Медленно в середине", "panel_letra": "Буква", "panel_ligada": "Включена",
 "panel_ligar_efeito": "Включить эффект", "panel_ligar_efeitos": "включить эффекты",
 "panel_ligar_todos": "Включить все", "panel_limite_canto": "Предел угла",
 "panel_limpar_busca": "Очистить поиск", "panel_linear": "Линейно", "panel_linha": "Линия",
 "panel_linha_reta": "Прямая линия", "panel_livre": "Свободно",
 "panel_losango_trilho_grava_keyframe_linha_acesa": "Ромб дорожки записывает ключ включённой линии на курсоре.",
 "panel_luz_ambiente": "Свет окружения", "panel_maior": "Больше",
 "panel_mais_opcoes_efeitos": "Другие настройки эффектов",
 "panel_mantem_forma_libera_pontos": "Сохраняет фигуру и освобождает точки.",
 "panel_manter": "Сохранить", "panel_manter_proporcao": "Сохранять пропорции",
 "panel_marcar_keyframe_aqui": "Поставить ключ здесь",
 "panel_margem_fundo": "Отступ фона", "panel_margem_fundo_276c": "отступ фона",
 "panel_margem_inicial": "Начальный отступ", "panel_margem_texto_caminho": "отступ текста на контуре",
 "panel_mascara_mostra_so_parte_camada_escolha": "Маска показывает только часть слоя. Выберите, с чего начать:",
 "panel_mascara_recorte": "Маска и обрезка",
 "panel_mascara_segue_esta_embaixo_dela_cabecote": "Маска следует за тем, что под ней, от курсора до конца клипа.",
 "panel_mascaras": "Маски", "panel_material": "Материал",
 "panel_material_ambiente": "Материал и окружение", "panel_mistura": "Смешивание",
 "panel_mistura_opacidade": "Смешивание и прозрачность", "panel_misturar": "Смешать",
 "panel_modo_escolhido_acima": "С выбранным выше режимом.",
 "panel_mostrar_x_y_z_3d": "Показать X/Y/Z (3D)", "panel_motor_recusou_esta_propriedade": "Движок отклонил это свойство.",
 "panel_move_so_este_grupo_dentro_camada": "Смещает только эту группу внутри слоя.",
 "panel_move_video_ponto_ficar_parado_tela": "Сдвигает видео так, чтобы точка стояла на месте.",
 "panel_mover_baixo": "Вниз", "panel_mover_cima": "Вверх", "panel_mover_pivo": "сместить центр",
 "panel_mover_ponto_curva_tempo": "сместить точку кривой времени",
 "panel_movimento_camera_encontrado": "Движение камеры найдено", "panel_movimento_suave": "Плавное движение",
 "panel_mudo": "Без звука", "panel_nao_ha_outra_camada_possa_recortar": "Нет другого слоя, который мог бы обрезать этот.",
 "panel_nao_juntar": "Не соединять", "panel_nao_recortar": "Не обрезать",
 "panel_negrito": "Жирный", "panel_neve": "Снег", "panel_nome_preset": "Дайте пресету имя",
 "panel_normal": "Обычный",
 "panel_novo_grupo_preenchimento_borda_proprios": "Новая группа (со своей заливкой и обводкой)",
 "panel_objetos_aproximam_ou_giram": "Для объектов, которые приближаются или вращаются.",
 "panel_objetos_so_andam_pela_tela": "Для объектов, которые только движутся по экрану.",
 "panel_onde_caminhos_cruzam": "Где контуры пересекаются", "panel_opacidade": "Прозрачность",
 "panel_opacidade_final": "Конечная прозрачность", "panel_opacidade_inicial": "Начальная прозрачность",
 "panel_ordem": "По порядку", "panel_ordem_aleatoria": "Случайный порядок",
 "panel_ordem_copias": "Порядок копий", "panel_overshoot": "Перелёт",
 "panel_overshoot_9678": "Перелёт ✓", "panel_padrao_aparelho": "Как на устройстве",
 "panel_palavra": "Слово", "panel_parada_toque_trilho_animar": "Стоит — коснитесь ◇ дорожки, чтобы анимировать",
 "panel_parado_toque_trilho_animar": "Стоит — коснитесь ◇ дорожки, чтобы анимировать",
 "panel_paragrafo": "Абзац", "panel_particulas": "Частицы",
 "panel_particulas_segundo": "Частиц в секунду", "panel_passagem": "Проход",
 "panel_passar_tras_frente": "Пройти сзади вперёд", "panel_pela_forma": "По форме",
 "panel_pela_forma_aparece_onde_outra_camada": "По форме: появляется там, где есть другой слой. По яркости: где он светлый.",
 "panel_pela_forma_invertido": "По форме, инвертировано", "panel_pelo_brilho": "По яркости",
 "panel_pelo_brilho_invertido": "По яркости, инвертировано", "panel_perpendicular_caminho": "Перпендикулярно контуру",
 "panel_petalas": "Лепестки", "panel_pivo_x": "Центр по X", "panel_pivo_y": "Центр по Y",
 "panel_poeira_luz": "Световая пыль", "panel_pontas": "Концы",
 "panel_posicao_x": "Позиция X", "panel_posicao_y": "Позиция Y",
 "panel_preencher": "Залить", "panel_preencher_tudo": "Залить всё",
 "panel_preenchimento": "Заливка", "panel_preenchimento_6e8f": "заливка",
 "panel_preset_sai_deste_aparelho": "Пресет покидает это устройство.",
 "panel_presets": "Пресеты", "panel_profundidade_z": "Глубина Z",
 "panel_proxima_forma": "Следующая фигура",
}

HI = {
 "panel_inverter_sentido": "दिशा उलटें", "panel_ja_existe_sera_substituido": "पहले से है: इसे बदल दिया जाएगा।",
 "panel_juntar_caminhos_grupo": "समूह के पथ जोड़ें",
 "panel_juntar_precisa_2_caminhos_grupo_use": "जोड़ने के लिए समूह में 2 पथ चाहिए: ऊपर + जोड़ें इस्तेमाल करें।",
 "panel_keyframe_anterior": "पिछला कीफ़्रेम", "panel_lados": "भुजाएँ", "panel_largura": "चौड़ाई",
 "panel_largura_caixa": "बॉक्स की चौड़ाई", "panel_largura_caixa_4a83": "बॉक्स की चौड़ाई",
 "panel_largura_contorno": "रूपरेखा की चौड़ाई", "panel_legendas": "कैप्शन",
 "panel_lento_meio": "बीच में धीमा", "panel_letra": "अक्षर", "panel_ligada": "चालू",
 "panel_ligar_efeito": "इफ़ेक्ट चालू करें", "panel_ligar_efeitos": "इफ़ेक्ट चालू करें",
 "panel_ligar_todos": "सभी चालू करें", "panel_limite_canto": "कोने की सीमा",
 "panel_limpar_busca": "खोज साफ़ करें", "panel_linear": "रैखिक", "panel_linha": "रेखा",
 "panel_linha_reta": "सीधी रेखा", "panel_livre": "मुक्त",
 "panel_losango_trilho_grava_keyframe_linha_acesa": "ट्रैक का हीरा प्लेहेड पर जली हुई लाइन का कीफ़्रेम दर्ज करता है।",
 "panel_luz_ambiente": "परिवेश प्रकाश", "panel_maior": "बड़ा",
 "panel_mais_opcoes_efeitos": "इफ़ेक्ट के और विकल्प",
 "panel_mantem_forma_libera_pontos": "आकृति रखता है और बिंदु मुक्त करता है।",
 "panel_manter": "रखें", "panel_manter_proporcao": "अनुपात बनाए रखें",
 "panel_marcar_keyframe_aqui": "यहाँ कीफ़्रेम लगाएँ",
 "panel_margem_fundo": "पृष्ठभूमि का हाशिया", "panel_margem_fundo_276c": "पृष्ठभूमि का हाशिया",
 "panel_margem_inicial": "शुरुआती हाशिया", "panel_margem_texto_caminho": "पथ पर टेक्स्ट का हाशिया",
 "panel_mascara_mostra_so_parte_camada_escolha": "मास्क लेयर का एक हिस्सा ही दिखाता है। शुरुआत कैसे करें चुनें:",
 "panel_mascara_recorte": "मास्क और कटाई",
 "panel_mascara_segue_esta_embaixo_dela_cabecote": "मास्क अपने नीचे वाले का पीछा करता है, प्लेहेड से क्लिप के अंत तक।",
 "panel_mascaras": "मास्क", "panel_material": "मटीरियल",
 "panel_material_ambiente": "मटीरियल और वातावरण", "panel_mistura": "मिश्रण",
 "panel_mistura_opacidade": "मिश्रण और अपारदर्शिता", "panel_misturar": "मिलाएँ",
 "panel_modo_escolhido_acima": "ऊपर चुने गए मोड के साथ।",
 "panel_mostrar_x_y_z_3d": "X/Y/Z दिखाएँ (3D)", "panel_motor_recusou_esta_propriedade": "इंजन ने यह प्रॉपर्टी अस्वीकार की।",
 "panel_move_so_este_grupo_dentro_camada": "लेयर के अंदर सिर्फ़ यह समूह हिलाता है।",
 "panel_move_video_ponto_ficar_parado_tela": "वीडियो को हिलाता है ताकि बिंदु स्क्रीन पर स्थिर रहे।",
 "panel_mover_baixo": "नीचे ले जाएँ", "panel_mover_cima": "ऊपर ले जाएँ", "panel_mover_pivo": "धुरी हिलाएँ",
 "panel_mover_ponto_curva_tempo": "समय कर्व का बिंदु हिलाएँ",
 "panel_movimento_camera_encontrado": "कैमरे की गति मिली", "panel_movimento_suave": "सौम्य गति",
 "panel_mudo": "मौन", "panel_nao_ha_outra_camada_possa_recortar": "ऐसी और कोई लेयर नहीं जो इसे काट सके।",
 "panel_nao_juntar": "न जोड़ें", "panel_nao_recortar": "न काटें",
 "panel_negrito": "बोल्ड", "panel_neve": "बर्फ़", "panel_nome_preset": "प्रीसेट को नाम दें",
 "panel_normal": "सामान्य",
 "panel_novo_grupo_preenchimento_borda_proprios": "नया समूह (अपने भरण और किनारे के साथ)",
 "panel_objetos_aproximam_ou_giram": "उन वस्तुओं के लिए जो पास आती या घूमती हैं।",
 "panel_objetos_so_andam_pela_tela": "उन वस्तुओं के लिए जो सिर्फ़ स्क्रीन पर चलती हैं।",
 "panel_onde_caminhos_cruzam": "जहाँ पथ काटते हैं", "panel_opacidade": "अपारदर्शिता",
 "panel_opacidade_final": "अंतिम अपारदर्शिता", "panel_opacidade_inicial": "शुरुआती अपारदर्शिता",
 "panel_ordem": "क्रम में", "panel_ordem_aleatoria": "बेतरतीब क्रम",
 "panel_ordem_copias": "प्रतियों का क्रम", "panel_overshoot": "ओवरशूट",
 "panel_overshoot_9678": "ओवरशूट ✓", "panel_padrao_aparelho": "डिवाइस डिफ़ॉल्ट",
 "panel_palavra": "शब्द", "panel_parada_toque_trilho_animar": "स्थिर — एनिमेट करने के लिए ट्रैक का ◇ दबाएँ",
 "panel_parado_toque_trilho_animar": "स्थिर — एनिमेट करने के लिए ट्रैक का ◇ दबाएँ",
 "panel_paragrafo": "पैराग्राफ़", "panel_particulas": "कण",
 "panel_particulas_segundo": "प्रति सेकंड कण", "panel_passagem": "गुज़र",
 "panel_passar_tras_frente": "पीछे से आगे जाएँ", "panel_pela_forma": "आकृति से",
 "panel_pela_forma_aparece_onde_outra_camada": "आकृति से: वहाँ दिखता है जहाँ दूसरी लेयर है। चमक से: जहाँ वह उजली है।",
 "panel_pela_forma_invertido": "आकृति से, उलटा", "panel_pelo_brilho": "चमक से",
 "panel_pelo_brilho_invertido": "चमक से, उलटा", "panel_perpendicular_caminho": "पथ के लंबवत",
 "panel_petalas": "पंखुड़ियाँ", "panel_pivo_x": "धुरी X", "panel_pivo_y": "धुरी Y",
 "panel_poeira_luz": "प्रकाश धूल", "panel_pontas": "सिरे",
 "panel_posicao_x": "स्थिति X", "panel_posicao_y": "स्थिति Y",
 "panel_preencher": "भरें", "panel_preencher_tudo": "सब भरें",
 "panel_preenchimento": "भरण", "panel_preenchimento_6e8f": "भरण",
 "panel_preset_sai_deste_aparelho": "प्रीसेट इस डिवाइस से हट जाता है।",
 "panel_presets": "प्रीसेट", "panel_profundidade_z": "गहराई Z",
 "panel_proxima_forma": "अगली आकृति",
}

ID = {
 "panel_inverter_sentido": "Balik arah", "panel_ja_existe_sera_substituido": "Sudah ada: akan diganti.",
 "panel_juntar_caminhos_grupo": "Gabung jalur grup",
 "panel_juntar_precisa_2_caminhos_grupo_use": "Menggabung perlu 2 jalur di grup: pakai + Tambah di atas.",
 "panel_keyframe_anterior": "Keyframe sebelumnya", "panel_lados": "Sisi", "panel_largura": "Lebar",
 "panel_largura_caixa": "Lebar kotak", "panel_largura_caixa_4a83": "lebar kotak",
 "panel_largura_contorno": "Tebal garis luar", "panel_legendas": "Teks",
 "panel_lento_meio": "Lambat di tengah", "panel_letra": "Huruf", "panel_ligada": "Nyala",
 "panel_ligar_efeito": "Nyalakan efek", "panel_ligar_efeitos": "nyalakan efek",
 "panel_ligar_todos": "Nyalakan semua", "panel_limite_canto": "Batas sudut",
 "panel_limpar_busca": "Hapus pencarian", "panel_linear": "Linear", "panel_linha": "Garis",
 "panel_linha_reta": "Garis lurus", "panel_livre": "Bebas",
 "panel_losango_trilho_grava_keyframe_linha_acesa": "Belah ketupat trek merekam keyframe garis yang menyala di kepala playback.",
 "panel_luz_ambiente": "Cahaya sekitar", "panel_maior": "Lebih besar",
 "panel_mais_opcoes_efeitos": "Opsi efek lainnya",
 "panel_mantem_forma_libera_pontos": "Menjaga bentuk dan membebaskan titiknya.",
 "panel_manter": "Pertahankan", "panel_manter_proporcao": "Pertahankan rasio",
 "panel_marcar_keyframe_aqui": "Tandai keyframe di sini",
 "panel_margem_fundo": "Margin latar", "panel_margem_fundo_276c": "margin latar",
 "panel_margem_inicial": "Margin awal", "panel_margem_texto_caminho": "margin teks di jalur",
 "panel_mascara_mostra_so_parte_camada_escolha": "Masker hanya menampilkan sebagian lapisan. Pilih cara mulai:",
 "panel_mascara_recorte": "Masker dan potongan",
 "panel_mascara_segue_esta_embaixo_dela_cabecote": "Masker mengikuti yang ada di bawahnya, dari kepala playback sampai akhir klip.",
 "panel_mascaras": "Masker", "panel_material": "Material",
 "panel_material_ambiente": "Material dan lingkungan", "panel_mistura": "Pencampuran",
 "panel_mistura_opacidade": "Pencampuran dan opasitas", "panel_misturar": "Campur",
 "panel_modo_escolhido_acima": "Dengan mode yang dipilih di atas.",
 "panel_mostrar_x_y_z_3d": "Tampilkan X/Y/Z (3D)", "panel_motor_recusou_esta_propriedade": "Mesin menolak properti ini.",
 "panel_move_so_este_grupo_dentro_camada": "Memindahkan hanya grup ini di dalam lapisan.",
 "panel_move_video_ponto_ficar_parado_tela": "Menggeser video agar titiknya diam di layar.",
 "panel_mover_baixo": "Pindah ke bawah", "panel_mover_cima": "Pindah ke atas", "panel_mover_pivo": "pindahkan poros",
 "panel_mover_ponto_curva_tempo": "pindahkan titik kurva waktu",
 "panel_movimento_camera_encontrado": "Gerak kamera ditemukan", "panel_movimento_suave": "Gerak halus",
 "panel_mudo": "Bisu", "panel_nao_ha_outra_camada_possa_recortar": "Tidak ada lapisan lain yang bisa memotong ini.",
 "panel_nao_juntar": "Jangan gabung", "panel_nao_recortar": "Jangan potong",
 "panel_negrito": "Tebal", "panel_neve": "Salju", "panel_nome_preset": "Beri nama presetnya",
 "panel_normal": "Normal",
 "panel_novo_grupo_preenchimento_borda_proprios": "Grup baru (dengan isian dan tepi sendiri)",
 "panel_objetos_aproximam_ou_giram": "Untuk objek yang mendekat atau berputar.",
 "panel_objetos_so_andam_pela_tela": "Untuk objek yang hanya bergerak di layar.",
 "panel_onde_caminhos_cruzam": "Tempat jalur bersilangan", "panel_opacidade": "Opasitas",
 "panel_opacidade_final": "Opasitas akhir", "panel_opacidade_inicial": "Opasitas awal",
 "panel_ordem": "Berurutan", "panel_ordem_aleatoria": "Urutan acak",
 "panel_ordem_copias": "Urutan salinan", "panel_overshoot": "Overshoot",
 "panel_overshoot_9678": "Overshoot ✓", "panel_padrao_aparelho": "Bawaan perangkat",
 "panel_palavra": "Kata", "panel_parada_toque_trilho_animar": "Diam — ketuk ◇ trek untuk menganimasikan",
 "panel_parado_toque_trilho_animar": "Diam — ketuk ◇ trek untuk menganimasikan",
 "panel_paragrafo": "Paragraf", "panel_particulas": "Partikel",
 "panel_particulas_segundo": "Partikel per detik", "panel_passagem": "Lintasan",
 "panel_passar_tras_frente": "Lewat dari belakang ke depan", "panel_pela_forma": "Berdasarkan bentuk",
 "panel_pela_forma_aparece_onde_outra_camada": "Berdasarkan bentuk: muncul di tempat lapisan lain ada. Berdasarkan kecerahan: di tempat ia terang.",
 "panel_pela_forma_invertido": "Berdasarkan bentuk, terbalik", "panel_pelo_brilho": "Berdasarkan kecerahan",
 "panel_pelo_brilho_invertido": "Berdasarkan kecerahan, terbalik", "panel_perpendicular_caminho": "Tegak lurus jalur",
 "panel_petalas": "Kelopak", "panel_pivo_x": "Poros X", "panel_pivo_y": "Poros Y",
 "panel_poeira_luz": "Debu cahaya", "panel_pontas": "Ujung",
 "panel_posicao_x": "Posisi X", "panel_posicao_y": "Posisi Y",
 "panel_preencher": "Isi", "panel_preencher_tudo": "Isi semua",
 "panel_preenchimento": "Isian", "panel_preenchimento_6e8f": "isian",
 "panel_preset_sai_deste_aparelho": "Presetnya keluar dari perangkat ini.",
 "panel_presets": "Preset", "panel_profundidade_z": "Kedalaman Z",
 "panel_proxima_forma": "Bentuk berikutnya",
}

AR = {
 "panel_inverter_sentido": "عكس الاتجاه", "panel_ja_existe_sera_substituido": "موجود بالفعل: سيُستبدل.",
 "panel_juntar_caminhos_grupo": "ضمّ مسارات المجموعة",
 "panel_juntar_precisa_2_caminhos_grupo_use": "الضمّ يحتاج مسارين في المجموعة: استخدم + إضافة بالأعلى.",
 "panel_keyframe_anterior": "الإطار المفتاحي السابق", "panel_lados": "الأضلاع", "panel_largura": "العرض",
 "panel_largura_caixa": "عرض الصندوق", "panel_largura_caixa_4a83": "عرض الصندوق",
 "panel_largura_contorno": "سماكة الإطار", "panel_legendas": "الترجمات",
 "panel_lento_meio": "بطيء في الوسط", "panel_letra": "حرف", "panel_ligada": "مشتغلة",
 "panel_ligar_efeito": "تشغيل المؤثر", "panel_ligar_efeitos": "تشغيل المؤثرات",
 "panel_ligar_todos": "تشغيل الكل", "panel_limite_canto": "حدّ الزاوية",
 "panel_limpar_busca": "مسح البحث", "panel_linear": "خطّي", "panel_linha": "خط",
 "panel_linha_reta": "خط مستقيم", "panel_livre": "حر",
 "panel_losango_trilho_grava_keyframe_linha_acesa": "معيّن المسار يسجّل إطارًا مفتاحيًا للخط المضيء عند المؤشّر.",
 "panel_luz_ambiente": "ضوء المحيط", "panel_maior": "أكبر",
 "panel_mais_opcoes_efeitos": "خيارات أخرى للمؤثرات",
 "panel_mantem_forma_libera_pontos": "يبقي الشكل ويحرّر النقاط.",
 "panel_manter": "إبقاء", "panel_manter_proporcao": "الحفاظ على النسبة",
 "panel_marcar_keyframe_aqui": "ضع إطارًا مفتاحيًا هنا",
 "panel_margem_fundo": "هامش الخلفية", "panel_margem_fundo_276c": "هامش الخلفية",
 "panel_margem_inicial": "الهامش الأولي", "panel_margem_texto_caminho": "هامش النص على المسار",
 "panel_mascara_mostra_so_parte_camada_escolha": "القناع يُظهر جزءًا من الطبقة فقط. اختر كيف تبدأ:",
 "panel_mascara_recorte": "قناع وقطع",
 "panel_mascara_segue_esta_embaixo_dela_cabecote": "القناع يتبع ما تحته، من المؤشّر إلى نهاية المقطع.",
 "panel_mascaras": "الأقنعة", "panel_material": "الخامة",
 "panel_material_ambiente": "الخامة والبيئة", "panel_mistura": "الدمج",
 "panel_mistura_opacidade": "الدمج والعتامة", "panel_misturar": "دمج",
 "panel_modo_escolhido_acima": "بالوضع المختار أعلاه.",
 "panel_mostrar_x_y_z_3d": "إظهار X/Y/Z (3D)", "panel_motor_recusou_esta_propriedade": "رفض المحرّك هذه الخاصية.",
 "panel_move_so_este_grupo_dentro_camada": "يحرّك هذه المجموعة وحدها داخل الطبقة.",
 "panel_move_video_ponto_ficar_parado_tela": "يحرّك الفيديو لتبقى النقطة ثابتة على الشاشة.",
 "panel_mover_baixo": "تحريك للأسفل", "panel_mover_cima": "تحريك للأعلى", "panel_mover_pivo": "تحريك المركز",
 "panel_mover_ponto_curva_tempo": "تحريك نقطة منحنى الزمن",
 "panel_movimento_camera_encontrado": "وُجدت حركة الكاميرا", "panel_movimento_suave": "حركة ناعمة",
 "panel_mudo": "مكتوم", "panel_nao_ha_outra_camada_possa_recortar": "لا توجد طبقة أخرى تستطيع قصّ هذه.",
 "panel_nao_juntar": "عدم الضمّ", "panel_nao_recortar": "عدم القصّ",
 "panel_negrito": "عريض", "panel_neve": "ثلج", "panel_nome_preset": "سمِّ الإعداد",
 "panel_normal": "عادي",
 "panel_novo_grupo_preenchimento_borda_proprios": "مجموعة جديدة (بتعبئة وحدود خاصة)",
 "panel_objetos_aproximam_ou_giram": "للكائنات التي تقترب أو تدور.",
 "panel_objetos_so_andam_pela_tela": "للكائنات التي تتحرك على الشاشة فقط.",
 "panel_onde_caminhos_cruzam": "حيث تتقاطع المسارات", "panel_opacidade": "العتامة",
 "panel_opacidade_final": "العتامة النهائية", "panel_opacidade_inicial": "العتامة الأولية",
 "panel_ordem": "بالترتيب", "panel_ordem_aleatoria": "ترتيب عشوائي",
 "panel_ordem_copias": "ترتيب النسخ", "panel_overshoot": "تجاوز",
 "panel_overshoot_9678": "تجاوز ✓", "panel_padrao_aparelho": "بافتراضي الجهاز",
 "panel_palavra": "كلمة", "panel_parada_toque_trilho_animar": "ثابتة — اضغط ◇ المسار للتحريك",
 "panel_parado_toque_trilho_animar": "ثابت — اضغط ◇ المسار للتحريك",
 "panel_paragrafo": "فقرة", "panel_particulas": "الجسيمات",
 "panel_particulas_segundo": "جسيمات في الثانية", "panel_passagem": "مرور",
 "panel_passar_tras_frente": "المرور من الخلف إلى الأمام", "panel_pela_forma": "بالشكل",
 "panel_pela_forma_aparece_onde_outra_camada": "بالشكل: يظهر حيث توجد الطبقة الأخرى. بالسطوع: حيث تكون مضيئة.",
 "panel_pela_forma_invertido": "بالشكل، معكوس", "panel_pelo_brilho": "بالسطوع",
 "panel_pelo_brilho_invertido": "بالسطوع، معكوس", "panel_perpendicular_caminho": "عمودي على المسار",
 "panel_petalas": "بتلات", "panel_pivo_x": "المركز X", "panel_pivo_y": "المركز Y",
 "panel_poeira_luz": "غبار ضوئي", "panel_pontas": "الأطراف",
 "panel_posicao_x": "الموضع X", "panel_posicao_y": "الموضع Y",
 "panel_preencher": "تعبئة", "panel_preencher_tudo": "تعبئة الكل",
 "panel_preenchimento": "التعبئة", "panel_preenchimento_6e8f": "تعبئة",
 "panel_preset_sai_deste_aparelho": "الإعداد يخرج من هذا الجهاز.",
 "panel_presets": "الإعدادات", "panel_profundidade_z": "العمق Z",
 "panel_proxima_forma": "الشكل التالي",
}

run({"en": EN, "es": ES, "ru": RU, "hi": HI, "id": ID, "ar": AR})
