# Lote 6 de traducoes (103 chaves) — fecha o catalogo.
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from i18n_translate import run

EN = {
 "panel_proximo_keyframe": "Next keyframe", "panel_quadradas": "Square", "panel_quadros_camera_lenta": "Frames in slow motion",
 "panel_raio": "Radius", "panel_raio_externo": "Outer radius", "panel_raio_fundo": "background radius",
 "panel_raio_interno": "Inner radius", "panel_raio_interno_75cf": "inner radius",
 "panel_rampa_ligada_som_video_seguem_mesma": "With the ramp on, sound and video follow the same speed change.",
 "panel_rapido": "Fast", "panel_rastreando": "Tracking…", "panel_rastrear_ponto": "Track a point",
 "panel_rastreio": "Tracking", "panel_recorte_outra_camada": "Cut-out by another layer",
 "panel_redefinir": "Reset", "panel_redefinir_efeito": "Reset effect", "panel_redondas": "Round",
 "panel_redondo": "Round", "panel_redondos": "Rounded", "panel_reforco": "Boost",
 "panel_remover": "Remove", "panel_remover_efeito": "Remove effect", "panel_remover_ponto": "Remove point",
 "panel_repetir_copias": "Repeat (copies)", "panel_repetir_quadro": "Repeat frame",
 "panel_resultado_agora": "Result now: ", "panel_retangulo": "Rectangle",
 "panel_retangulo_meio_camada_pronto_ajustar": "A rectangle in the middle of the layer, ready to adjust.",
 "panel_retas": "Straight", "panel_rotacao": "Rotation", "panel_saida_suave": "Soft out",
 "panel_saida_suave_9ac9": "soft out", "panel_salvar": "Save",
 "panel_salvar_camada_como_preset": "Save the layer's as a preset",
 "panel_salvar_curva_como_preset": "Save curve as a preset", "panel_salvar_desta_camada": "Save this layer's",
 "panel_seco": "Dry", "panel_seguir_posicao": "Follow position",
 "panel_seguir_posicao_tamanho_giro": "Follow position, size and rotation", "panel_selecionar": "Select",
 "panel_selecione_camada_particulas": "Select a particle layer.",
 "panel_selecione_camada_texto": "Select a text layer.",
 "panel_sem_chave_servico_transcricao_use_arquivo": "Without the transcription service key: use a caption file (.srt), or add the key in Settings › Captions. Audio only leaves the device when you tap Generate captions.",
 "panel_sem_rampa": "No ramp", "panel_sintaxe_ok_toque_aplicar": "Syntax ok · tap Apply",
 "panel_sobe": "Up", "panel_solo": "Solo", "panel_soltar_largura_altura": "Unlink width and height",
 "panel_soltar_proporcao": "Unlink the aspect ratio", "panel_som": "Sound", "panel_somar": "Add",
 "panel_sombra": "Shadow", "panel_sombra_x": "shadow x", "panel_sombra_y": "shadow y",
 "panel_sorteado": "Randomised", "panel_sua": "Your", "panel_suave": "Smooth",
 "panel_suavizar": "Smooth", "panel_subtrair": "Subtract", "panel_tamanho": "Size",
 "panel_tamanho_final": "End size", "panel_tamanho_fixo": "Fixed size",
 "panel_tamanho_forma": "shape size", "panel_tamanho_inicial": "Start size",
 "panel_tamanho_texto": "text size", "panel_tempo_velocidade": "Time and speed",
 "panel_texto": "Text", "panel_texto_caminho": "Text on the path",
 "panel_tirar_favoritos": "Remove from favourites", "panel_tirar_keyframe_daqui": "Remove the keyframe from here",
 "panel_toque_curva_criar_ponto_arraste_mudar": "Tap the curve to create a point, drag to change the time, hold to delete.",
 "panel_toque_num_detalhe_contraste_canto_luz": "Tap a high-contrast detail (corner, light, mark). Once chosen, tracking runs on its own.",
 "panel_toque_num_keyframe_timeline_npara_editar": "Tap a keyframe on the timeline\nto edit the curve.",
 "panel_toque_palco_pontos_arraste_curvar": "Tap the stage to place points; drag as you place to bend.",
 "panel_toque_palco_pontos_arraste_curvar_toque": "Tap the stage to place points; drag as you place to bend. Tap the 1st point (or Close path) to close it — the mask only cuts when closed.",
 "panel_toque_preset_guardar_aqui": "Tap a preset's ☆ to save it here.",
 "panel_tracejado": "Dashed",
 "panel_tracejado_aparece_borda_ligue_borda": "The dashes appear on the border: turn Border on.",
 "panel_traco": "Stroke", "panel_transcrever_novo": "Transcribe again", "panel_transformar": "Transform",
 "panel_travar_largura_altura": "Lock width and height", "panel_trecho_escolhido": "Chosen section",
 "panel_triangulo": "Triangle", "panel_trocar_forma": "change shape",
 "panel_trocas_segundo": "Swaps per second",
 "panel_ultimos_10_presets_aplicados_aparecem_aqui": "The last 10 presets you applied show up here.",
 "panel_unir": "Join", "panel_usando_valor_keyframes": " — using the keyframe value",
 "panel_usar_imagem_ambiente_hdr": "Use an environment image (.hdr)",
 "panel_varios_caminhos": "With several paths", "panel_velocidade": "Speed",
 "panel_velocidade_vale_video_audio_nas_outras": "The speed applies to video and audio. On other layers, bring the keyframes closer or further apart to animate faster or slower.",
 "panel_vetor": "Vector", "panel_vivos": "Vivid", "panel_voltar": "Back",
 "panel_voltar_ferramentas": "Back to the tools", "panel_voltar_ferramentas_camada": "Back to the layer tools",
 "panel_voltar_padrao": "Back to default", "panel_volume": "Volume",
 "panel_volume_sobe_desce_forma_natural_sem": "The volume rises and falls naturally, with no hole in the middle of the sound.",
 "panel_x_largura": "x · width", "panel_y_altura": "y · height",
}

ES = {
 "panel_proximo_keyframe": "Keyframe siguiente", "panel_quadradas": "Cuadradas", "panel_quadros_camera_lenta": "Fotogramas en cámara lenta",
 "panel_raio": "Radio", "panel_raio_externo": "Radio externo", "panel_raio_fundo": "radio del fondo",
 "panel_raio_interno": "Radio interno", "panel_raio_interno_75cf": "radio interno",
 "panel_rampa_ligada_som_video_seguem_mesma": "Con la rampa activada, sonido y vídeo siguen el mismo cambio de velocidad.",
 "panel_rapido": "Rápido", "panel_rastreando": "Rastreando…", "panel_rastrear_ponto": "Rastrear un punto",
 "panel_rastreio": "Rastreo", "panel_recorte_outra_camada": "Recorte por otra capa",
 "panel_redefinir": "Restablecer", "panel_redefinir_efeito": "Restablecer efecto", "panel_redondas": "Redondas",
 "panel_redondo": "Redondo", "panel_redondos": "Redondos", "panel_reforco": "Refuerzo",
 "panel_remover": "Quitar", "panel_remover_efeito": "Quitar efecto", "panel_remover_ponto": "Quitar punto",
 "panel_repetir_copias": "Repetir (copias)", "panel_repetir_quadro": "Repetir fotograma",
 "panel_resultado_agora": "Resultado ahora: ", "panel_retangulo": "Rectángulo",
 "panel_retangulo_meio_camada_pronto_ajustar": "Un rectángulo en medio de la capa, listo para ajustar.",
 "panel_retas": "Rectas", "panel_rotacao": "Rotación", "panel_saida_suave": "Salida suave",
 "panel_saida_suave_9ac9": "salida suave", "panel_salvar": "Guardar",
 "panel_salvar_camada_como_preset": "Guardar lo de la capa como preset",
 "panel_salvar_curva_como_preset": "Guardar curva como preset", "panel_salvar_desta_camada": "Guardar lo de esta capa",
 "panel_seco": "Seco", "panel_seguir_posicao": "Seguir posición",
 "panel_seguir_posicao_tamanho_giro": "Seguir posición, tamaño y giro", "panel_selecionar": "Seleccionar",
 "panel_selecione_camada_particulas": "Selecciona una capa de partículas.",
 "panel_selecione_camada_texto": "Selecciona una capa de texto.",
 "panel_sem_chave_servico_transcricao_use_arquivo": "Sin la clave del servicio de transcripción: usa un archivo de subtítulos (.srt), o pon la clave en Ajustes › Subtítulos. El audio solo sale del dispositivo cuando tocas Generar subtítulos.",
 "panel_sem_rampa": "Sin rampa", "panel_sintaxe_ok_toque_aplicar": "Sintaxis ok · toca Aplicar",
 "panel_sobe": "Sube", "panel_solo": "Solo", "panel_soltar_largura_altura": "Soltar ancho y alto",
 "panel_soltar_proporcao": "Soltar la proporción", "panel_som": "Sonido", "panel_somar": "Sumar",
 "panel_sombra": "Sombra", "panel_sombra_x": "sombra x", "panel_sombra_y": "sombra y",
 "panel_sorteado": "Sorteado", "panel_sua": "Tu", "panel_suave": "Suave",
 "panel_suavizar": "Suavizar", "panel_subtrair": "Restar", "panel_tamanho": "Tamaño",
 "panel_tamanho_final": "Tamaño final", "panel_tamanho_fixo": "Tamaño fijo",
 "panel_tamanho_forma": "tamaño de la forma", "panel_tamanho_inicial": "Tamaño inicial",
 "panel_tamanho_texto": "tamaño del texto", "panel_tempo_velocidade": "Tiempo y velocidad",
 "panel_texto": "Texto", "panel_texto_caminho": "Texto en el camino",
 "panel_tirar_favoritos": "Quitar de favoritos", "panel_tirar_keyframe_daqui": "Quitar el keyframe de aquí",
 "panel_toque_curva_criar_ponto_arraste_mudar": "Toca la curva para crear un punto, arrastra para cambiar el tiempo, mantén para borrar.",
 "panel_toque_num_detalhe_contraste_canto_luz": "Toca un detalle con contraste (esquina, luz, marca). Tras elegir, el rastreo corre solo.",
 "panel_toque_num_keyframe_timeline_npara_editar": "Toca un keyframe en la línea de tiempo\npara editar la curva.",
 "panel_toque_palco_pontos_arraste_curvar": "Toca el escenario para poner puntos; arrastra al poner para curvar.",
 "panel_toque_palco_pontos_arraste_curvar_toque": "Toca el escenario para poner puntos; arrastra al poner para curvar. Toca el 1er punto (o Cerrar camino) para cerrar — la máscara solo recorta cerrada.",
 "panel_toque_preset_guardar_aqui": "Toca la ☆ de un preset para guardarlo aquí.",
 "panel_tracejado": "Discontinuo",
 "panel_tracejado_aparece_borda_ligue_borda": "El discontinuo aparece en el borde: activa Borde.",
 "panel_traco": "Trazo", "panel_transcrever_novo": "Transcribir de nuevo", "panel_transformar": "Transformar",
 "panel_travar_largura_altura": "Fijar ancho y alto", "panel_trecho_escolhido": "Tramo elegido",
 "panel_triangulo": "Triángulo", "panel_trocar_forma": "cambiar forma",
 "panel_trocas_segundo": "Cambios por segundo",
 "panel_ultimos_10_presets_aplicados_aparecem_aqui": "Los últimos 10 presets aplicados aparecen aquí.",
 "panel_unir": "Unir", "panel_usando_valor_keyframes": " — usando el valor de los keyframes",
 "panel_usar_imagem_ambiente_hdr": "Usar imagen de entorno (.hdr)",
 "panel_varios_caminhos": "Con varios caminos", "panel_velocidade": "Velocidad",
 "panel_velocidade_vale_video_audio_nas_outras": "La velocidad vale para vídeo y audio. En las otras capas, acerca o aleja los keyframes para animar más rápido o más despacio.",
 "panel_vetor": "Vector", "panel_vivos": "Vivos", "panel_voltar": "Volver",
 "panel_voltar_ferramentas": "Volver a las herramientas", "panel_voltar_ferramentas_camada": "Volver a las herramientas de la capa",
 "panel_voltar_padrao": "Volver al predeterminado", "panel_volume": "Volumen",
 "panel_volume_sobe_desce_forma_natural_sem": "El volumen sube y baja de forma natural, sin hueco en medio del sonido.",
 "panel_x_largura": "x · ancho", "panel_y_altura": "y · alto",
}

RU = {
 "panel_proximo_keyframe": "Следующий ключ", "panel_quadradas": "Квадратные", "panel_quadros_camera_lenta": "Кадры в замедлении",
 "panel_raio": "Радиус", "panel_raio_externo": "Внешний радиус", "panel_raio_fundo": "радиус фона",
 "panel_raio_interno": "Внутренний радиус", "panel_raio_interno_75cf": "внутренний радиус",
 "panel_rampa_ligada_som_video_seguem_mesma": "С включённой рампой звук и видео следуют одному изменению скорости.",
 "panel_rapido": "Быстро", "panel_rastreando": "Слежение…", "panel_rastrear_ponto": "Отследить точку",
 "panel_rastreio": "Слежение", "panel_recorte_outra_camada": "Обрезка другим слоем",
 "panel_redefinir": "Сбросить", "panel_redefinir_efeito": "Сбросить эффект", "panel_redondas": "Круглые",
 "panel_redondo": "Круглый", "panel_redondos": "Скруглённые", "panel_reforco": "Усиление",
 "panel_remover": "Убрать", "panel_remover_efeito": "Убрать эффект", "panel_remover_ponto": "Убрать точку",
 "panel_repetir_copias": "Повтор (копии)", "panel_repetir_quadro": "Повторить кадр",
 "panel_resultado_agora": "Результат сейчас: ", "panel_retangulo": "Прямоугольник",
 "panel_retangulo_meio_camada_pronto_ajustar": "Прямоугольник в середине слоя, готовый к настройке.",
 "panel_retas": "Прямые", "panel_rotacao": "Поворот", "panel_saida_suave": "Мягкий выход",
 "panel_saida_suave_9ac9": "мягкий выход", "panel_salvar": "Сохранить",
 "panel_salvar_camada_como_preset": "Сохранить настройки слоя как пресет",
 "panel_salvar_curva_como_preset": "Сохранить кривую как пресет", "panel_salvar_desta_camada": "Сохранить настройки этого слоя",
 "panel_seco": "Сухой", "panel_seguir_posicao": "Следовать за позицией",
 "panel_seguir_posicao_tamanho_giro": "Следовать за позицией, размером и поворотом", "panel_selecionar": "Выбрать",
 "panel_selecione_camada_particulas": "Выберите слой частиц.",
 "panel_selecione_camada_texto": "Выберите текстовый слой.",
 "panel_sem_chave_servico_transcricao_use_arquivo": "Без ключа сервиса расшифровки: используйте файл субтитров (.srt) или укажите ключ в «Настройки › Субтитры». Звук покидает устройство только когда вы нажимаете «Создать субтитры».",
 "panel_sem_rampa": "Без рампы", "panel_sintaxe_ok_toque_aplicar": "Синтаксис ок · нажмите «Применить»",
 "panel_sobe": "Вверх", "panel_solo": "Solo", "panel_soltar_largura_altura": "Разъединить ширину и высоту",
 "panel_soltar_proporcao": "Разъединить пропорции", "panel_som": "Звук", "panel_somar": "Сложить",
 "panel_sombra": "Тень", "panel_sombra_x": "тень x", "panel_sombra_y": "тень y",
 "panel_sorteado": "Случайно", "panel_sua": "Ваша", "panel_suave": "Плавно",
 "panel_suavizar": "Сгладить", "panel_subtrair": "Вычесть", "panel_tamanho": "Размер",
 "panel_tamanho_final": "Конечный размер", "panel_tamanho_fixo": "Фиксированный размер",
 "panel_tamanho_forma": "размер фигуры", "panel_tamanho_inicial": "Начальный размер",
 "panel_tamanho_texto": "размер текста", "panel_tempo_velocidade": "Время и скорость",
 "panel_texto": "Текст", "panel_texto_caminho": "Текст на контуре",
 "panel_tirar_favoritos": "Убрать из избранного", "panel_tirar_keyframe_daqui": "Убрать ключ отсюда",
 "panel_toque_curva_criar_ponto_arraste_mudar": "Коснитесь кривой, чтобы создать точку; тяните, чтобы изменить время; удерживайте, чтобы удалить.",
 "panel_toque_num_detalhe_contraste_canto_luz": "Коснитесь контрастной детали (угол, свет, метка). После выбора слежение идёт само.",
 "panel_toque_num_keyframe_timeline_npara_editar": "Коснитесь ключа на таймлайне,\nчтобы редактировать кривую.",
 "panel_toque_palco_pontos_arraste_curvar": "Коснитесь сцены, чтобы поставить точки; тяните при постановке, чтобы изогнуть.",
 "panel_toque_palco_pontos_arraste_curvar_toque": "Коснитесь сцены, чтобы поставить точки; тяните при постановке, чтобы изогнуть. Коснитесь 1-й точки (или «Замкнуть контур»), чтобы замкнуть — маска обрезает только замкнутой.",
 "panel_toque_preset_guardar_aqui": "Коснитесь ☆ у пресета, чтобы сохранить его здесь.",
 "panel_tracejado": "Пунктир",
 "panel_tracejado_aparece_borda_ligue_borda": "Пунктир появляется на рамке: включите «Рамка».",
 "panel_traco": "Штрих", "panel_transcrever_novo": "Расшифровать заново", "panel_transformar": "Трансформировать",
 "panel_travar_largura_altura": "Зафиксировать ширину и высоту", "panel_trecho_escolhido": "Выбранный участок",
 "panel_triangulo": "Треугольник", "panel_trocar_forma": "сменить фигуру",
 "panel_trocas_segundo": "Смен в секунду",
 "panel_ultimos_10_presets_aplicados_aparecem_aqui": "Последние 10 применённых пресетов появятся здесь.",
 "panel_unir": "Соединить", "panel_usando_valor_keyframes": " — используется значение ключей",
 "panel_usar_imagem_ambiente_hdr": "Использовать изображение окружения (.hdr)",
 "panel_varios_caminhos": "С несколькими контурами", "panel_velocidade": "Скорость",
 "panel_velocidade_vale_video_audio_nas_outras": "Скорость действует на видео и звук. На других слоях сдвиньте ключи ближе или дальше, чтобы анимировать быстрее или медленнее.",
 "panel_vetor": "Вектор", "panel_vivos": "Яркие", "panel_voltar": "Назад",
 "panel_voltar_ferramentas": "Назад к инструментам", "panel_voltar_ferramentas_camada": "Назад к инструментам слоя",
 "panel_voltar_padrao": "Вернуть по умолчанию", "panel_volume": "Громкость",
 "panel_volume_sobe_desce_forma_natural_sem": "Громкость поднимается и падает естественно, без провала в середине звука.",
 "panel_x_largura": "x · ширина", "panel_y_altura": "y · высота",
}

HI = {
 "panel_proximo_keyframe": "अगला कीफ़्रेम", "panel_quadradas": "वर्गाकार", "panel_quadros_camera_lenta": "स्लो मोशन में फ़्रेम",
 "panel_raio": "त्रिज्या", "panel_raio_externo": "बाहरी त्रिज्या", "panel_raio_fundo": "पृष्ठभूमि की त्रिज्या",
 "panel_raio_interno": "भीतरी त्रिज्या", "panel_raio_interno_75cf": "भीतरी त्रिज्या",
 "panel_rampa_ligada_som_video_seguem_mesma": "रैंप चालू रहने पर आवाज़ और वीडियो एक ही गति-बदलाव का पालन करते हैं।",
 "panel_rapido": "तेज़", "panel_rastreando": "ट्रैक हो रहा है…", "panel_rastrear_ponto": "बिंदु ट्रैक करें",
 "panel_rastreio": "ट्रैकिंग", "panel_recorte_outra_camada": "दूसरी लेयर से कटाई",
 "panel_redefinir": "रीसेट", "panel_redefinir_efeito": "इफ़ेक्ट रीसेट करें", "panel_redondas": "गोल",
 "panel_redondo": "गोल", "panel_redondos": "गोलाकार", "panel_reforco": "बढ़ाव",
 "panel_remover": "हटाएँ", "panel_remover_efeito": "इफ़ेक्ट हटाएँ", "panel_remover_ponto": "बिंदु हटाएँ",
 "panel_repetir_copias": "दोहराएँ (प्रतियाँ)", "panel_repetir_quadro": "फ़्रेम दोहराएँ",
 "panel_resultado_agora": "अभी परिणाम: ", "panel_retangulo": "आयत",
 "panel_retangulo_meio_camada_pronto_ajustar": "लेयर के बीच एक आयत, समायोजन के लिए तैयार।",
 "panel_retas": "सीधी", "panel_rotacao": "घुमाव", "panel_saida_suave": "सौम्य निकास",
 "panel_saida_suave_9ac9": "सौम्य निकास", "panel_salvar": "सहेजें",
 "panel_salvar_camada_como_preset": "लेयर की सेटिंग प्रीसेट के रूप में सहेजें",
 "panel_salvar_curva_como_preset": "कर्व को प्रीसेट के रूप में सहेजें", "panel_salvar_desta_camada": "इस लेयर की सेटिंग सहेजें",
 "panel_seco": "सूखा", "panel_seguir_posicao": "स्थिति का पालन करें",
 "panel_seguir_posicao_tamanho_giro": "स्थिति, आकार और घुमाव का पालन करें", "panel_selecionar": "चुनें",
 "panel_selecione_camada_particulas": "कण लेयर चुनें।",
 "panel_selecione_camada_texto": "टेक्स्ट लेयर चुनें।",
 "panel_sem_chave_servico_transcricao_use_arquivo": "ट्रांसक्रिप्शन सेवा की कुंजी बिना: कैप्शन फ़ाइल (.srt) इस्तेमाल करें, या कुंजी सेटिंग्स › कैप्शन में डालें। कैप्शन बनाएँ दबाने पर ही ऑडियो डिवाइस से बाहर जाता है।",
 "panel_sem_rampa": "रैंप बिना", "panel_sintaxe_ok_toque_aplicar": "सिंटैक्स ठीक · लागू करें दबाएँ",
 "panel_sobe": "ऊपर", "panel_solo": "Solo", "panel_soltar_largura_altura": "चौड़ाई और ऊँचाई अलग करें",
 "panel_soltar_proporcao": "अनुपात अलग करें", "panel_som": "आवाज़", "panel_somar": "जोड़ें",
 "panel_sombra": "छाया", "panel_sombra_x": "छाया x", "panel_sombra_y": "छाया y",
 "panel_sorteado": "बेतरतीब", "panel_sua": "आपकी", "panel_suave": "सौम्य",
 "panel_suavizar": "सौम्य करें", "panel_subtrair": "घटाएँ", "panel_tamanho": "आकार",
 "panel_tamanho_final": "अंतिम आकार", "panel_tamanho_fixo": "स्थिर आकार",
 "panel_tamanho_forma": "आकृति का आकार", "panel_tamanho_inicial": "शुरुआती आकार",
 "panel_tamanho_texto": "टेक्स्ट का आकार", "panel_tempo_velocidade": "समय और गति",
 "panel_texto": "टेक्स्ट", "panel_texto_caminho": "पथ पर टेक्स्ट",
 "panel_tirar_favoritos": "पसंदीदा से हटाएँ", "panel_tirar_keyframe_daqui": "यहाँ से कीफ़्रेम हटाएँ",
 "panel_toque_curva_criar_ponto_arraste_mudar": "बिंदु बनाने के लिए कर्व दबाएँ, समय बदलने के लिए खींचें, मिटाने के लिए दबाए रखें।",
 "panel_toque_num_detalhe_contraste_canto_luz": "किसी कंट्रास्ट वाली जगह (कोना, रोशनी, निशान) को दबाएँ। चुनने के बाद ट्रैकिंग अपने आप चलती है।",
 "panel_toque_num_keyframe_timeline_npara_editar": "कर्व संपादित करने के लिए\nटाइमलाइन पर कीफ़्रेम दबाएँ।",
 "panel_toque_palco_pontos_arraste_curvar": "बिंदु रखने के लिए स्टेज दबाएँ; रखते समय खींचकर मोड़ें।",
 "panel_toque_palco_pontos_arraste_curvar_toque": "बिंदु रखने के लिए स्टेज दबाएँ; रखते समय खींचकर मोड़ें। बंद करने के लिए पहला बिंदु (या पथ बंद करें) दबाएँ — मास्क बंद होने पर ही काटता है।",
 "panel_toque_preset_guardar_aqui": "प्रीसेट को यहाँ सहेजने के लिए उसका ☆ दबाएँ।",
 "panel_tracejado": "बिंदुदार",
 "panel_tracejado_aparece_borda_ligue_borda": "बिंदुदार किनारे पर दिखता है: किनारा चालू करें।",
 "panel_traco": "स्ट्रोक", "panel_transcrever_novo": "फिर से ट्रांसक्राइब करें", "panel_transformar": "रूपांतरित करें",
 "panel_travar_largura_altura": "चौड़ाई और ऊँचाई लॉक करें", "panel_trecho_escolhido": "चुना हुआ हिस्सा",
 "panel_triangulo": "त्रिभुज", "panel_trocar_forma": "आकृति बदलें",
 "panel_trocas_segundo": "प्रति सेकंड बदलाव",
 "panel_ultimos_10_presets_aplicados_aparecem_aqui": "आपके लगाए आख़िरी 10 प्रीसेट यहाँ दिखेंगे।",
 "panel_unir": "जोड़ें", "panel_usando_valor_keyframes": " — कीफ़्रेम का मान इस्तेमाल हो रहा है",
 "panel_usar_imagem_ambiente_hdr": "वातावरण छवि इस्तेमाल करें (.hdr)",
 "panel_varios_caminhos": "कई पथों के साथ", "panel_velocidade": "गति",
 "panel_velocidade_vale_video_audio_nas_outras": "गति वीडियो और ऑडियो पर लागू होती है। दूसरी लेयर पर, तेज़ या धीमा एनिमेट करने के लिए कीफ़्रेम पास या दूर लाएँ।",
 "panel_vetor": "वेक्टर", "panel_vivos": "चटक", "panel_voltar": "वापस",
 "panel_voltar_ferramentas": "औज़ारों पर वापस", "panel_voltar_ferramentas_camada": "लेयर के औज़ारों पर वापस",
 "panel_voltar_padrao": "डिफ़ॉल्ट पर वापस", "panel_volume": "वॉल्यूम",
 "panel_volume_sobe_desce_forma_natural_sem": "वॉल्यूम स्वाभाविक रूप से ऊपर-नीचे होता है, आवाज़ के बीच में गड्ढा नहीं।",
 "panel_x_largura": "x · चौड़ाई", "panel_y_altura": "y · ऊँचाई",
}

ID = {
 "panel_proximo_keyframe": "Keyframe berikutnya", "panel_quadradas": "Persegi", "panel_quadros_camera_lenta": "Frame dalam gerak lambat",
 "panel_raio": "Jari-jari", "panel_raio_externo": "Jari-jari luar", "panel_raio_fundo": "jari-jari latar",
 "panel_raio_interno": "Jari-jari dalam", "panel_raio_interno_75cf": "jari-jari dalam",
 "panel_rampa_ligada_som_video_seguem_mesma": "Dengan ramp menyala, suara dan video mengikuti perubahan kecepatan yang sama.",
 "panel_rapido": "Cepat", "panel_rastreando": "Melacak…", "panel_rastrear_ponto": "Lacak sebuah titik",
 "panel_rastreio": "Pelacakan", "panel_recorte_outra_camada": "Potongan oleh lapisan lain",
 "panel_redefinir": "Setel ulang", "panel_redefinir_efeito": "Setel ulang efek", "panel_redondas": "Bulat",
 "panel_redondo": "Bulat", "panel_redondos": "Membulat", "panel_reforco": "Penguatan",
 "panel_remover": "Buang", "panel_remover_efeito": "Buang efek", "panel_remover_ponto": "Buang titik",
 "panel_repetir_copias": "Ulangi (salinan)", "panel_repetir_quadro": "Ulangi frame",
 "panel_resultado_agora": "Hasil sekarang: ", "panel_retangulo": "Persegi panjang",
 "panel_retangulo_meio_camada_pronto_ajustar": "Sebuah persegi panjang di tengah lapisan, siap disesuaikan.",
 "panel_retas": "Lurus", "panel_rotacao": "Rotasi", "panel_saida_suave": "Keluar halus",
 "panel_saida_suave_9ac9": "keluar halus", "panel_salvar": "Simpan",
 "panel_salvar_camada_como_preset": "Simpan milik lapisan sebagai preset",
 "panel_salvar_curva_como_preset": "Simpan kurva sebagai preset", "panel_salvar_desta_camada": "Simpan milik lapisan ini",
 "panel_seco": "Kering", "panel_seguir_posicao": "Ikuti posisi",
 "panel_seguir_posicao_tamanho_giro": "Ikuti posisi, ukuran, dan putaran", "panel_selecionar": "Pilih",
 "panel_selecione_camada_particulas": "Pilih lapisan partikel.",
 "panel_selecione_camada_texto": "Pilih lapisan teks.",
 "panel_sem_chave_servico_transcricao_use_arquivo": "Tanpa kunci layanan transkripsi: pakai berkas teks (.srt), atau isi kuncinya di Pengaturan › Teks. Audio hanya keluar dari perangkat saat Anda mengetuk Buat teks.",
 "panel_sem_rampa": "Tanpa ramp", "panel_sintaxe_ok_toque_aplicar": "Sintaks ok · ketuk Terapkan",
 "panel_sobe": "Naik", "panel_solo": "Solo", "panel_soltar_largura_altura": "Lepas lebar dan tinggi",
 "panel_soltar_proporcao": "Lepas rasionya", "panel_som": "Suara", "panel_somar": "Jumlahkan",
 "panel_sombra": "Bayangan", "panel_sombra_x": "bayangan x", "panel_sombra_y": "bayangan y",
 "panel_sorteado": "Acak", "panel_sua": "Milik Anda", "panel_suave": "Halus",
 "panel_suavizar": "Haluskan", "panel_subtrair": "Kurangi", "panel_tamanho": "Ukuran",
 "panel_tamanho_final": "Ukuran akhir", "panel_tamanho_fixo": "Ukuran tetap",
 "panel_tamanho_forma": "ukuran bentuk", "panel_tamanho_inicial": "Ukuran awal",
 "panel_tamanho_texto": "ukuran teks", "panel_tempo_velocidade": "Waktu dan kecepatan",
 "panel_texto": "Teks", "panel_texto_caminho": "Teks di jalur",
 "panel_tirar_favoritos": "Hapus dari favorit", "panel_tirar_keyframe_daqui": "Hapus keyframe dari sini",
 "panel_toque_curva_criar_ponto_arraste_mudar": "Ketuk kurva untuk membuat titik, seret untuk mengubah waktu, tahan untuk menghapus.",
 "panel_toque_num_detalhe_contraste_canto_luz": "Ketuk detail berkontras (sudut, cahaya, tanda). Setelah dipilih, pelacakan berjalan sendiri.",
 "panel_toque_num_keyframe_timeline_npara_editar": "Ketuk keyframe di timeline\nuntuk mengedit kurvanya.",
 "panel_toque_palco_pontos_arraste_curvar": "Ketuk panggung untuk menaruh titik; seret saat menaruh untuk melengkungkan.",
 "panel_toque_palco_pontos_arraste_curvar_toque": "Ketuk panggung untuk menaruh titik; seret saat menaruh untuk melengkungkan. Ketuk titik pertama (atau Tutup jalur) untuk menutup — masker hanya memotong saat tertutup.",
 "panel_toque_preset_guardar_aqui": "Ketuk ☆ sebuah preset untuk menyimpannya di sini.",
 "panel_tracejado": "Putus-putus",
 "panel_tracejado_aparece_borda_ligue_borda": "Garis putus-putus muncul di tepi: nyalakan Tepi.",
 "panel_traco": "Goresan", "panel_transcrever_novo": "Transkripsikan lagi", "panel_transformar": "Transformasikan",
 "panel_travar_largura_altura": "Kunci lebar dan tinggi", "panel_trecho_escolhido": "Potongan terpilih",
 "panel_triangulo": "Segitiga", "panel_trocar_forma": "ganti bentuk",
 "panel_trocas_segundo": "Pergantian per detik",
 "panel_ultimos_10_presets_aplicados_aparecem_aqui": "10 preset terakhir yang Anda pakai muncul di sini.",
 "panel_unir": "Gabung", "panel_usando_valor_keyframes": " — memakai nilai keyframe",
 "panel_usar_imagem_ambiente_hdr": "Pakai gambar lingkungan (.hdr)",
 "panel_varios_caminhos": "Dengan beberapa jalur", "panel_velocidade": "Kecepatan",
 "panel_velocidade_vale_video_audio_nas_outras": "Kecepatan berlaku untuk video dan audio. Di lapisan lain, dekatkan atau jauhkan keyframe untuk beranimasi lebih cepat atau lambat.",
 "panel_vetor": "Vektor", "panel_vivos": "Menyala", "panel_voltar": "Kembali",
 "panel_voltar_ferramentas": "Kembali ke alat", "panel_voltar_ferramentas_camada": "Kembali ke alat lapisan",
 "panel_voltar_padrao": "Kembali ke bawaan", "panel_volume": "Volume",
 "panel_volume_sobe_desce_forma_natural_sem": "Volumenya naik-turun secara alami, tanpa lubang di tengah suara.",
 "panel_x_largura": "x · lebar", "panel_y_altura": "y · tinggi",
}

AR = {
 "panel_proximo_keyframe": "الإطار المفتاحي التالي", "panel_quadradas": "مربّعة", "panel_quadros_camera_lenta": "إطارات في الحركة البطيئة",
 "panel_raio": "نصف القطر", "panel_raio_externo": "نصف القطر الخارجي", "panel_raio_fundo": "نصف قطر الخلفية",
 "panel_raio_interno": "نصف القطر الداخلي", "panel_raio_interno_75cf": "نصف القطر الداخلي",
 "panel_rampa_ligada_som_video_seguem_mesma": "مع تشغيل المنحدر، يتبع الصوت والفيديو نفس تغيّر السرعة.",
 "panel_rapido": "سريع", "panel_rastreando": "جارٍ التتبّع…", "panel_rastrear_ponto": "تتبّع نقطة",
 "panel_rastreio": "التتبّع", "panel_recorte_outra_camada": "قصّ بواسطة طبقة أخرى",
 "panel_redefinir": "إعادة الضبط", "panel_redefinir_efeito": "إعادة ضبط المؤثر", "panel_redondas": "مستديرة",
 "panel_redondo": "مستدير", "panel_redondos": "مستديرة", "panel_reforco": "تقوية",
 "panel_remover": "إزالة", "panel_remover_efeito": "إزالة المؤثر", "panel_remover_ponto": "إزالة النقطة",
 "panel_repetir_copias": "تكرار (نسخ)", "panel_repetir_quadro": "تكرار الإطار",
 "panel_resultado_agora": "النتيجة الآن: ", "panel_retangulo": "مستطيل",
 "panel_retangulo_meio_camada_pronto_ajustar": "مستطيل في وسط الطبقة، جاهز للضبط.",
 "panel_retas": "مستقيمة", "panel_rotacao": "الدوران", "panel_saida_suave": "خروج ناعم",
 "panel_saida_suave_9ac9": "خروج ناعم", "panel_salvar": "حفظ",
 "panel_salvar_camada_como_preset": "حفظ إعدادات الطبقة كإعداد جاهز",
 "panel_salvar_curva_como_preset": "حفظ المنحنى كإعداد جاهز", "panel_salvar_desta_camada": "حفظ إعدادات هذه الطبقة",
 "panel_seco": "جافّ", "panel_seguir_posicao": "تتبّع الموضع",
 "panel_seguir_posicao_tamanho_giro": "تتبّع الموضع والحجم والدوران", "panel_selecionar": "تحديد",
 "panel_selecione_camada_particulas": "حدّد طبقة جسيمات.",
 "panel_selecione_camada_texto": "حدّد طبقة نص.",
 "panel_sem_chave_servico_transcricao_use_arquivo": "بلا مفتاح خدمة التفريغ: استخدم ملف ترجمة (.srt)، أو ضع المفتاح في الإعدادات › الترجمات. لا يخرج الصوت من الجهاز إلا عند الضغط على «إنشاء الترجمات».",
 "panel_sem_rampa": "بلا منحدر", "panel_sintaxe_ok_toque_aplicar": "الصياغة سليمة · اضغط تطبيق",
 "panel_sobe": "يصعد", "panel_solo": "Solo", "panel_soltar_largura_altura": "فصل العرض عن الارتفاع",
 "panel_soltar_proporcao": "فصل النسبة", "panel_som": "الصوت", "panel_somar": "جمع",
 "panel_sombra": "ظلّ", "panel_sombra_x": "الظل x", "panel_sombra_y": "الظل y",
 "panel_sorteado": "عشوائي", "panel_sua": "خاصتك", "panel_suave": "ناعم",
 "panel_suavizar": "تنعيم", "panel_subtrair": "طرح", "panel_tamanho": "الحجم",
 "panel_tamanho_final": "الحجم النهائي", "panel_tamanho_fixo": "حجم ثابت",
 "panel_tamanho_forma": "حجم الشكل", "panel_tamanho_inicial": "الحجم الأولي",
 "panel_tamanho_texto": "حجم النص", "panel_tempo_velocidade": "الزمن والسرعة",
 "panel_texto": "نص", "panel_texto_caminho": "نص على المسار",
 "panel_tirar_favoritos": "إزالة من المفضّلة", "panel_tirar_keyframe_daqui": "إزالة الإطار المفتاحي من هنا",
 "panel_toque_curva_criar_ponto_arraste_mudar": "اضغط المنحنى لإنشاء نقطة، اسحب لتغيير الزمن، اضغط مطوّلًا للمحو.",
 "panel_toque_num_detalhe_contraste_canto_luz": "اضغط تفصيلًا عالي التباين (زاوية، ضوء، علامة). بعد الاختيار يعمل التتبّع وحده.",
 "panel_toque_num_keyframe_timeline_npara_editar": "اضغط إطارًا مفتاحيًا على الخط الزمني\nلتحرير المنحنى.",
 "panel_toque_palco_pontos_arraste_curvar": "اضغط المسرح لوضع النقاط؛ اسحب أثناء الوضع للانحناء.",
 "panel_toque_palco_pontos_arraste_curvar_toque": "اضغط المسرح لوضع النقاط؛ اسحب أثناء الوضع للانحناء. اضغط النقطة الأولى (أو «إغلاق المسار») للإغلاق — القناع يقصّ فقط وهو مغلق.",
 "panel_toque_preset_guardar_aqui": "اضغط ☆ على إعداد جاهز لحفظه هنا.",
 "panel_tracejado": "متقطّع",
 "panel_tracejado_aparece_borda_ligue_borda": "يظهر المتقطّع على الحدود: شغّل الحدود.",
 "panel_traco": "خط", "panel_transcrever_novo": "إعادة التفريغ", "panel_transformar": "تحويل",
 "panel_travar_largura_altura": "قفل العرض والارتفاع", "panel_trecho_escolhido": "المقطع المختار",
 "panel_triangulo": "مثلّث", "panel_trocar_forma": "تغيير الشكل",
 "panel_trocas_segundo": "تبديلات في الثانية",
 "panel_ultimos_10_presets_aplicados_aparecem_aqui": "آخر 10 إعدادات جاهزة طبّقتها تظهر هنا.",
 "panel_unir": "ضمّ", "panel_usando_valor_keyframes": " — يُستخدم قيمة الإطارات المفتاحية",
 "panel_usar_imagem_ambiente_hdr": "استخدام صورة محيط (.hdr)",
 "panel_varios_caminhos": "بمسارات متعددة", "panel_velocidade": "السرعة",
 "panel_velocidade_vale_video_audio_nas_outras": "السرعة تنطبق على الفيديو والصوت. على الطبقات الأخرى، قرّب الإطارات المفتاحية أو باعدها للتحريك أسرع أو أبطأ.",
 "panel_vetor": "متجه", "panel_vivos": "زاهية", "panel_voltar": "رجوع",
 "panel_voltar_ferramentas": "العودة إلى الأدوات", "panel_voltar_ferramentas_camada": "العودة إلى أدوات الطبقة",
 "panel_voltar_padrao": "العودة إلى الافتراضي", "panel_volume": "مستوى الصوت",
 "panel_volume_sobe_desce_forma_natural_sem": "يرتفع مستوى الصوت وينخفض بشكل طبيعي، بلا فراغ في وسط الصوت.",
 "panel_x_largura": "x · العرض", "panel_y_altura": "y · الارتفاع",
}

run({"en": EN, "es": ES, "ru": RU, "hi": HI, "id": ID, "ar": AR})
