package com.aurea.aurea.editor

import android.app.Application
import android.graphics.Bitmap
import android.media.MediaMetadataRetriever
import android.os.SystemClock
import android.os.ParcelFileDescriptor
import androidx.compose.ui.test.junit4.createComposeRule
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.viewmodel.compose.viewModel
import androidx.test.platform.app.InstrumentationRegistry
import com.aurea.aurea.editor.panels.effectTypeId
import com.aurea.aurea.engine.CommandBatch
import com.aurea.aurea.engine.EngineStatus
import com.aurea.aurea.engine.PerfStats
import com.aurea.aurea.engine.PodLayout
import com.aurea.aurea.state.EditorStore
import com.aurea.aurea.ui.theme.AureaTheme
import org.junit.Assert.*
import org.junit.Rule
import org.junit.Test
import java.io.File
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.abs

/** Color-path diagnosis using the exact Full HD fixture generated by the soak.
 * Fresh instrumentation process restores normal decoder selection on next run. */
class DiagnosticVideoPathColorDeviceTest {
    @get:Rule val compose = createComposeRule()

    @Test fun compareHardwareGlWithReadableSoftwarePlanes() = comparePaths(false)
    @Test fun compareTheSoakTileBlurGlowChainAcrossDecoderPaths() = comparePaths(true)
    @Test fun compareForcedSoftwareFallbackWithReadableSoftwarePlanes() = comparePaths(false, true)
    @Test fun compareForcedSoftwareFallbackTileBlurGlowWithReadableSoftwarePlanes() = comparePaths(true, true)

    private fun comparePaths(withEffects: Boolean, softwareFallback: Boolean = false) {
        val instrumentation = InstrumentationRegistry.getInstrumentation()
        val context = instrumentation.targetContext
        check(context.packageName == "com.aurea.aurea.uitest")
        org.junit.Assume.assumeTrue(InstrumentationRegistry.getArguments().getString("aureaStress") == "true")
        val forcedSoftwareFallback = ParcelFileDescriptor.AutoCloseInputStream(
            instrumentation.uiAutomation.executeShellCommand("getprop debug.aurea.force_sw_fallback")
        ).bufferedReader().use { it.readText().trim() } == "1"
        assertEquals("Select the requested diagnostic before launching this fresh instrumentation process", softwareFallback, forcedSoftwareFallback)
        val source = context.filesDir.listFiles().orEmpty().filter { it.name.startsWith("stress-sustained-") }
            .sortedByDescending { it.name }.map { File(it, "fixture-1080p.mp4") }.firstOrNull { it.length() > 1000 }
        assertNotNull("Run the Full HD soak fixture generation before this diagnostic", source)
        val fixture = checkNotNull(source)
        val folderName = (if (softwareFallback) "video-path-software-fallback" else "video-path-color") + (if (withEffects) "-effects" else "")
        val folder = File(context.filesDir, folderName).apply { mkdirs() }
        val report = File(folder, "progress.txt")
        report.writeText("${if (softwareFallback) "REGRESSION forced software fallback planes" else "DIAGNOSTIC hardware GL"} versus readable software planes; effects=$withEffects; fixture=${fixture.absolutePath}\n")
        val media = MediaMetadataRetriever()
        try {
            media.setDataSource(fixture.absolutePath)
            for ((name, key) in listOf("width" to MediaMetadataRetriever.METADATA_KEY_VIDEO_WIDTH,
                "height" to MediaMetadataRetriever.METADATA_KEY_VIDEO_HEIGHT,
                "standard" to MediaMetadataRetriever.METADATA_KEY_COLOR_STANDARD,
                "range" to MediaMetadataRetriever.METADATA_KEY_COLOR_RANGE,
                "transfer" to MediaMetadataRetriever.METADATA_KEY_COLOR_TRANSFER)) {
                report.appendText("metadata $name=${media.extractMetadata(key)}\n")
            }
        } finally { media.release() }
        lateinit var store: EditorStore
        var ready = false
        compose.setContent {
            store = viewModel(factory = ViewModelProvider.AndroidViewModelFactory.getInstance(context.applicationContext as Application))
            ready = true
            AureaTheme { EditorScreen(store) }
        }
        compose.waitUntil(30000) { ready && store.engineReady }
        compose.runOnIdle { store.newProject(1920, 1080, 30f, "Video color path diagnostic") }
        compose.waitUntil(30000) { store.project.title == "Video color path diagnostic" && !store.projectOperationBusy }
        val engine = store.engineForStress
        val id = engine.importVideo(fixture.absolutePath, "Same Full HD fixture")
        assertTrue(id > 0)
        compose.runOnIdle {
            store.setCompositionDuration(90)
            engine.beginCommandBatch()
            val cmd = CommandBatch(engine)
            cmd.setLayerTimeRange(id, 0, 90)
            if (withEffects) {
                cmd.setPosition(id, 160f, 90f, 0f)
                cmd.setScale(id, .105f, .105f, .105f)
                cmd.setRotation(id, 0f, 0f, 90f)
                cmd.addEffect(id, effectTypeId("aurea.stylize.motion_tile"))
                cmd.addEffect(id, effectTypeId("aurea.blur.gaussian"))
                cmd.addEffect(id, effectTypeId("aurea.light.glow"))
            } else {
                cmd.setPosition(id, 960f, 540f, 0f)
                cmd.setScale(id, 1f, 1f, 1f)
            }
            assertTrue(engine.submitCommands() > 0)
        }
        if (withEffects) {
            val rows = ByteBuffer.allocateDirect(3 * 32).order(ByteOrder.nativeOrder())
            val names = ByteBuffer.allocateDirect(2048)
            compose.waitUntil(15000) { engine.queryLayerEffects(id, rows, 3, names) == 3 }
            compose.runOnIdle {
                engine.beginCommandBatch()
                val cmd = CommandBatch(engine)
                val tile = rows.getInt(0)
                cmd.setEffectParam(id, tile, 3, 150f); cmd.setEffectParam(id, tile, 4, 150f)
                cmd.setEffectParam(id, tile, 5, 1f); cmd.setEffectParam(id, tile, 10, 70f)
                cmd.setEffectParam(id, rows.getInt(32), 0, 3f)
                cmd.setEffectParam(id, rows.getInt(64), 0, 20f)
                assertEquals(6, engine.submitCommands())
            }
        }
        val statusBuffer = ByteBuffer.allocateDirect(PodLayout.STATUS_BYTES).order(ByteOrder.nativeOrder())
        fun seek() {
            compose.runOnIdle { store.pause(); store.seek(45) }
            val began = SystemClock.elapsedRealtime()
            while (true) {
                assertTrue(engine.readStatus(statusBuffer))
                val state = EngineStatus().also { it.readFrom(statusBuffer) }
                if (!state.playing && state.playhead == 45L) break
                assertTrue("Native seek did not finish", SystemClock.elapsedRealtime() - began < 30000)
                Thread.sleep(100)
            }
        }
        fun capture(label: String): ByteArray {
            val buffer = ByteBuffer.allocateDirect(320 * 180 * 4)
            val dimensions = IntArray(2)
            val count = engine.captureFrame(320, buffer, dimensions)
            assertEquals(230400, count)
            assertArrayEquals(intArrayOf(320, 180), dimensions)
            val rgba = ByteArray(count).also { buffer.rewind(); buffer.get(it) }
            var cyan = 0; var magenta = 0
            for (offset in rgba.indices step 4) {
                val r = rgba[offset].toInt() and 255
                val g = rgba[offset + 1].toInt() and 255
                val b = rgba[offset + 2].toInt() and 255
                if (g > 170 && b > 170 && r < 90) cyan++
                if (r > 170 && b > 170 && g < 90) magenta++
            }
            report.appendText("$label visible video cyan=$cyan magenta=$magenta\n")
            assertTrue("The decoded video must be visible, not an empty successful capture: $label", cyan > 1 && magenta > 1)
            File(folder, "$label.rgba").writeBytes(rgba)
            val bitmap = Bitmap.createBitmap(320, 180, Bitmap.Config.ARGB_8888)
            try {
                bitmap.copyPixelsFromBuffer(ByteBuffer.wrap(rgba))
                File(folder, "$label.png").outputStream().use { bitmap.compress(Bitmap.CompressFormat.PNG, 100, it) }
            } finally { bitmap.recycle() }
            val perfBuffer = ByteBuffer.allocateDirect(PerfStats.BYTES).order(ByteOrder.nativeOrder())
            assertTrue(engine.readPerf(perfBuffer))
            val perf = PerfStats.read(perfBuffer)
            report.appendText("$label hardware=${perf.hardwareDecoder} decoder=${perf.decoder} stale=${perf.staleFrames} decodedBytes=${perf.decodedCacheBytes}\n")
            assertEquals("The diagnostic must exercise the requested decoder path: $label", label.startsWith("hardware-"), perf.hardwareDecoder)
            return rgba
        }
        fun compare(label: String, a: ByteArray, b: ByteArray) {
            val maximum = a.indices.maxOf { abs((a[it].toInt() and 255) - (b[it].toInt() and 255)) }
            val changed = a.indices.count { abs((a[it].toInt() and 255) - (b[it].toInt() and 255)) > 4 }
            report.appendText("$label maximum=$maximum changedAbove4=$changed/${a.size}\n")
            if (softwareFallback) assertTrue("Software fallback must preserve the readable YUV color conversion: $label max=$maximum", maximum <= 4)
        }
        seek()
        val initialLabel = if (softwareFallback) "software-fallback-planes" else "hardware-gl"
        val initial = capture(initialLabel)
        compare("initial path repeat", initial, capture("$initialLabel-repeat"))
        val project = File(folder, "same-video.aurea")
        assertEquals(0, engine.saveProject(project.absolutePath))
        engine.useReadableVideoPlanes()
        assertEquals(0, engine.loadProject(project.absolutePath))
        seek()
        val software = capture("software-planar")
        compare("software repeat", software, capture("software-planar-repeat"))
        compare("initial path versus software planar", initial, software)
        report.appendText("COMPLETE; forced software fallback enforces max channel difference <=4; native decoder log records the selected reader path\n")
    }
}
