"""Build the offline catalog; Portuguese strings are stable UI lookup keys."""
import csv
import json
import unicodedata
from pathlib import Path

root = Path(__file__).resolve().parent.parent
rows = list(csv.reader((root / 'tool/languages.tsv').read_text(encoding='utf-8').splitlines(), delimiter='\t'))
codes = rows[0][1:]
catalog = {}
def celula(v):
    # No TSV a quebra de linha vive como os dois caracteres `\n`;
    # a chave do dicionario tem de ser a string Dart de verdade.
    return v.replace('\\n', '\n')

for row in rows[1:]:
    assert len(row) == len(codes) + 1 and all(row), row
    row = [celula(v) for v in row]
    assert row[0] not in catalog, row[0]
    catalog[row[0]] = dict(zip(codes, row[1:]))
for source, values in list(catalog.items()):
    plain = ''.join(c for c in unicodedata.normalize('NFD', source) if unicodedata.category(c) != 'Mn')
    catalog.setdefault(plain, values)

def dart(value):
    return json.dumps(value, ensure_ascii=False).replace('$', r'\$')

lines = ['// Generated by tool/generate_languages.py. Edit tool/languages.tsv.',
         'const appTranslations = <String, Map<String, String>>{']
for source, values in catalog.items():
    lines.append(f'  {dart(source)}: {{' + ', '.join(f'{dart(code)}: {dart(value)}' for code, value in values.items()) + '},')
lines.append('};\n')
(root / 'lib/src/core/l10n/translations.dart').write_text('\n'.join(lines), encoding='utf-8')
print(f'{len(rows)-1} labels, {len(codes)} translations each; {len(catalog)} keys with spelling aliases.')
