"""Share Android's particle control labels, ranges and parameter IDs with iOS."""
from pathlib import Path
import re

root = Path(__file__).resolve().parent.parent
source = (root / 'android/app/src/main/java/com/aurea/aurea/editor/panels/ParticlesPanel.kt').read_text(encoding='utf-8')
enum = (root / 'engine/include/aurea/timeline/Layer.hpp').read_text(encoding='utf-8').split('enum class ParticleParam : u32 {')[1].split('};')[0]
enum = re.sub(r'//[^\n]*', '', enum)
names = [x.strip().split('=')[0].strip() for x in enum.split(',') if x.strip()]
ids = {name: index for index, name in enumerate(names)}
controls = {}
groups = list(re.finditer(r'Group\(stringResource\(R.string.(\w+)\)\)', source))
prefix = r'\(store, stringResource\(R.string.(\w+)\), P\.(\w+)'
for match in re.finditer(r'(Dim|Pct|Angle|Toggle)' + prefix + r', p([^\n]*)', source):
    kind, label, name, tail = match.groups()
    if name in controls:
        continue
    numbers = [float(n) for n in re.findall(r'(-?\d+(?:\.\d+)?)f', tail)]
    if kind == 'Dim':
        if len(numbers) < 3: continue
        lo, hi = numbers[1:3]
    elif kind == 'Angle': lo, hi = numbers[:2] if len(numbers) >= 2 else (-360, 360)
    else: lo, hi = 0, numbers[0] if numbers else 1
    group = next((g.group(1) for g in reversed(groups) if g.start() < match.start()), 'particular_group_emitter')
    controls[name] = [ids[name], label, group, lo, hi, kind == 'Toggle', [], 'negate = true' in tail]
for match in re.finditer(r'Choice' + prefix + r'\)\s*\{\s*listOf\((.*?)\)\s*\}', source, re.S):
    label, name, options = match.groups()
    labels = re.findall(r'R.string.(\w+)', options)
    group = next((g.group(1) for g in reversed(groups) if g.start() < match.start()), 'particular_group_emitter')
    controls[name] = [ids[name], label, group, 0, max(1, len(labels) - 1), False, labels, False]
missing = set(names[:-1]) - controls.keys()
if missing:
    raise RuntimeError(f'Missing particle controls: {sorted(missing)}')
lines = ['// Generated by tools/ios_particle_controls.py from the current Android panel.',
         'import Foundation',
         'struct ParticleControl: Identifiable {',
         '    var id: Int; var label: String; var group: String; var low: Float; var high: Float',
         '    var toggle: Bool; var choices: [String]; var negate: Bool',
         '}', 'let particleControls: [ParticleControl] = [']
for name, (index, label, group, lo, hi, toggle, options, negate) in controls.items():
    choices = ', '.join('"' + s + '"' for s in options)
    lines.append(f'    ParticleControl(id: {index}, label: "{label}", group: "{group}", low: {lo}, high: {hi}, toggle: {str(toggle).lower()}, choices: [{choices}], negate: {str(negate).lower()}), // {name}')
lines.append(']')
(root / 'engine/platform/ios/app/ParticleControls.swift').write_text('\n'.join(lines) + '\n', encoding='utf-8')
print(f'Generated {len(controls)} controls, matching every engine parameter.')
