// =============================================================================
//  Aurea / platform / ios / app / AureaStrings.swift
//
//  GERADO de android/app/src/main/res/values/strings.xml (pt-BR) e
//  values-en/strings.xml (ingles) por tools/_ios_strings.py — nao editar a mao
//  sem trazer a mesma mudanca para o catalogo do Android.
//
//  As CHAVES SAO AS MESMAS do Android (`home_tab_projects`, `editor_desfazer`...).
//  Isso e deliberado: um texto novo entra nos dois sistemas pelo mesmo nome,
//  e o catalogo continua sendo um so (o do Android e a fonte).
//
//  O Android tem SETE idiomas (values/ = pt-BR + ar, en, es, hi, id, ru). Esta
//  entrega traz pt-BR e ingles — os outros cinco saem do mesmo XML, pela mesma
//  extracao, quando o dono quiser (ver README).
//
//  Formato: o catalogo usa o printf do Android (%1$s, %2$d); aqui os
//  especificadores foram convertidos para os do Foundation (%1$@, %2$ld).
// =============================================================================
import Foundation

/// Um idioma do app. O que o dono escolhe nos Ajustes; o padrao segue o sistema.
enum AureaLanguage: String, CaseIterable, Identifiable {
    case pt = "pt-BR"
    case en = "en"

    var id: String { rawValue }

    /// Rotulo do seletor. Nome do idioma NO idioma — nao traduzido.
    var label: String {
        switch self {
        case .pt: return "Português (Brasil)"
        case .en: return "English"
        }
    }

    /// Idioma do sistema quando ele e um dos que temos; senao pt-BR (o idioma
    /// em que o app foi escrito, e o mesmo padrao do Android).
    static var systemDefault: AureaLanguage {
        for code in Locale.preferredLanguages {
            if code.hasPrefix("en") { return .en }
            if code.hasPrefix("pt") { return .pt }
        }
        return .pt
    }
}

/// O catalogo. `t()` traduz; chave desconhecida devolve a propria chave, o que
/// aparece na tela em vez de um texto vazio — um furo de traducao fica visivel.
enum AureaText {
    /// Idioma em vigor. O modelo observa e redesenha quando muda.
    static var language: AureaLanguage = .systemDefault

    static func t(_ key: String) -> String {
        let table = language == .en ? en : pt
        return table[key] ?? pt[key] ?? key
    }

    static func t(_ key: String, _ args: CVarArg...) -> String {
        String(format: t(key), arguments: args)
    }

    private static let pt: [String: String] = [
        "common_cancel": "Cancelar",
        "common_delete": "Excluir",
        "common_duplicate": "Duplicar",
        "common_remove": "Remover",
        "common_rename": "Renomear",
        "common_save": "Salvar",
        "common_search": "Buscar",
        "common_open": "Abrir",
        "common_irreversible": "Não dá para desfazer.",
        "home_tab_start": "Início",
        "home_tab_projects": "Projetos",
        "home_tab_settings": "Ajustes",
        "home_title_start": "Início",
        "home_title_projects": "Projetos",
        "home_search_projects": "Buscar projetos",
        "home_search_hint": "Procurar pelo nome",
        "home_new_project": "Novo projeto",
        "home_no_projects": "Nenhum projeto ainda",
        "home_no_projects_hint": "Toque em Novo projeto para começar.",
        "home_no_results": "Nenhum projeto encontrado",
        "home_sort_recent": "Mais recentes",
        "home_sort_name": "Nome (A-Z)",
        "home_sort_longest": "Mais longos",
        "home_sort_created": "Criação",
        "home_sort_size": "Tamanho",
        "home_project_count": "%1$d projeto",
        "home_continue": "Continuar editando",
        "home_continue_action": "Continuar",
        "home_import_media": "Importar mídia",
        "home_empty_hint": "Seus projetos aparecem aqui, com a miniatura do que você fez.",
        "home_selected_count": "%1$d selecionados",
        "home_select_all": "Selecionar todos",
        "home_clear_selection": "Limpar seleção",
        "home_clear_search": "Limpar busca",
        "editor_abrir": "Abrir",
        "editor_exportar": "Exportar",
        "editor_desfazer": "Desfazer",
        "editor_refazer": "Refazer",
        "editor_reproduzir": "Reproduzir",
        "editor_pausar": "Pausar",
        "editor_voltar_editor": "Voltar ao editor",
        "editor_mais": "Mais",
        "editor_projeto_cbe9": "Projeto",
        "editor_previa": "Prévia",
        "editor_tela_cheia": "Tela cheia",
        "editor_sair_tela_cheia": "Sair da tela cheia",
        "editor_adicionar_camada": "Adicionar camada",
        "editor_nenhum": "Nenhum",
        "editor_projetos": "Projetos",
        "editor_quadro_atras_segure_inicio": "Um quadro atrás · segure para o início",
        "editor_quadro_frente_segure_fim": "Um quadro à frente · segure para o fim",
        "editor_keyframe_anterior_segure_inicio": "Keyframe anterior · segure para o início",
        "editor_proximo_keyframe_segure_fim": "Próximo keyframe · segure para o fim",
        "editor_repeticao_ligada_segure_desligar": "Repetição ligada · segure para desligar",
        "editor_reproduzir_segure_repetir": "Reproduzir · segure para repetir",
        "editor_desligar_som_segure_volume": "Desligar o som · segure para o volume",
        "editor_som_desligado_toque_ligar_segure_volume": "Som desligado · toque para ligar, segure para o volume",
        "editor_voltar_composicao_principal": "Voltar para a composição principal",
        "editor_toque_num_objeto_tela_editar": "Toque num objeto na tela para editar.",
        "editor_selecione_menos_duas_camadas": "Selecione ao menos duas camadas",
        "editor_selecionar_todas_camadas": "Selecionar todas as camadas",
        "editor_limpar_selecao": "Limpar seleção",
        "editor_cancelar_selecao": "Cancelar seleção",
        "editor_camada_bloqueada": "Camada bloqueada",
        "editor_camada_bloqueada_desbloqueie_editar": "Camada bloqueada: desbloqueie para editar",
        "editor_agrupar": "Agrupar",
        "editor_desagrupar": "Desagrupar",
        "editor_duplicar_camada": "Duplicar camada",
        "editor_excluir_camada": "Excluir camada",
        "editor_copiar_camada": "Copiar camada",
        "editor_copiar_efeitos": "Copiar efeitos",
        "editor_colar_efeitos": "Colar efeitos",
        "editor_copiar_estilo": "Copiar estilo",
        "editor_colar_estilo": "Colar estilo",
        "editor_copiar_keyframes_cabecote": "Copiar keyframes do cabeçote",
        "editor_colar_keyframes_cabecote": "Colar keyframes no cabeçote",
        "editor_dividir_cabecote": "Dividir no cabeçote",
        "editor_mais_acoes_camada": "Mais ações da camada",
        "editor_mesclagem_opacidade_efeitos_cores": "Mesclagem, opacidade, efeitos e cores",
        "editor_estilo_efeitos": "Estilo e efeitos",
        "editor_keyframes": "Keyframes",
        "editor_aparar_inicio_cabecote": "Aparar o início no cabeçote",
        "editor_aparar_fim_cabecote": "Aparar o fim no cabeçote",
        "editor_alinhar_esquerda_tela": "Alinhar à esquerda da tela",
        "editor_alinhar_direita_tela": "Alinhar à direita da tela",
        "editor_alinhar_topo_tela": "Alinhar ao topo da tela",
        "editor_alinhar_base_tela": "Alinhar à base da tela",
        "editor_centralizar_horizontal": "Centralizar na horizontal",
        "editor_centralizar_vertical": "Centralizar na vertical",
        "editor_distribuir_horizontal_vaos_iguais": "Distribuir na horizontal (vãos iguais)",
        "editor_distribuir_vertical_vaos_iguais": "Distribuir na vertical (vãos iguais)",
        "editor_agrupar_camadas_escolhidas": "Agrupar as camadas escolhidas",
        "editor_trazer_frente": "Trazer para a frente",
        "editor_enviar_tras": "Enviar para trás",
        "editor_mostrar_camada": "Mostrar camada",
        "editor_ocultar_camada": "Ocultar camada",
        "editor_bloquear_camada": "Bloquear camada",
        "editor_desbloquear_camada": "Desbloquear camada",
        "editor_renomear": "Renomear",
        "editor_etiqueta": "Etiqueta",
        "editor_guia_nao_exporta": "Guia (não exporta)",
        "editor_camada_ajuste": "Camada de ajuste",
        "editor_solo": "Solo",
        "editor_extrair_audio": "Extrair o áudio",
        "editor_remover_espacos_vazios": "Remover espaços vazios",
        "editor_buscar_camadas": "Buscar camadas…",
        "editor_nome_ou_texto_camada": "Nome ou texto da camada",
        "sh_dock_transform": "Transformar",
        "sh_dock_effects": "Efeitos",
        "sh_dock_opacity_blend": "Opacidade e mistura",
        "sh_dock_edit_text": "Editar texto",
        "sh_dock_edit_shape": "Editar forma",
        "sh_dock_mask": "Máscara",
        "sh_dock_particles": "Partículas",
        "sh_dock_presets": "Presets",
        "sh_dock_environment": "Ambiente",
        "sh_dock_captions": "Legendas",
        "sh_dock_color_fill": "Cor e preenchimento",
        "sh_dock_edit_vector": "Editar vetor",
        "panel_transformar": "Transformar",
        "panel_ajustar": "Ajustar",
        "panel_largura": "Largura",
        "panel_altura": "Altura",
        "panel_centro": "Centro",
        "panel_preencher": "Preencher",
        "panel_voltar_padrao": "Voltar ao padrão",
        "panel_adicionar_expressao": "Adicionar expressão",
        "panel_deslize_mover_camada": "Deslize para mover a camada",
        "panel_deslize_mover_toque_z_profundidade": "Deslize para mover · toque em Z para profundidade",
        "panel_esconder_x_y_z_3d": "Esconder X/Y/Z (3D)",
        "panel_mostrar_x_y_z_3d": "Mostrar X/Y/Z (3D)",
        "panel_adicionar_efeito": "Adicionar efeito",
        "panel_efeitos_camada": "Efeitos da camada",
        "panel_este_efeito_nao_tem_ajustes": "Este efeito não tem ajustes.",
        "panel_opacidade": "Opacidade",
        "panel_redefinir": "Redefinir",
        "panel_remover_efeito": "Remover efeito",
        "panel_mover_cima": "Mover para cima",
        "panel_mover_baixo": "Mover para baixo",
        "panel_ligar_efeito": "Ligar efeito",
        "panel_desligar_efeito": "Desligar efeito",
        "panel_material": "Material",
        "panel_cor": "Cor",
        "panel_intensidade": "Intensidade",
        "panel_exposicao": "Exposição",
        "panel_luz_ambiente": "Luz do ambiente",
        "panel_ambiente_do_objeto": "Ambiente do objeto",
        "panel_do_projeto": "Do projeto",
        "panel_proprio": "Próprio",
        "panel_estudio_neutro": "Estúdio neutro",
        "panel_imagem_ambiente": "Imagem de ambiente ✓",
        "panel_trocar_imagem": "Trocar imagem",
        "panel_alinhamento": "Alinhamento",
        "pn_text3d_title": "Texto 3D",
        "pn_text3d_placeholder": "Digite o texto",
        "pn_depth": "Profundidade",
        "pn_env_light_hint": "A luz do ambiente ilumina e reflete em todos os objetos 3D do projeto.",
        "editor_formato": "Formato",
        "editor_resolucao": "Resolução",
        "editor_qualidade": "Qualidade",
        "editor_duracao": "Duração",
        "editor_quadros_segundo": "Quadros por segundo",
        "editor_h_264_abre_qualquer_aparelho_rede": "H.264: abre em qualquer aparelho e rede social.",
        "editor_hevc_arquivo_menor_mesma_qualidade_alguns": "HEVC: arquivo menor, mesma qualidade. Alguns aparelhos antigos não reproduzem.",
        "editor_mantenha_aurea_aberto_ate_terminar": "Mantenha o Aurea aberto até terminar.",
        "editor_video_pronto": "Vídeo pronto",
        "editor_salvando_galeria": "Salvando na galeria…",
        "editor_salvando": "Salvando…",
        "editor_tamanho_estimado": "Tamanho estimado",
        "editor_video": "Vídeo",
        "editor_nenhum_app_abre_video": "Nenhum app abre vídeo",
        "editor_abrir": "Abrir",
        "sh_export_progress": "Quadro %1$s de %2$s · %3$s q/s · falta %4$s",
        "sh_export_above_device": "%1$s: acima do que este aparelho exporta.",
        "sh_export_fps_from_project": "%1$s (do projeto)",
        "unit_megabyte": "%1$d MB",
        "unit_gigabyte": "%1$s GB",
        "aspect_hint_tv": "YouTube / TV",
        "aspect_hint_reels": "Reels / TikTok",
        "aspect_hint_feed": "Feed",
        "aspect_hint_instagram": "Instagram",
        "aspect_hint_classic": "Clássico",
        "editor_nome_camada": "Nome da camada",
        "settings_group_language": "Idioma",
        "settings_language": "Idioma do app",
        "settings_language_system": "Padrão do sistema",
        "settings_group_device": "Desempenho",
        "settings_device_auto": "Otimização automática",
        "settings_device_auto_note": "Na primeira abertura o app mede o aparelho e escolhe o preview, o número de workers e o teto de export. Fica configurado para as próximas vezes.",
        "settings_group_general": "Geral",
        "settings_dev_tools": "Ferramentas de desenvolvedor",
        "settings_dev_on": "Ferramentas de desenvolvedor ligadas",
        "settings_dev_off": "Ferramentas de desenvolvedor desligadas",
        "settings_technology": "Tecnologia",
        "editor_cor": "Cor",
        "editor_foto": "Foto",
        "editor_musica_ou_som": "Música ou som",
        "editor_escala": "Escala",
        "editor_rotacao": "Rotação",
        "editor_rastreio": "Rastreio",
        "panel_digite_texto": "Digite o texto",
        "home_title_settings": "Ajustes",
        "settings_aspect": "Proporção",
        "settings_resolution": "Resolução",
        "settings_fps": "Quadros por segundo",
        "panel_este_efeito_saiu_catalogo_ele_nao": "Este efeito saiu do catálogo. Ele não desenha mais; apague pelo ⋯.",
        "panel_cor_brilho_metalico_rugosidade_vem_arquivo": "Cor, brilho metálico e rugosidade vêm do arquivo do modelo (glTF, FBX).",
    ]

    private static let en: [String: String] = [
        "common_cancel": "Cancel",
        "common_delete": "Delete",
        "common_duplicate": "Duplicate",
        "common_remove": "Remove",
        "common_rename": "Rename",
        "common_save": "Save",
        "common_search": "Search",
        "common_open": "Open",
        "common_irreversible": "This can't be undone.",
        "home_tab_start": "Home",
        "home_tab_projects": "Projects",
        "home_tab_settings": "Settings",
        "home_title_start": "Home",
        "home_title_projects": "Projects",
        "home_search_projects": "Search projects",
        "home_search_hint": "Search by name",
        "home_new_project": "New project",
        "home_no_projects": "No projects yet",
        "home_no_projects_hint": "Tap New project to start.",
        "home_no_results": "No projects found",
        "home_sort_recent": "Recent",
        "home_sort_name": "Name (A-Z)",
        "home_sort_longest": "Longest",
        "home_sort_created": "Created",
        "home_sort_size": "Size",
        "home_project_count": "%1$d project",
        "home_continue": "Continue editing",
        "home_continue_action": "Continue",
        "home_import_media": "Import media",
        "home_empty_hint": "Your projects show up here, with a thumbnail of what you made.",
        "home_selected_count": "%1$d selected",
        "home_select_all": "Select all",
        "home_clear_selection": "Clear selection",
        "home_clear_search": "Clear search",
        "editor_abrir": "Open",
        "editor_exportar": "Export",
        "editor_desfazer": "Undo",
        "editor_refazer": "Redo",
        "editor_reproduzir": "Play",
        "editor_pausar": "Pause",
        "editor_voltar_editor": "Back to the editor",
        "editor_mais": "More",
        "editor_projeto_cbe9": "Project",
        "editor_previa": "Preview",
        "editor_tela_cheia": "Full screen",
        "editor_sair_tela_cheia": "Exit full screen",
        "editor_adicionar_camada": "Add layer",
        "editor_nenhum": "None",
        "editor_projetos": "Projects",
        "editor_quadro_atras_segure_inicio": "One frame back · hold for the start",
        "editor_quadro_frente_segure_fim": "One frame forward · hold for the end",
        "editor_keyframe_anterior_segure_inicio": "Previous keyframe · hold for the start",
        "editor_proximo_keyframe_segure_fim": "Next keyframe · hold for the end",
        "editor_repeticao_ligada_segure_desligar": "Repeat on · hold to turn off",
        "editor_reproduzir_segure_repetir": "Play · hold to repeat",
        "editor_desligar_som_segure_volume": "Mute · hold for volume",
        "editor_som_desligado_toque_ligar_segure_volume": "Sound off · tap to turn on, hold for volume",
        "editor_voltar_composicao_principal": "Back to the main composition",
        "editor_toque_num_objeto_tela_editar": "Tap an object on screen to edit it.",
        "editor_selecione_menos_duas_camadas": "Select at least two layers",
        "editor_selecionar_todas_camadas": "Select all layers",
        "editor_limpar_selecao": "Clear selection",
        "editor_cancelar_selecao": "Clear selection",
        "editor_camada_bloqueada": "Layer locked",
        "editor_camada_bloqueada_desbloqueie_editar": "Layer locked: unlock to edit",
        "editor_agrupar": "Group",
        "editor_desagrupar": "Ungroup",
        "editor_duplicar_camada": "Duplicate layer",
        "editor_excluir_camada": "Delete layer",
        "editor_copiar_camada": "Copy layer",
        "editor_copiar_efeitos": "Copy effects",
        "editor_colar_efeitos": "Paste effects",
        "editor_copiar_estilo": "Copy style",
        "editor_colar_estilo": "Paste style",
        "editor_copiar_keyframes_cabecote": "Copy keyframes from the playhead",
        "editor_colar_keyframes_cabecote": "Paste keyframes at the playhead",
        "editor_dividir_cabecote": "Split at the playhead",
        "editor_mais_acoes_camada": "More layer actions",
        "editor_mesclagem_opacidade_efeitos_cores": "Blending, opacity, effects and colours",
        "editor_estilo_efeitos": "Style and effects",
        "editor_keyframes": "Keyframes",
        "editor_aparar_inicio_cabecote": "Trim the start at the playhead",
        "editor_aparar_fim_cabecote": "Trim the end at the playhead",
        "editor_alinhar_esquerda_tela": "Align to left of screen",
        "editor_alinhar_direita_tela": "Align to right of screen",
        "editor_alinhar_topo_tela": "Align to top of screen",
        "editor_alinhar_base_tela": "Align to bottom of screen",
        "editor_centralizar_horizontal": "Centre horizontally",
        "editor_centralizar_vertical": "Centre vertically",
        "editor_distribuir_horizontal_vaos_iguais": "Distribute horizontally (equal gaps)",
        "editor_distribuir_vertical_vaos_iguais": "Distribute vertically (equal gaps)",
        "editor_agrupar_camadas_escolhidas": "Group the selected layers",
        "editor_trazer_frente": "Bring forward",
        "editor_enviar_tras": "Send backward",
        "editor_mostrar_camada": "Show layer",
        "editor_ocultar_camada": "Hide layer",
        "editor_bloquear_camada": "Lock layer",
        "editor_desbloquear_camada": "Unlock layer",
        "editor_renomear": "Rename",
        "editor_etiqueta": "Label",
        "editor_guia_nao_exporta": "Guide (not exported)",
        "editor_camada_ajuste": "Adjustment layer",
        "editor_solo": "Solo",
        "editor_extrair_audio": "Extract the audio",
        "editor_remover_espacos_vazios": "Remove empty gaps",
        "editor_buscar_camadas": "Search layers…",
        "editor_nome_ou_texto_camada": "Layer name or text",
        "sh_dock_transform": "Transform",
        "sh_dock_effects": "Effects",
        "sh_dock_opacity_blend": "Opacity and blending",
        "sh_dock_edit_text": "Edit text",
        "sh_dock_edit_shape": "Edit shape",
        "sh_dock_mask": "Mask",
        "sh_dock_particles": "Particles",
        "sh_dock_presets": "Presets",
        "sh_dock_environment": "Environment",
        "sh_dock_captions": "Captions",
        "sh_dock_color_fill": "Color and fill",
        "sh_dock_edit_vector": "Edit vector",
        "panel_transformar": "Transform",
        "panel_ajustar": "Adjust",
        "panel_largura": "Width",
        "panel_altura": "Height",
        "panel_centro": "Centre",
        "panel_preencher": "Fill",
        "panel_voltar_padrao": "Back to default",
        "panel_adicionar_expressao": "Add expression",
        "panel_deslize_mover_camada": "Slide to move the layer",
        "panel_deslize_mover_toque_z_profundidade": "Slide to move · tap Z for depth",
        "panel_esconder_x_y_z_3d": "Hide X/Y/Z (3D)",
        "panel_mostrar_x_y_z_3d": "Show X/Y/Z (3D)",
        "panel_adicionar_efeito": "Add effect",
        "panel_efeitos_camada": "Layer effects",
        "panel_este_efeito_nao_tem_ajustes": "This effect has no settings.",
        "panel_opacidade": "Opacity",
        "panel_redefinir": "Reset",
        "panel_remover_efeito": "Remove effect",
        "panel_mover_cima": "Move up",
        "panel_mover_baixo": "Move down",
        "panel_ligar_efeito": "Turn the effect on",
        "panel_desligar_efeito": "Turn the effect off",
        "panel_material": "Material",
        "panel_cor": "Colour",
        "panel_intensidade": "Strength",
        "panel_exposicao": "Exposure",
        "panel_luz_ambiente": "Ambient light",
        "panel_ambiente_do_objeto": "Object environment",
        "panel_do_projeto": "From the project",
        "panel_proprio": "Own",
        "panel_estudio_neutro": "Neutral studio",
        "panel_imagem_ambiente": "Environment image ✓",
        "panel_trocar_imagem": "Change image",
        "panel_alinhamento": "Alignment",
        "pn_text3d_title": "3D Text",
        "pn_text3d_placeholder": "Type the text",
        "pn_depth": "Depth",
        "pn_env_light_hint": "The environment light lights and reflects on every 3D object in the project.",
        "editor_formato": "Format",
        "editor_resolucao": "Resolution",
        "editor_qualidade": "Quality",
        "editor_duracao": "Duration",
        "editor_quadros_segundo": "Frames per second",
        "editor_h_264_abre_qualquer_aparelho_rede": "H.264: opens on any device and social network.",
        "editor_hevc_arquivo_menor_mesma_qualidade_alguns": "HEVC: smaller file, same quality. Some older devices can't play it.",
        "editor_mantenha_aurea_aberto_ate_terminar": "Keep Aurea open until it finishes.",
        "editor_video_pronto": "Video ready",
        "editor_salvando_galeria": "Saving to the gallery…",
        "editor_salvando": "Saving…",
        "editor_tamanho_estimado": "Estimated size",
        "editor_video": "Video",
        "editor_nenhum_app_abre_video": "No app opens video",
        "editor_abrir": "Open",
        "sh_export_progress": "Frame %1$s of %2$s · %3$s fps · %4$s left",
        "sh_export_above_device": "%1$s: above what this device exports.",
        "sh_export_fps_from_project": "%1$s (from the project)",
        "unit_megabyte": "%1$d MB",
        "unit_gigabyte": "%1$s GB",
        "aspect_hint_tv": "YouTube / TV",
        "aspect_hint_reels": "Reels / TikTok",
        "aspect_hint_feed": "Feed",
        "aspect_hint_instagram": "Instagram",
        "aspect_hint_classic": "Classic",
        "editor_nome_camada": "Layer name",
        "settings_group_language": "Language",
        "settings_language": "App language",
        "settings_language_system": "System default",
        "settings_group_device": "Performance",
        "settings_device_auto": "Automatic optimisation",
        "settings_device_auto_note": "On first launch the app measures the device and picks preview scale, worker count and the export ceiling. It stays configured from then on.",
        "settings_group_general": "General",
        "settings_dev_tools": "Developer tools",
        "settings_dev_on": "Developer tools on",
        "settings_dev_off": "Developer tools off",
        "settings_technology": "Technology",
        "editor_cor": "Colour",
        "editor_foto": "Photo",
        "editor_musica_ou_som": "Music or sound",
        "editor_escala": "Scale",
        "editor_rotacao": "Rotation",
        "editor_rastreio": "Tracking",
        "panel_digite_texto": "Type the text",
        "home_title_settings": "Settings",
        "settings_aspect": "Aspect ratio",
        "settings_resolution": "Resolution",
        "settings_fps": "Frames per second",
        "panel_este_efeito_saiu_catalogo_ele_nao": "This effect left the catalogue. It no longer draws; delete it with ⋯.",
        "panel_cor_brilho_metalico_rugosidade_vem_arquivo": "Colour, metallic shine and roughness come from the model file (glTF, FBX).",
    ]
}
