// Generated by tools/ios_particle_controls.py from the current Android panel.
import Foundation
struct ParticleControl: Identifiable {
    var id: Int; var label: String; var group: String; var low: Float; var high: Float
    var toggle: Bool; var choices: [String]; var negate: Bool
}
let particleControls: [ParticleControl] = [
    ParticleControl(id: 3, label: "particular_radius", group: "particular_group_emitter", low: 0.0, high: 2000.0, toggle: false, choices: [], negate: false), // EmitterRadius
    ParticleControl(id: 11, label: "panel_particulas_segundo", group: "particular_group_emitter", low: 0.0, high: 6000.0, toggle: false, choices: [], negate: false), // Rate
    ParticleControl(id: 13, label: "panel_duracao_cada", group: "particular_group_emitter", low: 0.05, high: 10.0, toggle: false, choices: [], negate: false), // Lifetime
    ParticleControl(id: 15, label: "panel_velocidade", group: "particular_group_physics", low: 0.0, high: 4000.0, toggle: false, choices: [], negate: false), // Speed
    ParticleControl(id: 31, label: "panel_gravidade", group: "particular_group_physics", low: -4000.0, high: 4000.0, toggle: false, choices: [], negate: true), // GravityY
    ParticleControl(id: 33, label: "world_resistance", group: "particular_group_physics", low: 0.0, high: 10.0, toggle: false, choices: [], negate: false), // Drag
    ParticleControl(id: 26, label: "panel_tamanho_inicial", group: "particular_group_particle", low: 0.1, high: 120.0, toggle: false, choices: [], negate: false), // StartSize
    ParticleControl(id: 27, label: "panel_tamanho_final", group: "particular_group_particle", low: 0.0, high: 120.0, toggle: false, choices: [], negate: false), // EndSize
    ParticleControl(id: 28, label: "panel_opacidade", group: "particular_group_particle", low: 0, high: 1, toggle: false, choices: [], negate: false), // StartOpacity
    ParticleControl(id: 21, label: "particular_shape", group: "particular_group_particle", low: 0, high: 3, toggle: false, choices: ["particular_shape_circle", "particular_shape_square", "particular_shape_streak", "particular_shape_soft"], negate: false), // ParticleType
]
