# Real shared CPU inference; source and trained weights are pinned separately.
include(FetchContent)
set(NCNN_VULKAN OFF CACHE BOOL "" FORCE)
set(NCNN_OPENMP OFF CACHE BOOL "" FORCE)
set(NCNN_INT8 OFF CACHE BOOL "" FORCE)
set(NCNN_DISABLE_EXCEPTION OFF CACHE BOOL "" FORCE)
set(NCNN_BUILD_TOOLS OFF CACHE BOOL "" FORCE)
set(NCNN_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(NCNN_BUILD_BENCHMARK OFF CACHE BOOL "" FORCE)
set(NCNN_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(NCNN_INSTALL_SDK OFF CACHE BOOL "" FORCE)
set(NCNN_SHARED_LIB OFF CACHE BOOL "" FORCE)
set(NCNN_AVX512 OFF CACHE BOOL "" FORCE)
set(NCNN_AVX512VNNI OFF CACHE BOOL "" FORCE)
set(NCNN_AVX512BF16 OFF CACHE BOOL "" FORCE)
set(NCNN_AVX512FP16 OFF CACHE BOOL "" FORCE)
FetchContent_Declare(aurea_ncnn
    URL https://codeload.github.com/Tencent/ncnn/zip/305837fd4a722ebc47c5d72e72d8ec9ae970e932
    URL_HASH SHA256=1a25fea794145d2326974ebcbc4558292c77b741be0a239a522484b59bef61d6
)
FetchContent_GetProperties(aurea_ncnn)
if(NOT aurea_ncnn_POPULATED)
    FetchContent_Populate(aurea_ncnn)
    # Only this pinned graph and the CPU tensor/convolution helpers are needed.
    # Keep enum positions generated by upstream, with unused registry slots null.
    set(ai_layers input split convolution prelu pixelshuffle interp binaryop
        packing cast padding crop flatten reshape innerproduct gemm scale bias
        relu clip sigmoid mish hardswish tanh)
    file(STRINGS "${aurea_ncnn_SOURCE_DIR}/src/CMakeLists.txt" ai_layer_lines REGEX "^ncnn_add_layer\\(")
    foreach(line IN LISTS ai_layer_lines)
        string(REGEX REPLACE "^ncnn_add_layer\\(([A-Za-z0-9_]+).*" "\\1" name "${line}")
        string(TOLOWER "${name}" name)
        if(name IN_LIST ai_layers)
            set(WITH_LAYER_${name} ON CACHE BOOL "" FORCE)
        else()
            set(WITH_LAYER_${name} OFF CACHE BOOL "" FORCE)
        endif()
    endforeach()
    add_subdirectory("${aurea_ncnn_SOURCE_DIR}" "${aurea_ncnn_BINARY_DIR}" EXCLUDE_FROM_ALL)
endif()
if(MSVC)
    target_compile_options(ncnn PRIVATE /MP4)
endif()
set(ai_model_dir "${CMAKE_CURRENT_SOURCE_DIR}/assets/ai")
set(ai_model_cpp "${CMAKE_CURRENT_BINARY_DIR}/generated/AiModel.cpp")
file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/generated")
add_custom_command(OUTPUT "${ai_model_cpp}"
    COMMAND "${CMAKE_COMMAND}" "-DMODEL_DIR=${ai_model_dir}" "-DOUTPUT=${ai_model_cpp}"
            -P "${CMAKE_CURRENT_SOURCE_DIR}/cmake/EmbedUpscaleModel.cmake"
    DEPENDS "${ai_model_dir}/realesr-animevideov3.bin"
            "${ai_model_dir}/realesr-animevideov3-x2.param"
            "${ai_model_dir}/realesr-animevideov3-x4.param"
            "${CMAKE_CURRENT_SOURCE_DIR}/cmake/EmbedUpscaleModel.cmake"
    VERBATIM)
target_sources(aurea_core PRIVATE src/ai/Upscaler.cpp "${ai_model_cpp}")
target_link_libraries(aurea_core PRIVATE ncnn)
# Model/vector allocation failures are translated to Status at this boundary.
# The rest of the shared core retains its existing no-exceptions contract.
if(MSVC)
    set_source_files_properties(src/ai/Upscaler.cpp PROPERTIES COMPILE_OPTIONS /EHsc)
else()
    set_source_files_properties(src/ai/Upscaler.cpp PROPERTIES COMPILE_OPTIONS -fexceptions)
endif()

