# Shared inference; source, shader compiler and trained weights are pinned.
include(FetchContent)
if(APPLE)
    set(ai_vulkan_default OFF) # Metal builds do not ship a Vulkan loader.
else()
    set(ai_vulkan_default ON)
endif()
option(AUREA_AI_VULKAN "Enable ncnn Vulkan inference with CPU fallback" ${ai_vulkan_default})
set(NCNN_VULKAN ${AUREA_AI_VULKAN} CACHE BOOL "" FORCE)
set(NCNN_OPENMP OFF CACHE BOOL "" FORCE)
set(NCNN_INT8 OFF CACHE BOOL "" FORCE)
set(NCNN_DISABLE_EXCEPTION OFF CACHE BOOL "" FORCE)
# ncnn publishes -fno-rtti to its consumers when enabled. That would silently
# remove RTTI from aurea_core while ObjC++/other bridge targets still require
# typeinfo for its public polymorphic interfaces (e.g. VideoSourceFactory).
set(NCNN_DISABLE_RTTI OFF CACHE BOOL "" FORCE)
set(NCNN_BUILD_TOOLS OFF CACHE BOOL "" FORCE)
set(NCNN_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(NCNN_BUILD_BENCHMARK OFF CACHE BOOL "" FORCE)
set(NCNN_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(NCNN_INSTALL_SDK OFF CACHE BOOL "" FORCE)
set(NCNN_SHARED_LIB OFF CACHE BOOL "" FORCE)
set(NCNN_AVX512 OFF CACHE BOOL "" FORCE)
set(NCNN_AVX512VNNI OFF CACHE BOOL "" FORCE)
set(NCNN_AVX512BF16 OFF CACHE BOOL "" FORCE)
set(NCNN_AVX512FP16 OFF CACHE BOOL "" FORCE)
FetchContent_Declare(aurea_ncnn
    URL https://codeload.github.com/Tencent/ncnn/zip/305837fd4a722ebc47c5d72e72d8ec9ae970e932
    URL_HASH SHA256=1a25fea794145d2326974ebcbc4558292c77b741be0a239a522484b59bef61d6
)
FetchContent_GetProperties(aurea_ncnn)
if(NOT aurea_ncnn_POPULATED)
    FetchContent_Populate(aurea_ncnn)
    if(AUREA_AI_VULKAN)
        # GitHub source archives omit submodules. Populate the exact glslang
        # revision referenced by the pinned ncnn tree, not a moving branch.
        FetchContent_Declare(aurea_ai_glslang
            URL https://codeload.github.com/nihui/glslang/zip/a9ac7d5f307e5db5b8c4fbf904bdba8fca6283bc
            URL_HASH SHA256=7799500ebd4ba8b7b0e32503f33724d2308dd1da30cd5f22215014d5d2c40670
            SOURCE_DIR "${aurea_ncnn_SOURCE_DIR}/glslang")
        FetchContent_GetProperties(aurea_ai_glslang)
        if(NOT aurea_ai_glslang_POPULATED)
            FetchContent_Populate(aurea_ai_glslang)
        endif()
    endif()
    # Only this pinned graph and the CPU tensor/convolution helpers are needed.
    # Keep enum positions generated by upstream, with unused registry slots null.
    set(ai_layers input split convolution prelu pixelshuffle interp binaryop
        packing cast padding crop flatten reshape innerproduct gemm scale bias
        relu clip sigmoid mish hardswish tanh)
    file(STRINGS "${aurea_ncnn_SOURCE_DIR}/src/CMakeLists.txt" ai_layer_lines REGEX "^ncnn_add_layer\\(")
    foreach(line IN LISTS ai_layer_lines)
        string(REGEX REPLACE "^ncnn_add_layer\\(([A-Za-z0-9_]+).*" "\\1" name "${line}")
        string(TOLOWER "${name}" name)
        if(name IN_LIST ai_layers)
            set(WITH_LAYER_${name} ON CACHE BOOL "" FORCE)
        else()
            set(WITH_LAYER_${name} OFF CACHE BOOL "" FORCE)
        endif()
    endforeach()
    add_subdirectory("${aurea_ncnn_SOURCE_DIR}" "${aurea_ncnn_BINARY_DIR}" EXCLUDE_FROM_ALL)
endif()
if(MSVC)
    target_compile_options(ncnn PRIVATE /MP4)
endif()
set(ai_model_dir "${CMAKE_CURRENT_SOURCE_DIR}/assets/ai")
set(ai_model_cpp "${CMAKE_CURRENT_BINARY_DIR}/generated/AiModel.cpp")
file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/generated")
add_custom_command(OUTPUT "${ai_model_cpp}"
    COMMAND "${CMAKE_COMMAND}" "-DMODEL_DIR=${ai_model_dir}" "-DOUTPUT=${ai_model_cpp}"
            -P "${CMAKE_CURRENT_SOURCE_DIR}/cmake/EmbedUpscaleModel.cmake"
    DEPENDS "${ai_model_dir}/realesr-animevideov3.bin"
            "${ai_model_dir}/realesr-animevideov3-x2.param"
            "${ai_model_dir}/realesr-animevideov3-x4.param"
            "${CMAKE_CURRENT_SOURCE_DIR}/cmake/EmbedUpscaleModel.cmake"
    VERBATIM)
target_sources(aurea_core PRIVATE src/ai/Upscaler.cpp src/ai/TemporalStabilizer.cpp "${ai_model_cpp}")
target_link_libraries(aurea_core PRIVATE ncnn)
# Model/vector allocation failures are translated to Status at this boundary.
# The rest of the shared core retains its existing no-exceptions contract.
if(MSVC)
    set_source_files_properties(src/ai/Upscaler.cpp src/ai/TemporalStabilizer.cpp PROPERTIES COMPILE_OPTIONS /EHsc)
else()
    set_source_files_properties(src/ai/Upscaler.cpp src/ai/TemporalStabilizer.cpp PROPERTIES COMPILE_OPTIONS -fexceptions)
endif()
