# Shared inference; source, shader compiler and trained weights are pinned.
include(FetchContent)
if(APPLE)
    set(ai_vulkan_default OFF) # Metal builds do not ship a Vulkan loader.
else()
    set(ai_vulkan_default ON)
endif()
option(AUREA_AI_VULKAN "Enable ncnn Vulkan inference with CPU fallback" ${ai_vulkan_default})
set(NCNN_VULKAN ${AUREA_AI_VULKAN} CACHE BOOL "" FORCE)
set(NCNN_OPENMP OFF CACHE BOOL "" FORCE)
set(NCNN_INT8 OFF CACHE BOOL "" FORCE)
set(NCNN_DISABLE_EXCEPTION OFF CACHE BOOL "" FORCE)
# ncnn publishes -fno-rtti to its consumers when enabled. That would silently
# remove RTTI from aurea_core while ObjC++/other bridge targets still require
# typeinfo for its public polymorphic interfaces (e.g. VideoSourceFactory).
set(NCNN_DISABLE_RTTI OFF CACHE BOOL "" FORCE)
set(NCNN_BUILD_TOOLS OFF CACHE BOOL "" FORCE)
set(NCNN_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(NCNN_BUILD_BENCHMARK OFF CACHE BOOL "" FORCE)
set(NCNN_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(NCNN_INSTALL_SDK OFF CACHE BOOL "" FORCE)
set(NCNN_SHARED_LIB OFF CACHE BOOL "" FORCE)
set(NCNN_AVX512 OFF CACHE BOOL "" FORCE)
set(NCNN_AVX512VNNI OFF CACHE BOOL "" FORCE)
set(NCNN_AVX512BF16 OFF CACHE BOOL "" FORCE)
set(NCNN_AVX512FP16 OFF CACHE BOOL "" FORCE)
FetchContent_Declare(aurea_ncnn
    URL https://codeload.github.com/Tencent/ncnn/zip/305837fd4a722ebc47c5d72e72d8ec9ae970e932
    URL_HASH SHA256=1a25fea794145d2326974ebcbc4558292c77b741be0a239a522484b59bef61d6
)
FetchContent_GetProperties(aurea_ncnn)
if(NOT aurea_ncnn_POPULATED)
    FetchContent_Populate(aurea_ncnn)
    if(AUREA_AI_VULKAN)
        # GitHub source archives omit submodules. Populate the exact glslang
        # revision referenced by the pinned ncnn tree, not a moving branch.
        FetchContent_Declare(aurea_ai_glslang
            URL https://codeload.github.com/nihui/glslang/zip/a9ac7d5f307e5db5b8c4fbf904bdba8fca6283bc
            URL_HASH SHA256=7799500ebd4ba8b7b0e32503f33724d2308dd1da30cd5f22215014d5d2c40670
            SOURCE_DIR "${aurea_ncnn_SOURCE_DIR}/glslang")
        FetchContent_GetProperties(aurea_ai_glslang)
        if(NOT aurea_ai_glslang_POPULATED)
            FetchContent_Populate(aurea_ai_glslang)
        endif()
    endif()
    # Only the pinned graphs and the CPU tensor/convolution helpers are needed.
    # Keep enum positions generated by upstream, with unused registry slots null.
    # The depth graph (MiDaS v2.1 small) adds depthwise convolution, its
    # normalization constants (MemoryData) and the final Squeeze.
    set(ai_layers input split convolution prelu pixelshuffle interp binaryop
        packing cast padding crop flatten reshape innerproduct gemm scale bias
        relu clip sigmoid mish hardswish tanh convolutiondepthwise memorydata squeeze pooling concat)
    file(STRINGS "${aurea_ncnn_SOURCE_DIR}/src/CMakeLists.txt" ai_layer_lines REGEX "^ncnn_add_layer\\(")
    foreach(line IN LISTS ai_layer_lines)
        string(REGEX REPLACE "^ncnn_add_layer\\(([A-Za-z0-9_]+).*" "\\1" name "${line}")
        string(TOLOWER "${name}" name)
        if(name IN_LIST ai_layers)
            set(WITH_LAYER_${name} ON CACHE BOOL "" FORCE)
        else()
            set(WITH_LAYER_${name} OFF CACHE BOOL "" FORCE)
        endif()
    endforeach()
    # ncnn divide por subgroupSize ANTES de consultá-lo (instância Vulkan 1.1
    # sem VK_EXT_subgroup_size_control): vale 0 ali. No ARM a divisão inteira
    # por zero dá 0; no x86 (emulador, Chromebook) é SIGFPE e derrubava o app
    # ao abrir a prévia do Mapa de profundidade. Remendo idempotente.
    set(ai_gpu_cpp "${aurea_ncnn_SOURCE_DIR}/src/gpu.cpp")
    file(READ "${ai_gpu_cpp}" ai_gpu_src)
    string(REPLACE "maxComputeWorkGroupInvocations / querySubgroupProperties.subgroupSize, 1u)"
                   "maxComputeWorkGroupInvocations / std::max(querySubgroupProperties.subgroupSize, 1u), 1u)"
                   ai_gpu_patched "${ai_gpu_src}")
    if(NOT ai_gpu_patched STREQUAL ai_gpu_src)
        file(WRITE "${ai_gpu_cpp}" "${ai_gpu_patched}")
    endif()
    add_subdirectory("${aurea_ncnn_SOURCE_DIR}" "${aurea_ncnn_BINARY_DIR}" EXCLUDE_FROM_ALL)
endif()
if(MSVC)
    target_compile_options(ncnn PRIVATE /MP4)
endif()
set(ai_model_dir "${CMAKE_CURRENT_SOURCE_DIR}/assets/ai")
set(ai_model_cpp "${CMAKE_CURRENT_BINARY_DIR}/generated/AiModel.cpp")
file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/generated")
add_custom_command(OUTPUT "${ai_model_cpp}"
    COMMAND "${CMAKE_COMMAND}" "-DMODEL_DIR=${ai_model_dir}" "-DOUTPUT=${ai_model_cpp}"
            -P "${CMAKE_CURRENT_SOURCE_DIR}/cmake/EmbedUpscaleModel.cmake"
    DEPENDS "${ai_model_dir}/realesr-animevideov3.bin"
            "${ai_model_dir}/realesr-animevideov3-x2.param"
            "${ai_model_dir}/realesr-animevideov3-x4.param"
            "${CMAKE_CURRENT_SOURCE_DIR}/cmake/EmbedUpscaleModel.cmake"
    VERBATIM)
# Depth model (MiDaS v2.1 small): OUR ncnn conversion, fp16 storage, ~33 MB.
# Provenance, recipe and hashes: assets/ai/README.md. Clang/GCC (Android, iOS)
# embed the bytes with the assembler's .incbin; MSVC (host tests) has no
# .incbin and gets a generated hex table decoded once at first use.
set(ai_depth_bin "${ai_model_dir}/midas-v21-small-256.bin")
set(ai_depth_param "${ai_model_dir}/midas-v21-small-256.param")
set(ai_depth_cpp "${CMAKE_CURRENT_BINARY_DIR}/generated/AiDepthModel.cpp")
if(MSVC)
    add_custom_command(OUTPUT "${ai_depth_cpp}"
        COMMAND "${CMAKE_COMMAND}" "-DBIN=${ai_depth_bin}" "-DPARAM=${ai_depth_param}" "-DOUTPUT=${ai_depth_cpp}"
                -P "${CMAKE_CURRENT_SOURCE_DIR}/cmake/EmbedDepthModel.cmake"
        DEPENDS "${ai_depth_bin}" "${ai_depth_param}" "${CMAKE_CURRENT_SOURCE_DIR}/cmake/EmbedDepthModel.cmake"
        VERBATIM)
else()
    set(AI_DEPTH_BIN "${ai_depth_bin}")
    set(AI_DEPTH_PARAM "${ai_depth_param}")
    configure_file("${CMAKE_CURRENT_SOURCE_DIR}/cmake/AiDepthModel.incbin.cpp.in" "${ai_depth_cpp}" @ONLY)
    # The compiler's dependency scan does not see .incbin inputs.
    set_source_files_properties("${ai_depth_cpp}" PROPERTIES OBJECT_DEPENDS "${ai_depth_bin};${ai_depth_param}")
endif()
# Foreground segmentation ships with both apps. First use and reopened projects
# must not depend on an external download or writable model directory.
set(ai_foreground_bin "${CMAKE_CURRENT_SOURCE_DIR}/assets/rotobrush/u2netp.bin")
set(ai_foreground_param "${CMAKE_CURRENT_SOURCE_DIR}/assets/rotobrush/u2netp.param")
file(SHA256 "${ai_foreground_bin}" ai_foreground_bin_sha)
file(SHA256 "${ai_foreground_param}" ai_foreground_param_sha)
if(NOT ai_foreground_bin_sha STREQUAL "e9cbc6a779f02490ac16ef87e6b800d3b8dc29fe8cd65226318c089c5d21fd2e" OR
   NOT ai_foreground_param_sha STREQUAL "ab9567c0bfebecf51e8bb1292e2b4ca1bfb09006122a01bbba38a429ca94a4b0")
    message(FATAL_ERROR "Bundled U2Net-P model checksum mismatch")
endif()
set(ai_foreground_cpp "${CMAKE_CURRENT_BINARY_DIR}/generated/AiForegroundModel.cpp")
if(MSVC)
    add_custom_command(OUTPUT "${ai_foreground_cpp}"
        COMMAND "${CMAKE_COMMAND}" "-DBIN=${ai_foreground_bin}" "-DPARAM=${ai_foreground_param}" "-DOUTPUT=${ai_foreground_cpp}"
                -P "${CMAKE_CURRENT_SOURCE_DIR}/cmake/EmbedForegroundModel.cmake"
        DEPENDS "${ai_foreground_bin}" "${ai_foreground_param}"
                "${CMAKE_CURRENT_SOURCE_DIR}/cmake/EmbedForegroundModel.cmake"
                "${CMAKE_CURRENT_SOURCE_DIR}/cmake/EmbedDepthModel.cmake"
        VERBATIM)
else()
    set(AI_FOREGROUND_BIN "${ai_foreground_bin}")
    set(AI_FOREGROUND_PARAM "${ai_foreground_param}")
    configure_file("${CMAKE_CURRENT_SOURCE_DIR}/cmake/AiForegroundModel.incbin.cpp.in" "${ai_foreground_cpp}" @ONLY)
    set_source_files_properties("${ai_foreground_cpp}" PROPERTIES OBJECT_DEPENDS "${ai_foreground_bin};${ai_foreground_param}")
endif()
target_sources(aurea_core PRIVATE src/ai/Upscaler.cpp src/ai/TemporalStabilizer.cpp src/ai/DepthEstimator.cpp src/ai/ForegroundEstimator.cpp
               "${ai_model_cpp}" "${ai_depth_cpp}" "${ai_foreground_cpp}")
target_link_libraries(aurea_core PRIVATE ncnn)
# Model/vector allocation failures are translated to Status at this boundary.
# The rest of the shared core retains its existing no-exceptions contract.
if(MSVC)
    set_source_files_properties(src/ai/Upscaler.cpp src/ai/TemporalStabilizer.cpp src/ai/DepthEstimator.cpp src/ai/ForegroundEstimator.cpp src/ai/DepthMapService.cpp
                                PROPERTIES COMPILE_OPTIONS /EHsc)
else()
    set_source_files_properties(src/ai/Upscaler.cpp src/ai/TemporalStabilizer.cpp src/ai/DepthEstimator.cpp src/ai/ForegroundEstimator.cpp src/ai/DepthMapService.cpp
                                PROPERTIES COMPILE_OPTIONS -fexceptions)
endif()
