file(WRITE "${OUTPUT}" "#include <cstdint>\nnamespace aurea::ai::embedded {\n")
foreach(name IN ITEMS weights param2 param4)
    if(name STREQUAL "weights")
        set(path "${MODEL_DIR}/realesr-animevideov3.bin")
    elseif(name STREQUAL "param2")
        set(path "${MODEL_DIR}/realesr-animevideov3-x2.param")
    else()
        set(path "${MODEL_DIR}/realesr-animevideov3-x4.param")
    endif()
    file(SIZE "${path}" size)
    file(APPEND "${OUTPUT}" "alignas(16) static const unsigned char ${name}[] = {\n")
    set(offset 0)
    while(offset LESS size)
        file(READ "${path}" data OFFSET ${offset} LIMIT 256 HEX)
        string(REGEX REPLACE "(..)" "0x\\1," data "${data}")
        file(APPEND "${OUTPUT}" "${data}\n")
        math(EXPR offset "${offset} + 256")
    endwhile()
    file(APPEND "${OUTPUT}" "0};\n")
endforeach()
file(APPEND "${OUTPUT}" "const unsigned char* model_weights() { return weights; }\nconst char* model_param(unsigned scale) { return reinterpret_cast<const char*>(scale == 2 ? param2 : param4); }\n}\n")
